### ISSUE TITLE
Dict[slice, ...] is not valid

### ISSUE THREAD

**Issue by gvanrossum** [google/pytype#10]
I have a function like this:

```
def foo(a):
    return a[:10].lower()
```

The generated stub is:

```
def foo(a: bytes or str or unicode or Dict[slice, bytearray or bytes or str or unicode or List[?, ...] or Tuple[?, ...]]) -> bytearray or bytes or str or unicode
```

Now, it's cute that it figures out that if the argument were a dict with slice keys and string values it might work, but in fact slice does not implement hash() so `Dict[slice, ...]` is nonsense.

I'm also unclear on why it thinks that the value could be a List or Tuple, since neither of those has a lower() method.

**Comment by gvanrossum** [comment]
(Also bytearray is not valid in PY2; and bytes is just an alias for str so doesn't necessarily deserve mention. But maybe this deserves a separate issue.)

**Comment by matthiaskramm** [comment]
Yeah, at least List and Tuple are definitely a bug.

**Comment by gvanrossum** [comment]
Any reason why slice would not be a bug?

**Comment by matthiaskramm** [comment]
`slice` is a bug, too. Just a more subtle one.

**Comment by gvanrossum** [comment]
I was just showing the List/Tuple thing to Greg and he suggested that it
might be due to incorrectly putting in the parentheses?

**Comment by matthiaskramm** [comment]
It looks that way, doesn't it? I don't see how that could happen, but I have to dig into it more deeply.

**Comment by matthiaskramm** [comment]
Why is bytearray invalid in Python 2?

```
 $ python2.7
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> b = bytearray('FOO')
>>> b
bytearray(b'FOO')
>>> b[:10].lower()
bytearray(b'foo')
```

**Comment by gvanrossum** [comment]
My mistake. I thought it didn't exist. But it was added (for PY3
compatibility, I'm sure) in 2.6. So ignore that part. ;-)

On Fri, Jan 22, 2016 at 3:25 PM, Matthias Kramm <notifications@github.com>
wrote:

> Why is bytearray invalid in Python 2?
>
>  $ python2.7
> Python 2.7.6 (default, Jun 22 2015, 17:58:13)
> [GCC 4.8.2] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> >>> b = bytearray('FOO')
> >>> b
> bytearray(b'FOO')
> >>> b[:10].lower()
> bytearray(b'foo')
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/pytype/issues/10#issuecomment-174085610>.
>



-- 
--Guido van Rossum (python.org/~guido)

**Comment by matthiaskramm** [comment]
Moved the List/Slice issue into https://github.com/google/pytype/issues/15, since they have a very different root cause.

**Comment by matthiaskramm** [comment]
So the way I see it, to fix the `Dict[slice, ...]` issue, two things need to happen:

* typeshed needs a more precise definition of `dict`:
```
K = TypeVar('K', SupportsHash)
V = TypeVar('V')
class dict [...]
  def __setitem__(self, k: K, v: V) -> None: ...
```
with `SupportsHash` inheriting from Protocol (https://github.com/python/typing/issues/11#issuecomment-138133867)

* pytype needs to become aware of structural subtyping. I.e., it needs to understand that in the above, the possible types for `K` are all the types that implement the methods requested by `SupportsHash`.

**Comment by gvanrossum** [comment]
Technically you would need
```
K = TypeVar('K', bound=SupportsHash)
```
(The other form constrains it to *exactly* SupportsHash, which is not what is meant, although in a stub it doesn't actually matter.)

Also, it's Hashable, not SupportsHash (for historical reasons).

**Comment by rchen152** [comment]
This bug is obsolete, as pytype no longer infers nominal types for function parameters. (Well, currently it doesn't infer parameter types at all, but it may eventually infer structural types if the `--protocols` flag makes it out of experimental.)
