### ISSUE TITLE
possible false positive - [wrong-arg-types] when using `path_type` argument to `click.Path()`

### ISSUE THREAD

**Issue by nik-sm** [google/pytype#1005]
The library `click` provides decorators for handling command line arguments.
They include a class called `click.Path` for handling path-like inputs. This class has an optional constructor arg `path_type`, so that you can have a command line argument such as `--infile /path/to/myfile.txt` be processed into `pathlib.Path("/path/to/myfile.txt")`.

Attempting to use this `path_type` constructor arg causes pytype to declare `wrong-arg-types`.

I'm not sure whether this is a pytype bug - but I suspect so because I believe it is the correct usage of `click.Path` and the code runs as expected.

Here's a minimal example:

```python
import click
from pathlib import Path


@click.command()
@click.option("--infile", type=click.Path(path_type=Path))
def main(infile):
    print(f"{infile=}")


if __name__ == "__main__":
    main()
```

Running it gives:

```shell
$ python pytype-decorator.py --infile foo/bar/baz
infile=PosixPath('foo/bar/baz')
```

Running pytype gives:

```shell
$ pytype code-scraps/pytype-decorator.py
Computing dependencies
Analyzing 1 sources with 0 local dependencies
ninja: Entering directory `.pytype'
[1/1] check pytype-decorator
FAILED: .../pytype-decorator.pyi 
.../python3 -m pytype.single --imports_info .../.pytype/imports/pytype-decorator.imports --module-name pytype-decorator -V 3.8 -o .../.pytype/pyi/pytype-decorator.pyi --analyze-annotated --nofail --quick .../pytype-decorator.py
File ".../pytype-decorator.py", line 6, in <module>: Function Path.__init__ was called with the wrong arguments [wrong-arg-types]
         Expected: (self, exists, file_okay, dir_okay, writable, readable, resolve_path, allow_dash, path_type: Optional[Type[Union[bytes, str]]] = ...)
  Actually passed: (self, path_type: Type[pathlib.Path])

For more details, see https://google.github.io/pytype/errors.html#wrong-arg-types
ninja: build stopped: subcommand failed.
Leaving directory '.pytype'
```

```shell
$ pytype --version                      
2021.08.24
```

**Comment by nik-sm** [comment]
Forgot to include - running the same example without the `path_type` argument gives no errors:


```python
import click


@click.command()
@click.option("--infile", type=click.Path())
def main(infile):
    print(f"{infile=}")


if __name__ == "__main__":
    main()
```

```shell
$ pytype pytype-decorator.py
...
Success: no errors found
```

**Comment by rchen152** [comment]
It looks like pytype is using the [typeshed](https://github.com/python/typeshed/tree/master/stubs/click) click stubs, which were made obsolete in version 8.0 due to click adding a `py.typed` marker in 8.0. The ability to pass in `pathlib.Path` for `path_type` is also new in 8.0 and is therefore not reflected in typeshed's stubs. What we really need to do is fix https://github.com/google/pytype/issues/151, so pytype knows to use click's inline type information.
