### ISSUE TITLE
incorrect [attribute-error] for `multiprocessing.current_process()._identity[0]`

### ISSUE THREAD

**Issue by nik-sm** [google/pytype#1010]
This snippet works, but pytype gives `[attribute-error]`:

`File "scrap.py", line 6, in worker_fn: No attribute '_identity' on multiprocessing.process.BaseProcess [attribute-error]`

```python
import multiprocessing
from multiprocessing import Pool


def worker_fn(x):
    worker_idx = multiprocessing.current_process()._identity[0]
    print(f"worker idx: {worker_idx}")
    return x ** 2


with Pool(4) as pool:
    results = pool.map(worker_fn, range(8))

print(results)

```

```shell
$ pytype --version
2021.09.09
```

**Comment by rchen152** [comment]
We'll need to add the `_identity` attribute (with an `# undocumented` comment) to the BaseProcess here: https://github.com/python/typeshed/blob/master/stdlib/multiprocessing/process.pyi.

**Comment by rchen152** [comment]
This has been fixed upstream: https://github.com/python/typeshed/pull/6041. The fix will be pulled in the next time we do a typeshed update.
