### ISSUE TITLE
Type checking fails to work properly in ```@property``` decorated functions

### ISSUE THREAD

**Issue by peakay** [google/pytype#1016]
```
class Test:
    @property
    def A(self):
        self.b(123)
        
    def b(self, item: str):
        print(item)
```
passes pytype fine (when it should not), where as 

```
class Test:
    def A(self):
        self.b(123)
        
    def b(self, item: str):
        print(item)
```

results in

```
File "bad_type.py", line 5, in A: Function Test.b was called with the wrong arguments [wrong-arg-types]
         Expected: (self, item: str)
  Actually passed: (self, item: int)
```

which is the expected behavior

**Comment by rchen152** [comment]
For type-checking of properties to work properly, you need to (for now) pass the `--bind-properties` flag to pytype. The behavior of `--bind-properties` will eventually be enabled by default, but we need to do some cleanup of Google-internal code first.
