### ISSUE TITLE
Pytype - type stubs and typeshed

### ISSUE THREAD

**Issue by SandyChapman** [google/pytype#1032]
I'm in the process of upgrading `pytype` from `2021.04.09` to `2021.10.11`. However, the version bump causes `pytype` to report many issues in `beautifulsoup4` because of the version of `typeshed` used:

Example:

```
File "/Users/schapman/workspace/pytype-testing/main.py", line 9, in <module>: Function print_tag was called with the wrong arguments [wrong-arg-types]
         Expected: (tag: bs4.element.Tag)
  Actually passed: (tag: bs4.element.PageElement)
```

I see in the latest `typeshed` version that the type annotation in `beautifulsoup4` has been updated to correct the issue. 

My questions:

1. Is there any way to override `pytype`'s use of its built-in `typeshed` and instead use the `types-beautifulsoup4` package? I understand I can set `TYPESHED_HOME` with the updated version, but would rather avoid maintaining our own submodule for `typeshed` in the repo.
2. What are the concerns/processes for updating the submodule reference? Can I just open a PR with the updated submodule and have the updates in the next `typeshed` release that seems to happen every week or two?

Thanks!

**Comment by rchen152** [comment]
I've updated us to https://github.com/python/typeshed/commit/3b6a52b8581bde232a36c407f08c51564b00597a from Nov 29, so closing this issue. The typeshed update will be in the next pytype release (likely early next week).
