### ISSUE TITLE
Add support to release linux aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [google/pytype#1037]
Problem
---------
On aarch64, `pip install pytype` builds the wheels from source code and then installs it. It requires the user to have a development environment installed on their system. Also, it takes more time to build the wheels than downloading and extracting the wheels from PyPI.

Resolution
-----------
On aarch64, `pip install pytype` should download the wheels from PyPI.

@rchen152, Please let me know your interest in releasing aarch64 wheels. I can help with this.

**Comment by rchen152** [comment]
Sorry for the slow response! Releasing aarch64 wheels sounds like a good idea. I tried what seemed to me the "obvious" idea of using the docker/setup-qemu-action action and a manylinux2014_aarch64  image (https://github.com/google/pytype/commit/7f4b267e97eda0965da32e7c025e028d533376b1), but I noticed that (1) the Build wheel workflow became super slow, and (2) it eventually failed with a cryptic error about "bad ELF interpreter" (https://github.com/google/pytype/actions/runs/1397022437). I'll take another stab at it sometime this week, but I'm also not too familiar with the process of building and releasing wheels (our current setup was contributed by another user ^^;), so I'd love some help!

**Comment by odidev** [comment]
Hi @rchen152
I built Linux AArch64 wheels on GitHub Actions. The error “bad ELF interpreter" was solved by building ninja from source. Below are the changes and logs for the same:

Changes: https://github.com/odidev/pytype/commit/9cede67c5dc0002c70661f70b6986fb609748dbc
Logs: https://github.com/odidev/pytype/actions/runs/1411337383

Could you please have a look and share your feedback and let me know of your interest in raising a PR for the same?

**Comment by rchen152** [comment]
Wow, thanks! I left a minor comment on the commit itself, but overall, I think it's in a good state for a PR :)

One question about the time the Build wheels workflow takes - building the other wheels only takes about 5 min, but aarch64 wheels take 50 min to build - I assume this is because emulation is slow? I think this will still be acceptable, if just barely, but if it does turn out that waiting 50 min for wheels feels unbearably slow, do you know if there are any ways we might be able to speed this up in the future?

**Comment by rchen152** [comment]
Thanks, those are great suggestions! (For simplicity, I'd prefer to stick with GitHub Actions for everything.)

**Comment by rchen152** [comment]
pytype-2021.11.12 ships aarch64 wheels. @odidev Thanks for contributing this!
