### ISSUE TITLE
'gym.utils.colorize' object is not callable [not-callable]

### ISSUE THREAD

**Issue by ikamensh** [google/pytype#1039]
I'm running `pytype` on openai/gym, commit 7869eca8 [https://github.com/openai/gym/commit/7869eca817985b971771a8650a3d4520f719007c] and I get following errors:

File "/Users/kai7rng/oss/gym/gym/logger.py", line 36, in warn: 'gym.utils.colorize' object is not callable [not-callable]
File "/Users/kai7rng/oss/gym/gym/logger.py", line 48, in error: 'gym.utils.colorize' object is not callable [not-callable]

This is incorrect, because:
* `gym.utils.__init__.py` has `from .colorize import colorize`
* `gym.utils.colorize` has `def colorize(...)`, meaning it's a funciton (callable).
* importing by `from gym.utils import colorize` should then retrieve the callable, not the module `colorize`

The code also works when run.

Note:
To get this error, you will need to comment out lines 125-127 in `gym/error.py`

```
> pytype --version                                                                                                                                                      
2021.10.25
```

**Comment by rchen152** [comment]
Thanks for the report! This looks like the same issue as https://github.com/google/pytype/issues/264, so I'm going to close this bug in favor of that one.
