### ISSUE TITLE
astroid does not allow typed-ast 1.5.0

### ISSUE THREAD

**Issue by rchen152** [google/pytype#1047]
astroid pins typed-ast to >=1.4.0,<1.5 (https://github.com/PyCQA/astroid/blob/main/setup.cfg). This is a problem because typed-ast 1.5.0 contains a fix for https://github.com/google/pytype/issues/1044. I'm working around this for now by manually installing dependencies for astroid and pylint, then installing them with --no-dependencies.

**Comment by srittau** [comment]
astroid 2.8.5 will pin typed-ast to >=1.4.0,<2.

**Comment by rchen152** [comment]
Great to know, thanks!
