### ISSUE TITLE
Unify union of a class with a subclass of it?

### ISSUE THREAD

**Issue by gvanrossum** [google/pytype#11]
Why would you ever write "bool or int" (or "Union[bool, int]" in PEP 484 speak)? Since bool is a subclass of int, this can be simplified to just "int".

**Comment by matthiaskramm** [comment]
It can! We just need to do that simplification. We have a simplifier for pyi in https://github.com/google/pytype/blob/master/pytype/pytd/optimize.py, it just needs to be made aware of this transformation.

**Comment by matthiaskramm** [comment]
Fix is in code review.

**Comment by matthiaskramm** [comment]
Pushed.
