### ISSUE TITLE
Question: pytype automated casting from Any depending on function output

### ISSUE THREAD

**Issue by theahura** [google/pytype#1117]
Hey folks, 

Given the following code;
```
def foo() --> Any:
  return 'test'
  
def bar() --> str:
  return foo()
```
does pytype end up typing the return of `bar()` as `str` or as `Any`?

More specifically, I have a StatusOr type that is defined like so:
```python
class StatusOr(Generic[T]):
   status: STATUS  # an enum
   value: Optional[T] # always None if ok() returns false

   def ok():
      return self.status === OK
   
def copy_error(status_or: StatusOr[Any]) -> StatusOr[Any]:
  return StatusOr(**status_or_fields)
```
which then gets used like so:

```python
def foo() -> StatusOr[int]:
  if math.random() > 0.5:
     return StatusOr(OK, 10)
  return StatusOr(ERR)
  
def bar() --> StatusOr[str]:
  maybe_int = foo()
  if not maybe_int.ok():
    return copy_error(maybe_int)
  return StatusOr(OK, 'hello')
``` 

The idea is that the copy_error function allows an implicit cast from StatusOr[int] to StatusOr[str], without me having to write any specific casting logic, which can be convenient when the StatusOr type gets passed through a function that can potentially return a lot of different status or types. Because the StatusOr value is None when there is an error, it should also work out at runtime.

However, this depends on pytype knowing to return the type of the function, not the type returned by copy_error. In more recent versions of pytype, this logic seems to be causing errors. Not sure if this is a mistake on my end, a mistake with pytype, or if I'm just doing this wrong.

Thanks for the help!

**Comment by rchen152** [comment]
The "implicit cast" you described ought to work with pytype - it should be using the function's return type annotation over the inferred type of whatever is being returned. I tried constructing a full example out of the provided code snippets, and pytype doesn't report any errors on this:
```
import dataclasses
import enum
import random
from typing import Any, Generic, Optional, TypeVar
T = TypeVar('T')

class STATUS(enum.Enum):
  OK = 'ok'
  ERR = 'err'

@dataclasses.dataclass
class StatusOr(Generic[T]):
   status: STATUS  # an enum
   value: Optional[T] # always None if ok() returns false

   def ok(self):
      return self.status == STATUS.OK

def copy_error(status_or: StatusOr[Any]) -> StatusOr[Any]:
  return StatusOr(status_or.status, status_or.value)

def foo() -> StatusOr[int]:
  if random.random() > 0.5:
     return StatusOr(STATUS.OK, 10)
  return StatusOr(STATUS.ERR, 42)

def bar() -> StatusOr[str]:
  maybe_int = foo()
  if not maybe_int.ok():
    return copy_error(maybe_int)
```

Do you have an example of code that pytype is struggling with?

One possible issue is that, if your code makes heavy use of enums, you'll need to use the `--use-enum-overlay` flag.

**Comment by rchen152** [comment]
Do you still need help on this issue?

**Comment by theahura** [comment]
I think I'm good, thanks for checking!
