### ISSUE TITLE
python3 vs python3.8 on PATH

### ISSUE THREAD

**Issue by ngam** [google/pytype#1129]
```
$ pytype
CRITICAL Could not find a valid python3.8 interpreter in path (found Python 2.7.18)

$ pytype -V 3.8
CRITICAL Could not find a valid python3.8 interpreter in path (found Python 2.7.18)

$ pytype -V 3
Computing dependencies
...
    exe = 'python%d.%d' % version
TypeError: not enough arguments for format string

$ pytype -V 2
Computing dependencies
...
    exe = 'python%d.%d' % version
TypeError: not enough arguments for format string
```

pytype isn't happy to settle for python3 when locating python3.8 on the path, and would persist in failing. A solution is to symlink python3.8 somewhere on the PATH (which works btw, e.g. `sudo ln -s /usr/bin/python3 /usr/local/bin/python3.8`). I tried to look into your code, but I couldn't really find where exactly it is being super picky. I think it might be beneficial to loosen this a little, but that might cause other issues elsewhere. Just reporting this here. 

Fwiw, this is on MacOS 12.2.1, Python 3.8.9 (as well as Python 2.7.18), and ptype 2022.02.08.

**Comment by not-my-profile** [comment]
On that note why does pytype require the interpreter version to match the `--python-version`?

Mypy accepts `--python-version 3.8` even when `python --version` is 3.9. Pytype seems to already set the `feature_version` for `ast.parse` shouldn't that suffice?

**Comment by martindemello** [comment]
pytype works on the python bytecode, so we need a valid python executable to compile the source into the correct bytecode for each version.
