### ISSUE TITLE
Proper way to set `Final` annotated variables as default args.

### ISSUE THREAD

**Issue by benjaminrwilson** [google/pytype#1147]
Hi,

Thank you for this work! I had a quick question related to the use of the `Final` annotation. What is the proper way to handle the below snippet?

```
from math import pi

PI: Final[float] = pi

def add_constant(x: float, y: float = PI) -> float:
    return x + y
```
results in:

```
Type annotation for y does not match type of assignment [annotation-type-mismatch]
  Annotation: float
  Assignment: Final[float]

For more details, see https://google.github.io/pytype/errors.html#annotation-type-mismatch
```

I know this example is a bit contrived --- the `Final` variable would typically be imported from a `constants.py` file for the library. Is there a straightforward way to handle this without annotating with `# pytype: disable=annotation-type-mismatch`?

Thanks in advance!

**Comment by martindemello** [comment]
that looks like a bug on our end; it should definitely be allowed to initialise a `float` with a `Final[float]`

**Comment by martindemello** [comment]
shouldn't be too hard! i'll take a look at it.

**Comment by martindemello** [comment]
i couldn't reproduce the error

```
$ cat bugs/foo.py 
from typing_extensions import Final
from math import pi

PI: Final[float] = pi

def add_constant(x: float, y: float = PI) -> float:
  return x + y

$ pytype --version
2022.03.08

$ pytype bugs/foo.py 
Computing dependencies
Analyzing 1 sources with 0 local dependencies
ninja: Entering directory `.pytype'
[1/1] check foo
Leaving directory '.pytype'
Success: no errors found
```

**Comment by benjaminrwilson** [comment]
Thanks for checking, @martindemello. I confirmed that I do not get an error with the above setup. Would you mind moving `PI: Final[float] = pi` to a separate file `constants.py` and try importing from `foo.py`? I'm able to reproduce the error with this setup.

**Comment by martindemello** [comment]
confirmed! looking into it.
