### ISSUE TITLE
Adding type annotation for class instance

### ISSUE THREAD

**Issue by aravind-spnp** [google/pytype#1148]
```python
from django.http import HttpRequest

class Runner:
    def run(self, command: str) -> None:
        eval(command)

def check_here(request: HttpRequest, runner):
    runner.run(request.GET["command"])
```

In the above example is there any possibility to annotate the runner instance automatically as `def check_here(request: HttpRequest, runner: Runner)` using pytype? If there is a possibility how to accomplish that?

**Comment by martindemello** [comment]
this should work exactly as you said:

```
def check_here(request: HttpRequest, runner: Runner):
```

do you get any errors if you do that?

**Comment by aravind-spnp** [comment]
@martindemello Is there any other possible way to add annotation automatically to runner instance? Because i have many python repositories without type annotation / definition. My goal is to annotate all the python repositories including the case i mentioned. Could you please suggest a way to do achieve this?

**Comment by martindemello** [comment]
take a look at https://github.com/Instagram/MonkeyType and see if it's helpful.

**Comment by aravind-spnp** [comment]
@martindemello I think they get the type at runtime

**Comment by aravind-spnp** [comment]
@martindemello  I think they try to get the type information at runtime(by simulating call traces).... but my requirement is to get the type information of the class instance in a static way since i don't have provisions and dependencies to execute the code. Is there any other alternative or workaround?

**Comment by martindemello** [comment]
I don't think so - pytype will just infer `Any` for the type of `runner`, because there is not enough information to statically determine the type. The issue is that python itself will accept anything that has a `run()` method; there is nothing to say that just because `Runner` provides that method it is the type that that function wants.

**Comment by aravind-spnp** [comment]
okie...Thanks @martindemello
