### ISSUE TITLE
Dependency on obsolete lib2to3.

### ISSUE THREAD

**Issue by mrolle45** [google/pytype#1155]
There will come a point in the future when lib2to3 will no longer work.  Sorry for the bad news.

To quote the lib2to3 doc:
Python 3.10 includes new language syntax that is not parseable by lib2to3’s LL(1) parser (see [PEP 634](https://www.python.org/dev/peps/pep-0634)).
That implies that pytype will not be able to support 3.10 code.

I don't know how many of pytype's tools use lib2to3.  I know that merge_pyi does, and so it will have to be rewritten significantly, at least for 3.10+ code.

I suppose that the best solution is to use the `ast` library module, and then work with the resulting syntax trees.  The mypy code may need to differ with the running Python release if `ast` has incompatible changes.  It also means that if the user has an option for the Python release of the source code, it will have to be within the range that `ast` will accept.  Python 2 source files will have to be processed by mypy on a 2.7 release.

Good luck with the rewrites.  However, it will be necessary when your users (like all the projects at Google) want to use new features in Python 3.10.

**Comment by mrolle45** [comment]
You might look at how `mypy` handles syntax trees for inspiration or code reuse.

**Comment by martindemello** [comment]
thanks, @mrolle45! we are currently rewriting merge_pyi to use libcst instead of lib2to3, it should be merged in soon.
