### ISSUE TITLE
Would like recursive and backup capabilities for merge-pyi

### ISSUE THREAD

**Issue by mrolle45** [google/pytype#1164]
I'm reluctant to use `merge-pyi -i` because I want to be able to get my original `.py` files back.
Could you add an option, something like `-b` or `--backup`.  The option value would be either a suffix to be appended to the file names, or if it is a directory, store the backup in that directory (with the intervening directories if any).
That is,
`merge-pyi -i -b .save foo.py <pyi file>` would create `foo.py.save`.
`merge-pyi -i -b .save bar/foo.py <pyi file>` would create `bar/foo.py.save`.
Or if `save` is a directory,
`merge-pyi -i -b save foo.py <pyi file>` would create `save/foo.py`.
`merge-pyi -i -b save bar/foo.py <pyi file>` would create `save/bar/foo.py`.
Without this, I need to write a script which will copy my input file to a backup, then run merge-pyi -i.

Also, if you can come up with a syntax for specifying multiple `.py` files (perhaps using a glob style and/or multiple arguments), that would be nice.  You'd have to devise a way of matching each `.py` name to a sub file name.

**Comment by martindemello** [comment]
thanks, that's a good idea! i'll implement it in the new merge-pyi, which is just waiting for a libcst pull request to go through before we can release it,

**Comment by martindemello** [comment]
should work now with `merge-project <root-of-py-tree> <root-of-pyi-tree> [--backup <backup extension>]`
