### ISSUE TITLE
merge-pyi inserts duplicate global defs

### ISSUE THREAD

**Issue by mrolle45** [google/pytype#1168]
If my py file contains some assignments which are also in the pyi file, then the ones from the pyi are copied into the resulting output.  The result is that this is a duplication.

I would expect that the assign from the pyi would _replace_ the one of the same name.

When I run `merge-pyi -i` then the replaced py file now has the new assigns (correctly).  But if I run merge-pyi again, then I get two identical blocks of assigns.

Not only is this a nuisance, but it could cause an error in my program.  If I have changed my source, then run pytype on it, the new pyi could have a changed value for some of those assigns.  Then after merge-pyi, the new assigns will appear before the old assigns, so that I get the old value in the end.

The code for `add_globals` begins with
```
  def add_globals(self, tree, inserted_types):
    """Add required globals to the tree. Idempotent."""
    # Copy imports if not already present
```
So this is clearly the intended behavior.  However, when I run it on my code, it doesn't happen.

`self.assignments` comes from some of the assignment statements in the pyi file.  It chooses anything starting with '_' (so this caches __all__), and anything with a TypeVar.

`add_globals` needs to look at each of these and see if they already exist in the py file and insert only those that don't already exist.

**Comment by mrolle45** [comment]
**Fix**

Use this code in `merge_pyi.py`:
```
class Pyi(collections.namedtuple('Pyi', 'imports assignments funcs')):
  ...
  def add_globals(self, tree, inserted_types):
    """Add required globals to the tree. Idempotent."""
    # Remove any children from the py tree that match any pyi assigns.
    pyi_assign_targets = set(map(self.match_assign_target, self.assignments))

    tree.children = list(filter(lambda child: self.match_assign_target(child) not in pyi_assign_targets, tree.children))
    ...
  def match_assign_target(self, node):
      results = {}
      if self.assign_pattern.match(node, results):
          # This is an assign statement
          return node.children[0].children[0].value
      else:
          return None
```
This removes all duplicate top level assigns from the py file tree _before_ inserting the pyi file assigns (and before looking for the place to insert them).

**Comment by mrolle45** [comment]
There was an error in my code for the new method `match_assign_target`.  Here is the correct code:
```
  def match_assign_target(self, node):
      results = {}
      if self.assign_pattern.match(node, results):
          # This is an assign statement
          try: return node.children[0].children[0].value
          except: pass
      else:
          return None
```
Some assignments don't have a `node.children[0].children[0].value`.

**Comment by mrolle45** [comment]
This is still wrong, as I discovered after running merge_pyi on the files in my project.

Here's an example.
```
common.py:
_ErrorRe = re.compile(r'INVALID|ILLEGAL|\?\?\?|error|(?<!\()\?')

common.pyi:
_ErrorRe: Pattern[str]
```
What I would like to see after the merge is both lines:
```
_ErrorRe: Pattern[str]
...
_ErrorRe = re.compile(r'INVALID|ILLEGAL|\?\?\?|error|(?<!\()\?')
```
Even nicer would be
```
_ErrorRe: Pattern[str] = re.compile(r'INVALID|ILLEGAL|\?\?\?|error|(?<!\()\?')
```
So my proposed code in the previous comment didn't distinguish between an assignment and a bare type hint.
What I wanted to do was eliminate the duplicated type hints resulting from the py file having been already merged with the pyi file.  In that case, I want to remove the existing type hint from the new merge, but not an assign.
The code's `self.assign_pattern` was misnamed, perhaps, because it matches both assignments and bare type hints.
So please don't put my proposed fix into the code.  Let me work on it some more and get it to do the right thing.

**Comment by rchen152** [comment]
I believe this is obsolete, since we've started the process of moving merge-pyi to use libcst (https://github.com/google/pytype/commit/1937781b69d53168970535d6ab0d378b03d619b7). (Also, just a heads up - the behavior of merge-pyi may be a little odd for a bit, since we're depending on an unreleased libcst commit. If this is causing you trouble, please either pin to a pytype release before 2022.04.15 or install https://github.com/Instagram/LibCST from source.)
