### ISSUE TITLE
Could pytype be used to optimized python programs?

### ISSUE THREAD

**Issue by happycr** [google/pytype#1177]
If I understand correctly, pytype totally infers the type of python variables and functions (albeit sometimes as union types).
Essentially, this converts python from a dynamically typed language to a statically typed language  ( since pytype knows the type of everything ). 
One of the most common cited reasons for the slowness of python is that it is dynamically typed. However, pytype makes it statically typed, so I was wondering if pytype could further optimize python programs?

**Comment by rchen152** [comment]
Hello! Python performance optimization isn't something that we've explored for pytype, but in general, it is possible to use static typing for this. Check out, for example, mypyc: https://github.com/mypyc/mypyc.
