### ISSUE TITLE
inspect._ParameterKind is being downgraded to int

### ISSUE THREAD

**Issue by taralx** [google/pytype#1182]
I tried a few tests, and it seems to only affect .pyi files, not local declarations.

Testcase:
```python
import inspect

def cause_type_error(k):
    return inspect.Parameter(k, inspect.Parameter.KEYWORD_ONLY)
```

**Comment by rchen152** [comment]
This is happening because our enum support isn't fully rolled out yet. Run pytype with the `--use-enum-overlay` flag, and the problem should go away.
