### ISSUE TITLE
Functional typeddict constructor support

### ISSUE THREAD

**Issue by theahura** [google/pytype#1184]
I have a bunch of jsonschemas that represent existing data structures in our DB. I wanted to add typeddict types in our python code that represent these structures. One of these structures uses `global` as a field, which is a python reserved keyword. 

The proposed way to get around this is to use the TypedDict functional constructor syntax, but it looks like pytype doesn't support that yet (got: `TypedDict functional constructor not supported yet [not-supported-yet]` when I tried to use it).

Is this something that is coming in the pipeline soon? 
Thanks!

**Comment by rchen152** [comment]
I believe we were hoping to not have to support the functional constructor, but using keywords as field names sounds like a legitimate (if niche) use case that the class-based constructor can't handle.

**Comment by martindemello** [comment]
agreed, this is a case where "use the class constructor" is not a valid workaround
