### ISSUE TITLE
Pytype incorrectly ignoring TypedDict variable type annotations

### ISSUE THREAD

**Issue by theahura** [google/pytype#1185]
I'm running into a bug where Pytype is incorrectly ignoring a TypedDict variable type annotation. 

A minimal reproducing example on 2022.04.15:
```python
class Foo(TypedDict, total=False):
  name: Literal['FOO']

test: Foo = {
    'name': 'FOO',
}
reveal_type(test)
```

results in 
```
(env) soot@soot:~/code/soot/experimental/amol/pytype-typedict-test$ pytype test.py --enable-typed-dict
Computing dependencies
Analyzing 1 sources with 0 local dependencies
ninja: Entering directory `.pytype'
[1/1] check test
FAILED: /home/soot/code/soot/experimental/amol/pytype-typedict-test/.pytype/pyi/test.pyi 
/home/soot/code/soot/experimental/amol/pytype-typedict-test/env/bin/python3 -m pytype.single --imports_info /home/soot/code/soot/experimental/amol/pytype-typedict-test/.pytype/imports/test.imports --module-name test --platform linux -V 3.8 -o /home/soot/code/soot/experimental/amol/pytype-typedict-test/.pytype/pyi/test.pyi --analyze-annotated --enable-typed-dicts --nofail --quick /home/soot/code/soot/experimental/amol/pytype-typedict-test/test.py

File "/home/soot/code/soot/experimental/amol/pytype-typedict-test/test.py", line 36, in <module>: Dict[str, str] [reveal-type]

For more details, see https://google.github.io/pytype/errors.html#reveal-type
```

In particular, it looks like Pytype is calling `test` a `Dict[str, str]` instead of type `Foo`. 

Would appreciate any help!

**Comment by rchen152** [comment]
I'm pretty sure this is a bug in how we print types. Internally, `test` does appear to be represented as a TypeDict; I played around a bit with passing it to functions that accept various typed dicts, and the accept/reject behavior looks correct.

**Comment by rchen152** [comment]
I played around with this a bit more, and the underlying issue is that when a TypedDict is instantiated, its type is set to `dict` rather than the `TypedDict` subclass. This causes problems with not just `reveal_type` but also cases like:
```
def f():
  test: Foo = {
      'name': 'FOO',
  }
  return test
```
The return type of `f()` is inferred as `Dict[str, str]` rather than `Foo`.

**Comment by theahura** [comment]
I was wondering about that! I had observed something similar but chalked it up to some weird casting in my codebase :sweat_smile:

**Comment by martindemello** [comment]
okay, that was an easy fix, we were deliberately dropping the TypedDict type on annotated assignments after checking that the concrete dictionary was valid. not sure why, i suspect because i misread the spec.
