### ISSUE TITLE
Invalid [bad-unpacking] error when using "catch-all"

### ISSUE THREAD

**Issue by chuckwondo** [google/pytype#1207]
When using a "catch-all" with unpacking, pytype incorrectly reports a [bad-unpacking] error.

As a simple case:

```python
first, *rest = ["foo"]
```

This is valid, where `first` is assigned `"foo"` and `rest` is assigned `[]`, but pytype reports:

```
Cannot unpack 1 value into 2 variables [bad-unpacking]
```

When pytype analyzes such unpacking, it should not count the "catch-all" on the LHS (if there is one) in its variable count for comparison to the length of the value on the RHS.

Conversely, in the following case, Python will produce a `ValueError`, but pytype does _not_ produce an error:

```python
first, *rest = []
```

**Comment by martindemello** [comment]
thanks, looks like we have some errors in our sequence unpacking logic!

**Comment by rchen152** [comment]
Looks like this is fixed!
