### ISSUE TITLE
No attribute 'nbytes' on memoryview [attribute-error]

### ISSUE THREAD

**Issue by anarkiwi** [google/pytype#1225]
Discovered by @ltindall.

$ pytype --version
2022.06.06
$ python3 --version
Python 3.10.4
$ cat test.py 
print(memoryview(b'123').nbytes)
$ python3 test.py 
3
$ pytype test.py 
Computing dependencies
Analyzing 1 sources with 0 local dependencies
ninja: Entering directory `.pytype'
[1/1] check test
FAILED: /home/josh/tmp/.pytype/pyi/test.pyi 
/usr/bin/python3 -m pytype.single --imports_info /home/josh/tmp/.pytype/imports/test.imports --module-name test --platform linux -V 3.10 -o /home/josh/tmp/.pytype/pyi/test.pyi --analyze-annotated --nofail --quick /home/josh/tmp/test.py
File "/home/josh/tmp/test.py", line 1, in <module>: No attribute 'nbytes' on memoryview [attribute-error]

For more details, see https://google.github.io/pytype/errors.html#attribute-error
ninja: build stopped: subcommand failed.
Leaving directory '.pytype'

**Comment by rchen152** [comment]
Huh, nbytes has been around since Python 3.3! I'm surprised we've gone this long without anyone noticing it was missing.
