### ISSUE TITLE
Couldn't import pyi for 'sqlalchemy.dialects.postgresql'

### ISSUE THREAD

**Issue by chadhamre** [google/pytype#1240]
Example:

`from sqlalchemy.dialects.postgresql import ENUM, UUID`

run pytype

`
Couldn't import pyi for 'sqlalchemy.dialects.postgresql' [pyi-error]
  Can't find pyi for 'sqltypes.ARRAY', referenced from 'sqlalchemy.dialects.postgresql.array'
`

**Comment by rchen152** [comment]
Sorry for the slow response! This appears to be https://github.com/google/pytype/issues/1087 (pytype can't parse typeshed's sqlalchemy stubs), so I'm going to close this issue and copy the error message over.

**Comment by rchen152** [comment]
In the meantime, you can unblock yourself by disabling pyi-error. If it's just one problematic import, you can add `# pytype: disable=pyi-error` at the end of the import line in the source code. If there are a lot of pyi errors, then alternatively you can add a setup.cfg file and disable them there: https://github.com/google/pytype#config-file.
