### ISSUE TITLE
[Question] Does the dataflow algorithm of pytype have any papers/references? 

### ISSUE THREAD

**Issue by iSika-PKU** [google/pytype#1249]
Hello! I have used pytype for some time and found that the dataflow algorithm is particularly accurate, e.g., it can type the following program without a type error. 

```
import random
r = random.randrange(0, 2)
if r == 0:
	x=1
elif r == 1:
	x='1'

if isinstance(x, int):
    y = 1

elif isinstance(x, str):
    y = '1'
z = y + x
```

I looked at the code, and as far as I am concerned, the dataflow framework is basically a points-to analysis. What makes it such accurate is the backward checking of the type error combinations, i.e., the "Reachability" and "Solver" in the documentation.
I have some knowledge of pointer analysis and concrete type inference, but I do not found any papers introducing such a demand-driven style of handling points-to combinations. So I am wondering if it is developed by pytype specifically, or, if there are some papers or tools about this algorithm which I have not found？ 

Any suggestions will be appreciated!

**Comment by martindemello** [comment]
I don't think there are any papers, it's a reachability algorithm that was developed for pytype by considering types overlaid on the control flow graph. unfortunately, it's not as accurate as your example suggests; the following code also passes type checking:

```if __random__:
  x = 1
else:
  x = '1'

if __random__:
  y = 1
else:
  y = '1'

z = x + y
reveal_type(z)  # Union[int, str]
```

**Comment by iSika-PKU** [comment]
> I don't think there are any papers, it's a reachability algorithm that was developed for pytype by considering types overlaid on the control flow graph. unfortunately, it's not as accurate as your example suggests; the following code also passes type checking:
> 
> ```
>   x = 1
> else:
>   x = '1'
> 
> if __random__:
>   y = 1
> else:
>   y = '1'
> 
> z = x + y
> reveal_type(z)  # Union[int, str]
> ```

Thanks for the reply! I think that answers my confusion. 

However, I think the code will be rejected if we use the _--strict-parameter-checks_ flag, as I tested.
