### ISSUE TITLE
typing.final not supported yet

### ISSUE THREAD

**Issue by tschuett** [google/pytype#1256]
```bash
>  python --version
Python 3.9.7
> pytype --version
2022.01.13
> pytype myfile.py

line 25, in <module>: typing.final not supported yet [not-supported-yet]
```

Are there any plans to add support for typing.final?

**Comment by rchen152** [comment]
It looks like you're on a fairly old version of pytype (2022.01.13). We added support for final in 2022.01.31. I'd encourage you to update to the most recent version (2022.06.30) if possible, since we've made some bug fixes since initial support was added.

**Comment by tschuett** [comment]
Sorry for the noise.

```bash
> pytype --version
2022.06.30
> pytype ./check.py
Computing dependencies
Analyzing 1 sources with 0 local dependencies
ninja: Entering directory `.pytype'
[1/1] check check
Leaving directory '.pytype'
Success: no errors found
```
