### ISSUE TITLE
Pytype does not handle default parameters correctly

### ISSUE THREAD

**Issue by theahura** [google/pytype#1263]
hey folks, ran into this error:

```python
from typing import Callable


def bar(x: int, a: int, b: int) -> int:
  return 0


def foo(a: int) -> Callable[[int, int], int]:

  def _bar(x: int, b: int = 10):
    bar(x, a, b)

  return _bar


baz = foo(0)
baz(0)
```

This causes pytype to throw the following: 
```
File "/home/soot/code/soot/experimental/amol/pytype-callable-with-default/test3.py", line 3, in <module>: Function <callable> expects 2 arg(s), got 1 [w
rong-arg-count]   
         Expected: (_, _)                                                  
  Actually passed: (_)                                                     
                                                                           
For more details, see https://google.github.io/pytype/errors.html#wrong-arg-count
```

I think what's happening is that Pytype sees that the return of Foo is a callable with two ints, but doesn't know that one of the ints has a default passed in already. So even though `baz(0)` is totally valid, Pytype thinks it's the wrong signature. 

I *could* put `Optional` around the second parameter type, but if I understand right that would be a misuse of the `Optional` keyword (`Optional` is meant to be `Union[Type, None]`, which is very different from 'required but has a default')

**Comment by rchen152** [comment]
This seems to be WAI - a two-parameter callable shouldn't be allowed to be called with just one argument. Callables can't handle functions with a variable number of parameters, so you have to use something called a callback protocol:
```
from typing import Callable, Protocol

class Foo(Protocol):
  def __call__(self, x: int, b: int = 10) -> int: ...


def bar(x: int, a: int, b: int) -> int:
  return 0


def foo(a: int) -> Foo:

  def _bar(x: int, b: int = 10):
    bar(x, a, b)

  return _bar


baz = foo(0)
baz(0)
```
