### ISSUE TITLE
Using "jobs = auto" results in ninja error

### ISSUE THREAD

**Issue by AddisonG** [google/pytype#1267]
The autogenerated config file contains the following text:

```
# Run N jobs in parallel. When 'auto' is used, this will be equivalent to the
# number of CPUs on the host system.
```

But when I set `jobs = auto` in this file, and run pytype, I get the following error:

```
ninja: fatal: invalid -j parameter
```

**Comment by martindemello** [comment]
looks like ninja no longer supports `-j auto`, we should get rid of it.

**Comment by rchen152** [comment]
We're not passing `--j auto` to ninja; we're parsing `auto` here: https://github.com/google/pytype/blob/908c9dff94e4b12862a91f364cc0668d257c7c48/pytype/tools/analyze_project/parse_args.py#L22. My guess is that the parsing is accidentally skipped when when reading a config file.
