### ISSUE TITLE
Nested TypedDict class from another module does not get typed checked correctly

### ISSUE THREAD

**Issue by dcower** [google/pytype#1270]
Hi,

I've found that when a nested TypedDict class is used from another module, type checking doesn't seem to apply. But when it isn't nested (i.e., top-level TypedDict class), it works fine.

Here's a repro case:

File 1:
```python
# other_file.py
from typing import TypedDict, Protocol

class TopLevel(TypedDict):
  foo: str

class Outer:
  class Nested(TypedDict):
    bar: str
```

File 2:
```python
import other_file

top_level = other_file.TopLevel()  # This works correctly and gives an error.
nested = other_file.Outer.Nested()  # This does NOT work correctly and does NOT give an error.
```

I'm using PyType version 2022.08.03 with Python 3.9.13. Please let me know if you have any issues reproducing. Happy to take a stab at fixing it if someone can point me in the right direction too.

Thanks!
Dillon

**Comment by rchen152** [comment]
This seems to be an issue specific to TypedDict. If I change Nested to:
```
class Outer:
  class Nested:
    def __init__(self, bar: str):
      pass
```
then pytype is able to detect the missing parameter.
