### ISSUE TITLE
Add pre-commit support

### ISSUE THREAD

**Issue by ilCatania** [google/pytype#1300]
Add support for running pytype as a [pre-commit](https://pre-commit.com/) hook

**Comment by eggplants** [comment]
This feature has removed from repo in https://github.com/google/pytype/commit/41729eeb1f275a11192407e0555ac71fb6feb551. I don't know why.

**Comment by rchen152** [comment]
Apologies, that was a bad merge! I'll re-add .pre-commit-hooks.yaml and change our export rules so it doesn't get overwritten (i.e., deleted) again.
