### ISSUE TITLE
Why does PyType generate so many reports like "unsupported operand type(s) for |: 'TypeA' and 'TypeB' "

### ISSUE THREAD

**Issue by PVMPATCH** [google/pytype#1304]
Hi, I'm currently using PyType to learn about Python type annotation, 
and PyType has benefited me a lot. 
But I encountered some small problems during use, I would like to ask you if I am using it correctly

Why does PyType generate so many reports like `unsupported operand type(s) for |: 'TypeA' and 'TypeB' `?
For instance, for the following code snippet 
```
def fun(
        self,
        name: str,
        schema: dict[str, Any] | vol.Schema,
        func: str | Callable[..., Any],
        required_features: Iterable[int] | None = None,
    ) -> None:
```
PyType report that
```
"unsupported operand type(s) for |: 'Type[Iterable[int]]' and 'None: None'
No attribute '__or__' on 'Type[Iterable[int]]' or '__ror__' on 'None: None'"
```
Is it a false positives? 
As far as I know, the latest type annotation specification already supports that `val: A | B` is equivalent to `val: Union[A, B]`

Looking forward to your reply！

**Comment by rchen152** [comment]
What Python version are you using? I believe pytype requires Python 3.10+ to understanding the `|` syntax for `Union` (even if you use `from __future__ import annotations`).

**Comment by rchen152** [comment]
That's odd. I tried running pytype on:
```
from collections.abc import Callable, Iterable
from typing import Any

def fun(
    self,
    name: str,
    schema: dict[str, Any] | int,
    func: str | Callable[..., Any],
    required_features: Iterable[int] | None = None,
) -> None:
  pass
```
with the Python version set to 3.10, and I didn't get those errors. Could you post a self-contained code snippet that I could use to reproduce the errors?

**Comment by urnotlxr** [comment]
> That's odd. I tried running pytype on:
> 
> ```
> from collections.abc import Callable, Iterable
> from typing import Any
> 
> def fun(
>     self,
>     name: str,
>     schema: dict[str, Any] | int,
>     func: str | Callable[..., Any],
>     required_features: Iterable[int] | None = None,
> ) -> None:
>   pass
> ```
> 
> with the Python version set to 3.10, and I didn't get those errors. Could you post a self-contained code snippet that I could use to reproduce the errors?

I used pytype to scan the whole code from repository [core](https://github.com/home-assistant/core)
The specific location is at line 750 of this code
https://github.com/home-assistant/core/blob/dev/homeassistant/helpers/entity_platform.py

```
from collections.abc import Awaitable, Callable, Coroutine, Iterable
...
from typing import TYPE_CHECKING, Any, Protocol
...
@callback
    def async_register_entity_service(
        self,
        name: str,
        schema: dict[str, Any] | vol.Schema,
        func: str | Callable[..., Any],
        required_features: Iterable[int] | None = None,
    ) -> None:
```

**Comment by PVMPATCH** [comment]
> That's odd. I tried running pytype on:
> 
> ```
> from collections.abc import Callable, Iterable
> from typing import Any
> 
> def fun(
>     self,
>     name: str,
>     schema: dict[str, Any] | int,
>     func: str | Callable[..., Any],
>     required_features: Iterable[int] | None = None,
> ) -> None:
>   pass
> ```
> 
> with the Python version set to 3.10, and I didn't get those errors. Could you post a self-contained code snippet that I could use to reproduce the errors?

I used pytype to scan the whole code from repository [core](https://github.com/home-assistant/core)
The specific location is at line 750 of this code
https://github.com/home-assistant/core/blob/dev/homeassistant/helpers/entity_platform.py


```
from collections.abc import Awaitable, Callable, Coroutine, Iterable
...
from typing import TYPE_CHECKING, Any, Protocol
...
@callback
    def async_register_entity_service(
        self,
        name: str,
        schema: dict[str, Any] | vol.Schema,
        func: str | Callable[..., Any],
        required_features: Iterable[int] | None = None,
    ) -> None:
```

**Comment by rchen152** [comment]
Sorry for the slow response. I cloned the core repo and ran pytype on the specified file, but I'm still not seeing your errors. However, I see those errors and many similar ones if I add '-V3.9' to my invocation to use Python 3.9. Could you try adding '-V3.10' to explicitly request Python 3.10 and see if the errors are still present?

**Comment by rchen152** [comment]
I'm going to go ahead and close this issue. Please feel free to open a new one if you're still having trouble with this.
