### ISSUE TITLE
Cannot disable pytype with a multiple statement comment

### ISSUE THREAD

**Issue by wieczorek1990** [google/pytype#1311]
Pycharm and pylint support

`# noqa; pytype: disable=wrong-arg-types`

and pytype only supports:

`# pytype: disable=wrong-arg-types  # noqa`

**Comment by rchen152** [comment]
Up to now, we've intentionally required that pytype disables be put in their own comment, to reduce ambiguity. Does the `# noqa; pytype: disable=wrong-arg-types` form have some advantage over `# pytype: disable=wrong-arg-types # noqa`?

**Comment by wieczorek1990** [comment]
No double # used.

W dniu pt., 28.10.2022 o 22:11 Rebecca Chen ***@***.***>
napisał(a):

**Comment by rchen152** [comment]
Fewer `#` isn't inherently better, though? It sounds to me, then, like supporting this format isn't worth it for pytype. It would complicate our comment parsing logic quite a bit, for unclear gain. But let me know if I've missed something :)

**Comment by wieczorek1990** [comment]
There’s also two spaces less per line ;)

W dniu wt., 1.11.2022 o 01:41 Rebecca Chen ***@***.***>
napisał(a):
