### ISSUE TITLE
Custom project overlays support

### ISSUE THREAD

**Issue by supersergiy** [google/pytype#1319]
Custom project overlays are mentioned as a possibility in https://github.com/google/pytype/issues/234#issuecomment-485745748. Is there any plan to support this now?

Specifically, I have a decorator that patches a class. I can make it work with `mypy` plugins. 
Is there a way to make it work with `pytype`?
```python
from typing import Generic, TypeVar, Type
from typing_extensions import ParamSpec

P = ParamSpec("P")

T = TypeVar("T")
def decorator(cls: Type[T]) -> Type[T]: # annotation ignored by mypy
    def bar(self, *args, **kwargs):
        return self.foo()
    setattr(cls, 'bar', bar)
    return cls
    
@decorator
class A(Generic[P]):
    def foo(self, a: int) -> int:
        return 2*a
    
    def pop(self, *args: P.args, **kwargs: P.kwargs) -> str:
        return 'a'

reveal_type(A.bar)
```

**Comment by rchen152** [comment]
Unfortunately, the only way to write pytype overlays is still to add them to the `overlays/` subdirectory in the pytype source code. Since you specifically mentioned decorators, will the upcoming Data Class Transforms PEP (https://peps.python.org/pep-0681/) help with your case?

**Comment by supersergiy** [comment]
Thank you for the answer. 

Unfortunately our decorator has to add non-dunder methods, so PEP681 wouldn't directly help us as far as I understand.
