### ISSUE TITLE
pytype chokes on python 3 testtools

### ISSUE THREAD

**Issue by lantz** [google/pytype#133]
`pytype` seems to choke on testtools:

```
$ cat testtools-bug.py
#!/usr/bin/python3
import testtools
$ pytype -V3.5 testtools-bug.py
CRITICAL Cannot parse input files:
invalid syntax (_compat2x.py, line 16)
```

It seems that `pytype` isn't understanding that importing `compat2x` is wrapped in a `try:` block in `testtools/compat.py` to determine whether it should import the python 2 or 3 version:

```python
try:
    from testtools import _compat2x as _compat
except SyntaxError:
    from testtools import _compat3x as _compat
```

**Comment by Solumin** [comment]
Is there a reason to use a `try` block instead of `sys.version_info`? That's the standard (and pytype-supported) way to handle any version-specific features, including imports.

**Comment by kamahen** [comment]
There are lots of examples of code like this in the Python standard
library. e.g. in zipfile.py:

try:
    import zlib # We may need its compression method
    crc32 = zlib.crc32
except ImportError:
    zlib = None
    crc32 = binascii.crc32


I'm surprised that OP used SyntaxError rather than ImportError.

**Comment by Solumin** [comment]
They aren't looking for alternative implementations, but for version-specific libraries. try/except ImportError makes sense when there's multiple implementations, but it's definitely not the standard way when choosing version-specific libraries.

**Comment by kamahen** [comment]
`sys.version_info` isn't always enough. For example, the source might include a `from __future__ import annotations` which allows syntax that Python 3.7 doesn't support (but Python 3.8 will). Or Python 2.7 source with `from __future__ import print`.

**Comment by kamahen** [comment]
I suppose there's a limit to which idioms pytype can support -- pytype can't be a complete meta-interpreter for Python.

**Comment by lantz** [comment]
I might be OK with something like:
```python
import testtools  # pytype disable=syntax-error
```
You can already disable `import-error` which seems like a similar type of error.

**Comment by Solumin** [comment]
I'm not sure that will work, if it isn't a pytype error.

`# type: ignore` might work.

Another solution, I think, would be to run pytype on the file that's that
failing in python 2 mode. Something like: `pytype -V2.7 path/to/_compat2.py`
(Pardon for not remembering the exact file name, I'm on my phone.) This
would produce a pyi file and pytype would stop trying to analyze the file.
I can't guarantee it will work, I don't recall off the top of my head if
pytype will ignore the pyi file because it was generated in 2.7 mode.

**Comment by lantz** [comment]
@Solumin  If it is possible for `pytype` to catch `ImportError` and turn it into `import-error`, shouldn't it be possible to catch `SyntaxError` as well and turn it into `syntax-error`?

**Comment by Solumin** [comment]
Slight clarification: `import-error` is an _internal_ pytype error. The syntax error on `_compat2x.py` is raised by Importlab, the library used to run pytype. (Pytype needs to process all of a file's dependencies before analyzing the file. Importlab discovers the dependency graph of the project.) @martindemello might have some perspective on this.

**Comment by lantz** [comment]
Pre-running `pytype` on `_compat2x.py` didn't seem to help unfortunately:
```
$ cat testtools-bug.py
#!/usr/bin/python3
import testtools
$ pytype -V3.5 testtools-bug.py
CRITICAL Cannot parse input files:
invalid syntax (_compat2x.py, line 16)
$ pytype -V2.7 /usr/local/lib/python3.5/dist-packages/testtools/_compat2x.py 
Analyzing 1 sources with 0 dependencies
$ pytype -V3.5 testtools-bug.py
CRITICAL Cannot parse input files:
invalid syntax (_compat2x.py, line 16)
```
this also fails:
```
$ pytype -V2.7 /usr/local/lib/python3.5/dist-packages/testtools/compat.py 
Analyzing 1 sources with 3 dependencies
File "/usr/local/lib/python3.5/dist-packages/testtools/compat.py", line 56, in <module>: Can't find module 'builtins'. [import-error]
File "/usr/local/lib/python3.5/dist-packages/testtools/compat.py", line 59, in <module>: Name 'ascii' is not defined [name-error]
File "/usr/local/lib/python3.5/dist-packages/testtools/compat.py", line 202, in unicode_output_stream: Function <callable> expects 1 arg(s), got 2 [wrong-arg-count]
  Expected: (_)
  Actually passed: (_, _)
File "/usr/local/lib/python3.5/dist-packages/testtools/compat.py", line 215, in unicode_output_stream: Function <callable> expects 1 arg(s), got 2 [wrong-arg-count]
  Expected: (_)
  Actually passed: (_, _)

For more details, see https://github.com/google/pytype/blob/master/docs/errors.md.
```

**Comment by rchen152** [comment]
Hmm, so the problem, as far as I can tell, is that importlab gives up completely when it finds a file with a syntax error, so pytype can't generate a dependency graph, which is a prerequisite for its analysis.

The two possible solutions I can think of are to (1) change importlab so that it can still generate the rest of the graph even if one file is bad (maybe mark that import as unresolved?), or (2) have pytype analyze a file with import errors disabled when it can't get dependency information. (1) sounds much better to me, so I'll start by filing an issue with importlab.

**Comment by Solumin** [comment]
https://github.com/google/importlab/issues/16
Guess we forgot to update this issue? Though we may need to release a new version of importlab and update pytype first?

**Comment by rchen152** [comment]
Oh, nice! Yeah, sounds like an importlab release is in order.

**Comment by martindemello** [comment]
pushed importlab-0.3.0 to pypi
