### ISSUE TITLE
pytype chokes on Python 3 yaml (upstream typeshed issue?)

### ISSUE THREAD

**Issue by lantz** [google/pytype#134]
`pytype` seems to fail on the `yaml` library if it's used in Python 3 code:
```
$ cat yamltest.py
import yaml
$ pytype -V3.5 yamltest.py
Analyzing 1 sources with 0 dependencies
File ".../pytype-bugs/yamltest.py", line 1, in <module>: Couldn't import pyi for 'yaml' [pyi-error]
    File: "/usr/local/lib/python3.5/dist-packages/pytype/typeshed/third_party/2and3/yaml/__init__.pyi", line 39
      b'class YAMLObject:'
        ^
  ParseError: Illegal value for alias '__metaclass__'. Value must be an attribute or method on the same class.

For more details, see https://github.com/google/pytype/blob/master/docs/errors.md#pyi-error.
```

The root problem seems to be with `typeshed`: python/typeshed#2399

**Comment by lantz** [comment]
Until it is fixed upstream this seems to work:
```python
import yaml  # pytype: ignore=pyi-error
```

**Comment by rchen152** [comment]
The __metaclass__ issue has been fixed, but pytype's still unhappy with the nested `classobj` definition in yaml.constructor. I'll submit a PR to try to change that to `classobj: type`; if that doesn't work, we'll have to update our parser to handle nested classes.

**Comment by rchen152** [comment]
Fixed and released!
