### ISSUE TITLE
Can we allow inferring Optional?

### ISSUE THREAD

**Issue by BenQuigley** [google/pytype#1343]
This project is amazingly useful and well executed!

mypy has a feature called "implicit optional" that I'd like to either learn how to make work in pytype, or add it. For example -

```python
foo.py:
def foo(bar: str = None):
    return f"Hello {bar}!" if bar else "Hello"
```
So technically `Optional[str]` is the correct annotation, but it gets omitted in this kwargs context quite a lot. I think this is arguably pythonic and acceptable, since certain types like lists, dicts are [not allowable](https://docs.python-guide.org/writing/gotchas/) as default arguments, it's common to see 

```python
def send_emails(
    to_email: str,
    cc_emails: list[str] = None,
    ...
):
    cc_emails = cc_emails or []
```

Anyway, all of this actually flies in mypy, unless you configure `--no-implicit-optional`; but pytype complains:
```shell
$ pytype foo.py
...
File "/Users/benquigley/foo.py", line 1, in <module>: Type annotation for bar does not match type of assignment [annotation-type-mismatch]                                                                
  Annotation: str (Did you mean 'typing.Optional[str]'?)                                                        
  Assignment: None                                                                                              
...
```
In pytype, a configuration option would be nice so that we can use this pattern without disabling `annotation-type-mismatch` itself, and it might be worth considering if this should even be the default behavior like in mypy.

**Comment by rchen152** [comment]
Implicit optional used to be recommended by PEP 484 and has been essentially deprecated for years:

> A past version of this PEP allowed type checkers to assume an optional type when the default value is None, as in this code:
> 
> def handle_employee(e: Employee = None): ...
>
> This would have been treated as equivalent to:
> 
> def handle_employee(e: Optional[Employee] = None) -> None: ...
>
> This is no longer the recommended behavior. Type checkers should move towards requiring the optional type to be made explicit.

(https://peps.python.org/pep-0484/#union-types)

(I'm a little surprised that `--no-implicit-optional` isn't the default yet in mypy!)

**Comment by BenQuigley** [comment]
Okay, thanks for responding!
