### ISSUE TITLE
How to tell pytype a function is guaranteed to return a value of expected type?

### ISSUE THREAD

**Issue by pepoluan** [google/pytype#1354]
I got the following error:

```
FAILED: /home/runner/work/aiosmtpd/aiosmtpd/.pytype/pyi/autoprogramm.pyi 
/opt/hostedtoolcache/Python/3.8.15/x64/bin/python -m pytype.single --imports_info /home/runner/work/aiosmtpd/aiosmtpd/.pytype/imports/autoprogramm.imports --module-name autoprogramm --platform linux -V 3.8 -o /home/runner/work/aiosmtpd/aiosmtpd/.pytype/pyi/autoprogramm.pyi --analyze-annotated --nofail --quick /home/runner/work/aiosmtpd/aiosmtpd/aiosmtpd/docs/_exts/autoprogramm.py
File "/home/runner/work/aiosmtpd/aiosmtpd/aiosmtpd/docs/_exts/autoprogramm.py", line 57, in get_subparser_action: bad return type [bad-return-type]
           Expected: argparse._SubParsersAction
  Actually returned: None
```

The affected code, [as seen here](https://github.com/aio-libs/aiosmtpd/blob/770ed2adcce8b5999242680c1ec4c3d5910f38ef/aiosmtpd/docs/_exts/autoprogramm.py#L49-L57), is actually:

```python
    for a in parser._actions:
        if isinstance(a, argparse._SubParsersAction):
            return a
```

So there is no way `a` is `None` as inferred by pytype, as the `return a` will be executed _if and only if_ `a` is actually an instance of `argparse._SubParsersAction`.

### EDIT 1:

Hmm... I think the issue was not that line, but because in the end _if_ the nothing suitable is found in `parser._actions` then the function returns `None` **implicitly** ?

I think that might be the right explanation, but the error message is kind of misleading...

If that is actually the case, how do I inform pytype that this function is 'guaranteed' to return something and not fall through to do an implicit `return None` ?

### EDIT 2:

This is the GitHub Action where the error happened: https://github.com/aio-libs/aiosmtpd/actions/runs/3909388062/jobs/6680408709

**Comment by pepoluan** [comment]
Hmm... I think the issue was not that line, but because in the end _if_ the nothing suitable is found in `parser._actions` then the function returns `None` **implicitly** ?

I think that might be the right explanation, but the error message is kind of misleading...

**Comment by rchen152** [comment]
Hmm, hard to tell from the snippet whether pytype is complaining about the type of `a` or that the for loop could terminate without returning anything. You can try two things:

1. Raise an exception after the loop:
    ```
      for a in parser._actions:
        if isinstance(a, argparse._SubParsersAction):
            return a
      raise AssertionError('This should never happen')
   ```
   If the problem is the implicit return None, that should fix it.
1. If the error persists, can you add `reveal_type(a)` right before the return statement to see what pytype thinks the type of `a` is?

**Comment by pepoluan** [comment]
I tried using `return cast(..., a)` and it still complained.

So for the time being I wrapped the function with a pair of `disable`...`enable`

**Comment by pepoluan** [comment]
Accidentally closed, so reopening. Dang train ride 😄

**Comment by rchen152** [comment]
If explicitly casting `a` failed, then I'm pretty sure pytype is complaining about the implicit `return None` that occurs when `parser._actions` is empty. That's working as intended, and the way to resolve the error is to raise an exception after the for loop as shown above.

**Comment by pepoluan** [comment]
> the way to resolve the error is to raise an exception after the for loop as shown above.

Ahh this makes sense. A defensive check. Okay then, thanks for taking a look at this!
