### ISSUE TITLE
@abstractmethod is not recognized when re-exported

### ISSUE THREAD

**Issue by eltoder** [google/pytype#1365]
To reproduce:
```
$ cat proj/my_abc.py
from abc import ABC, abstractmethod
$ cat proj/use_abc.py
import abc
from proj import my_abc

class C1(abc.ABC):
    @abc.abstractmethod
    def method(self):
        pass

class C2(abc.ABC):
    @my_abc.abstractmethod
    def method(self):
        pass

class C3(my_abc.ABC):
    @abc.abstractmethod
    def method(self):
        pass

C1()
C2()
C3()
```
Running pytype gives:
```
$ pytype proj/use_abc.py
...
File "/home/elt/code/pytype-test/proj/use_abc.py", line 19, in <module>: Can't instantiate C1 with abstract methods method [not-instantiable]
File "/home/elt/code/pytype-test/proj/use_abc.py", line 21, in <module>: Can't instantiate C3 with abstract methods method [not-instantiable]
...
```
Pytype correctly flags C1 and C3, but misses C2. That is, is supports using abc.ABC via re-exported name, but doing the same for abc.abstractmethod does not work.

**Comment by rchen152** [comment]
I don't think it's feasible for us to support this, given the complexity - currently, pytype re-exports imported functions by copying the definition (not aliasing), so we'd have to completely rewrite that to preserve the information that my_abc.abstractmethod is abc.abstractmethod. Then we'd have to figure out how to trigger the abc overlay code when that aliased method is imported.

Please use `abc.abstractmethod` directly instead.

**Comment by eltoder** [comment]
@rchen152 you could add an attribute that tracks the source of the copy

**Comment by martindemello** [comment]
patches welcome, but you're underestimating the difficulty of doing this with pytytpe's current architecture. as @rchen152 noted, we have an overlay that special-cases `abc.abstractmethod` specifically and does whatever magic is needed, it does not work through the regular typing mechanisms.

**Comment by eltoder** [comment]
@rchen152 I read the code and now I understand your comment. It seems that to support this, you would need to

1. Write re-exported functions as aliases instead of as signatures in the pyi files.
2. Change the Loader to use overlay_dict when importing.

Does this sound about right? Step 2 sounds not very hard, but step 1 can have many side-effects. This sounds like a lot of work to support my use case, but it may also improve handling of overlays in imported modules in general.
