### ISSUE TITLE
pytype not using system ninja, even if it's there

### ISSUE THREAD

**Issue by PythonCHB** [google/pytype#1376]
pytype using ninja (honestly, I haven't looked into how or why, but I'm sure you all know :-) (and I may be getting some of this wrong, but ...)

However, ninja is not a python package, so it has to be installed somehow.

For Python / pip users, a "ninja" package is on PyPi that is basically a wrapper around ninja so that it can be installed by pip. Nifty.

However, at least as of commit: 1a6d0b3481c7 -- pytype seems to always try to call ninja via the python wrapper, which fails if the python wrapper isn't there, even though the ninja executable is there.

This is an issue for the conda-forge pytype package, which has been broken for some time (still trying to figure out when it last worked). conda-forge has a ninja package that installs the ninja executable, which works fine itself, but not with the current pytype package.

I imagine it would be an issue for any other system that can install ninja itself -- e.g. Linux distros.

This is discussed in the conda-forge "feedstock" repo here:

https://github.com/conda-forge/pytype-feedstock/issues/97

**Comment by eli-schwartz** [comment]
I would suggest checking for both `shutil.which('ninja')` and `from ninja import ninja` to see which one is available.

**Comment by PythonCHB** [comment]
> `from ninja import ninja`

Make sure to wrap that in a:
```
try:
    from ninja import ninja
except ImportError:
    ...
```
