### ISSUE TITLE
TypeVars become nothing

### ISSUE THREAD

**Issue by eltoder** [google/pytype#1383]
Consider the following example:
```python
from typing import Iterable, TypeVar

T = TypeVar('T')

def last(xs: Iterable[T], default: T) -> T:
    res = default
    for x in xs:
        reveal_type(x)  # revealed as nothing
        res = x
    reveal_type(res)  # revealed as Union[Any, nothing]
    return res
```
Somehow iterating over an `Iterable[T]` produces elements of `nothing` instead of `T`. The behavior is even more strange for `res` which got a union with `Any`. If I remove the type var and define
```python
T = int
```
both types are revealed as `int` as expected.

**Comment by rchen152** [comment]
I wouldn't focus too much on the `reveal_type` output here; what is displayed for `TypeVar`s is always a little unusual when there isn't a concrete type substituted in. Are you seeing any weird behavior resulting from this?

**Comment by eltoder** [comment]
Oh, I see. This is just how type variables work in pytype. For example, 
```python
T = TypeVar("T")

def noop(x: T) -> T:
    print(x.upper())
    return "abc"
```
does not generate any errors. But if I add an incompatible call like `noop(1)`, I get the errors. Also, `reveal_type` inside noop is printed once for every unique type of the argument. So this is handled like C++ templates rather than like generic functions in Java.
