### ISSUE TITLE
Parameter of type `Optional[int]` is erroneously inferred to have type `Union[Any, int]`

### ISSUE THREAD

**Issue by manueljacob** [google/pytype#1384]
```python
from typing import Optional

class A:
    def __init__(self, x: Optional[int]):
        assert_type(x, Optional[int])

def test(a: A):
    pass
```

I would expect that it succeeds, but it gives the following error:

```
File "/home/manu/vcs/pytype/reproducer.py", line 5, in __init__: Union[Any, int] [assert-type]
  Expected: Optional[int]
    Actual: Union[Any, int]
```

I tried several pytype versions, the earliest was 5916b3a40ff654e3635e6fa8060325947968534f (that introduced `assert_type()` in the current form) and the lastest was e6984f1bf09fc5d61efc45db68f84f37620e7c02 (current main).

#### `reveal_type()` instead of `assert_type()` prints two different types

```
File "/home/manu/vcs/pytype/reproducer.py", line 5, in __init__: Optional[int] [reveal-type]
File "/home/manu/vcs/pytype/reproducer.py", line 5, in __init__: Union[Any, int] [reveal-type]
```

Similarly, the handler for `assert_type()` is called twice, but only the second fails.

#### Using a different method than `__init__()` works

I tried `test`, `__new__` and `__call__` instead of `__init__`. Neither of them triggers the error.

#### It seems as if a variable of `A` must exist to trigger the error

Without `def test(a: A)`, the error is not triggered. But `a: A = A(1)` instead of the function definition also triggers the error.

#### Looking at the pytype code

I disabled the typegraph C extension (`pytype.typegraph.cfg`) to simplify debugging. It still has the same error.

The binding that results in the `Any` type is added in [pytype/vm.py:967](https://github.com/google/pytype/blob/e6984f1bf09fc5d61efc45db68f84f37620e7c02/pytype/vm.py#L967).

### Open questions

- Is it expected that the `reveal_type()` / `assert_type()` handlers can be called twice?

**Comment by msuozzo** [comment]
This should now be addressed by the new flag `--strict-none-binding`.

**Comment by rchen152** [comment]
Yep, I just tested it, and the code in the first comment passes pytype with `--strict-none-binding` enabled :)

**Comment by manueljacob** [comment]
Nice, thank for this and all the great work!
