### ISSUE TITLE
pytype should allow None as a constrained type in TypeVar

### ISSUE THREAD

**Issue by shoyer** [google/pytype#1389]
`FloatOrNone = TypeVar("FloatOrNone", float, None)` [works in mypy](https://github.com/python/mypy/issues/8851) but with pytype I see the following error:
```
wrong arguments [invalid-typevar]
         Expected: (name, _, _2: Union[str, type], ...)
  Actually passed: (name, _, _2: None)
```

Instead, I need to write `FloatOrNone = TypeVar("FloatOrNone", float, types.NoneType)`, which is a little more cumbersome.

**Comment by rchen152** [comment]
Huh, I'm surprised this has never come up before.
