### ISSUE TITLE
readonly typeddict

### ISSUE THREAD

**Issue by theahura** [google/pytype#1400]
Is there a way to make a TypedDict readonly?

For example:
```python
from typing import Mapping, Text, TypedDict


class Foo(TypedDict, Mapping, total=False):
  bar: Text


x: Foo = {'bar': 'baz'}

print(x['bar'])
x['bar'] = 'should not be allowed'
```
^this currently fails with
```
File "/home/soot/code/soot/experimental/amol/pytype-readonly-typedict/test.py", line 4, in <module>: Invalid base class: Mapping [base-class-error]
  TypedDict Foo cannot inherit from a non-TypedDict class.

For more details, see https://google.github.io/pytype/errors.html#base-class-error
```

**Comment by rchen152** [comment]
It looks like TypedMapping in Python 3.12 will be exactly what you want: https://peps.python.org/pep-0705/. The Motivation section (https://peps.python.org/pep-0705/#motivation) shows how you can use a protocol to achieve a similar effect before TypedMapping is available.
