### ISSUE TITLE
pytype cannot tell between enum and enum value

### ISSUE THREAD

**Issue by theahura** [google/pytype#1405]
Hey folks, ran into this error today:

```py
from enum import Enum


class Foo(Enum):
  A = 1
  B = 2


def foo_ingest(foo: Foo):
  return foo


foo_ingest(Foo.A.value)
```
pytype compiles without error, but this is obviously wrong because `foo_ingest` expects an enum value and is getting an int

**Comment by rchen152** [comment]
I see the expected error when I run pytype over this code. Are you using `--use-enum-overlay`? (We plan to eventually switch that flag to on by default, but for now, you still have to enable it manually. You can set it to True in a configuration file if that's easier.)

**Comment by theahura** [comment]
ah that did it. Thank you!
