### ISSUE TITLE
namedtuple defaults in stubs

### ISSUE THREAD

**Issue by hmc-cs-mdrissi** [google/pytype#1410]
```python
class Foo(NamedTuple):
  x: bool = False
```

produces an error message similar to,

```
  File "/Users/pa-loaner/Snapchat/Dev/.venvs/typeshed/lib/python3.9/site-packages/pytype/ast/visitor.py", line 55, in _call_visitor
    return visitor(node)
  File "/Users/pa-loaner/Snapchat/Dev/.venvs/typeshed/lib/python3.9/site-packages/pytype/pyi/parser.py", line 477, in visit_AnnAssign
    raise ParseError(msg)
pytype.pyi.types.ParseError:   File: "stubs/tensorflow/tensorflow/io/__init__.pyi", line 56
    default_value: _TensorCompatible | None = None
   ^
ParseError: Default value for default_value: typing.Union can only be '...', got None
```

I think it then leads to various noise errors elsewhere due to parse error. Originally hit [here](https://github.com/python/typeshed/pull/10052#discussion_r1167784300) by running pytype_test.py stubs/tensorflow/io but you can run pytype_test.py stubs/tensorflow/toy and add a file in toy with just example at top to trigger this error. The error looks to be specific to stub files and normal .py files are fine.

edit: Looking a bit more at code/stacktrace I'm unsure this is unique to namedtuples although probably most common to see default with them in class body.

**Comment by hmc-cs-mdrissi** [comment]
I'm able to take a stab at this, but unsure which values you want to allow. typeshed exact [rule](https://github.com/PyCQA/flake8-pyi/blob/7e921e11b44a80ba3c410683e8030759e6df679b/pyi.py#L737) is a bit complex and mostly motivated by what can stubtest/static ast checking with flake8 handle and isn't too "complex". I'm unsure what mypy/pyright's valid stub default values are. Some of which is very heuristicy (long tuples/strings being blocked). 

The easiest rule is just allow everything as valid stub defaults. Alternatively allowlist only some types/constants?

At the least default value should not be raising a ParseError that can't be type ignored/affects other files.

**Comment by rchen152** [comment]
Looks like "literals and constants" are supposed to be allowed as default values: https://typing.readthedocs.io/en/latest/source/stubs.html#functions-and-methods. I could've sworn that doc did not used to say that, but I can implement it.
