### ISSUE TITLE
Pytype won't accept a single file without `.py` extension as input

### ISSUE THREAD

**Issue by redat00** [google/pytype#1415]
Hello ! 

I'm working on a small script. This script, as it is an executable, does not have a `.py` extension, and is not in a directory.  It's the file called `s3`.

```bash
.
├── COPYING
├── poetry.lock
├── pyproject.toml
├── README.md
└── s3
```

I wan't to run `pytype` on it, but I'm not able to since I have this error message : 
```
# poetry run pytype s3
usage: pytype [options] input [input ...]
pytype: error: Need an input.
```

However, if I just rename the file from `s3` to `s3.py` I don't have this problem anymore. 
Is it something that should occur, or is there something I'm missing ? 

Thanks in advance for any help !

**Comment by rchen152** [comment]
Thank you @trevor-james-nangosha for fixing this! Next week's release will contain the fix.
