### ISSUE TITLE
Support for typeshed?

### ISSUE THREAD

**Issue by theahura** [google/pytype#1426]
Does pytype support type inference using typeshed types? I notice that pytype can often be very slow for larger repositories, and I'm wondering if I can speed it up by using pre-built typing packages for third party libraries

**Comment by rchen152** [comment]
Pytype has supported typeshed from the start. It doesn't support standalone stub packages (https://github.com/google/pytype/issues/151), but that shouldn't cause any slowness. With large repositories, a lot of time goes into loading stubs for the repository itself into memory. Internally, pytype uses pickle to get around this, but I haven't gotten around to integrating pickle support into the opensource infrastructure yet.
