### ISSUE TITLE
False-positive `name-error` in match statement

### ISSUE THREAD

**Issue by sizmailov** [google/pytype#1435]
Source `foo.py`:
```python
import bar

match 0:
    case 0:
        x: int = bar.f(0)
```
Command:
```shell
pytype --disable import-error foo.py 
```
Error:
```
File "foo.py", line 5, in <module>: Name '__annotations__' is not defined [name-error]
```

System info:
```
$ python --version
Python 3.10.6
$ pytype --version
2023.05.24
```

**Comment by martindemello** [comment]
the problem is the match statement compiles to this:

```
  1           0 LOAD_CONST               0 (0)

  2           2 LOAD_CONST               0 (0)
              4 COMPARE_OP               2 (==)
              6 POP_JUMP_IF_FALSE       12 (to 24)

  3           8 LOAD_CONST               1 (1)
             10 STORE_NAME               0 (x)
             12 LOAD_NAME                1 (int)
             14 LOAD_NAME                2 (__annotations__)
             16 LOAD_CONST               2 ('x')
             18 STORE_SUBSCR
             20 LOAD_CONST               3 (None)
             22 RETURN_VALUE

  2     >>   24 LOAD_CONST               3 (None)
             26 RETURN_VALUE
```

where it calls `__annotations__[x] = int` without having generated a `SETUP_ANNOTATIONS` first. for some reason this does not raise an error at runtime, but pytype is technically correct that the bytecode contains a name error. i suspect the interpreter special-cases `__annotations__` in `LOAD_NAME` and we will have to do the same.

**Comment by martindemello** [comment]
since this is being fixed in cpython, and since there will genuinely be a runtime error when a module with this code is imported, i don't think we should try to work around this from pytype's side.

**Comment by JelleZijlstra** [comment]
Just a note that we'll only fix this in 3.11+ in CPython, as 3.10 is in security fix-only mode.

**Comment by martindemello** [comment]
ah, thanks for the note. for anyone running into the issue, the workaround is simply to add a top-level annotated assignment, to force the compiler to emit a `SETUP_ANNOTATIONS`. e.g. this works:

```
import bar

match 0:
    case 0:
        x: int = bar.f(0)

fix_annotations: bool = True
```

**Comment by martindemello** [comment]
this has been fixed in cpython at head and there's nothing more we can do for 3.10- so closing
