### ISSUE TITLE
libcst dependency conflict

### ISSUE THREAD

**Issue by tanducmai** [google/pytype#1450]
The latest release of pytype (2023.6.16) requires libcst==0.4.9, but the latest release of libcst is (1.0.1) - which is incompatible.
The previous release of pytype did not result in the mentioned conflict with libcst 1.0.1

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pytype 2023.6.16 requires libcst==0.4.9, but you have libcst 1.0.1 which is incompatible.
```

**Comment by martindemello** [comment]
not sure why this issue is showing up just now, but we are in the process of upgrading our libcst dependency to 1.01 anyway, so it should be fixed soon.

**Comment by martindemello** [comment]
fixed via https://github.com/google/pytype/commit/807d4bf1bd4955761ab9dab9b267435871f8952a
