### ISSUE TITLE
no_type_check_decorator doesn't work

### ISSUE THREAD

**Issue by jgarvin** [google/pytype#1452]
The [`no_type_check_decorator`](https://docs.python.org/3/library/typing.html#typing.no_type_check_decorator) is supposed to let you give the effect of `no_type_check` to other decorators. pytype doesn't appear to understand it:

```python
from typing import no_type_check_decorator

@no_type_check_decorator
def test(cls):
    return cls

@test
class Foo:
    x: 5
```

Gives:

```
File "/tmp/type_test3.py", line 15, in Foo: Invalid type annotation '5' for x [invalid-annotation]
  Not a type
```

[mypy is also currently lacking support](https://github.com/python/mypy/issues/6583), they discuss it probably needing special case support directly in the checker.

**Comment by martindemello** [comment]
we would need special-case support directly in the checker too, since this is more of a type-checker directive than something that works with the existing type system.

**Comment by AlexWaygood** [comment]
Since no type checker added support for this decorator after 8 years of it being in the `typing` module, it has now been deprecated: https://github.com/python/cpython/issues/106309.

**Comment by rchen152** [comment]
Thanks for the update! I'll close this issue then.
