### ISSUE TITLE
pytype: error: unrecognized arguments: .

### ISSUE THREAD

**Issue by joortcom** [google/pytype#1483]
I have some python file in my current working dir, and I always get this error:

```
$ pytype .
...
pytype: error: unrecognized arguments: .
```

even if I pass a single file:
```
$ pytype single.py
Computing dependencies
INFO NumExpr defaulting to 8 threads.
pytype: error: unrecognized arguments: single.py

$ pytype --version
2023.07.28
```

I'm wondering why it's not working at all?

**Comment by rchen152** [comment]
Do you have any .toml or .cfg files in the directory that you're running pytype from? Both `pytype .` and `pytype single.py` work for me in a test directory that contains just a single Python file named `single.py`, so I'm wondering if maybe pytype is doing something strange while trying to read a configuration file.

**Comment by joortcom** [comment]
No, I don't:

```
$ ls *.toml *.cfg
ls: cannot access '*.toml': No such file or directory
ls: cannot access '*.cfg': No such file or directory

$ pytype single.py
Computing dependencies
INFO NumExpr defaulting to 8 threads.
pytype: error: unrecognized arguments: single.py
```

So what else should I check?

BTW, if pytype read some .toml or .cfg files, can it print out something explicitly, so at least the users know where to check.

**Comment by joortcom** [comment]
BUT, I think I know where the error coming from:

my own script also parse the command line args:

```
import argparse                                                                                                                                                                                                     
...

prog_args = _parser.parse_args() 
```

looks like `pytype` will *execute* that piece of code (and of course, my script won't recognize the input).

I think `pytype` should consume its own command-line args, and never pass them to the user scripts.

**Comment by joortcom** [comment]
pytype should follow the Linux convention:

```
$ pytype <pytype args> input.py --  <input.py args>
```

only pass those `<input.py args>` to input.py (but not any of the `<pytype args> input.py`.

**Comment by joortcom** [comment]
@rchen152 I'd rather keep this as a separate issue: 

#1436: not to execute the code being analyzed.
#1483: (since #1436 is not fixed), only passing `--  <input.py args>` to the code being analyzed.

**Comment by rchen152** [comment]
We're not doing anything that would intentionally pass pytype's args to your script. If that's happening, it's a side effect of https://github.com/google/pytype/issues/1436.

**Comment by joortcom** [comment]
What I mean is pytype should *consume* it's own args: i.e reset `sys.argv` (remove pytype's own recognized arg), then #1483 will work (regardless of #1436).

**Comment by rchen152** [comment]
I've honestly never seen a program that removes the args it reads from sys.argv. I tried googling a bit to see if that's standard, but the closest I found was https://github.com/ipython/ipython/issues/9133, which seems to suggest that the opposite is true, and it would be quite unusual to remove args after reading them.

**Comment by joortcom** [comment]
Program like pytype is an unusual type of program: it works like a compiler, and in the same time also execute some part of the code.

I think #1436 is debatable: since execute argparse at global level actually helps pytype to reduce the search spaces (with certain flags fixed). Of course, this behavior need to be doc-ed clearly, so no surprises to the users.

**Comment by joortcom** [comment]
The very existence of this Linux convention is for such reason:

$ pytype <pytype args> input.py --  <input.py args>

only pass those <input.py args> to input.py (but not any of the <pytype args> input.py.

**Comment by martindemello** [comment]
#1436 is not debatable - it's an unfortunate side effect of how python's `importlib` works (and, at a deeper level, of the dynamic nature of python's import mechanisms). pytype itself does not intentionally execute any part of the code, since it is meant to be a purely static analysis tool.

**Comment by joortcom** [comment]
> #1436 is not debatable - it's an unfortunate side effect of how python's `importlib` works (and, at a deeper level, of the dynamic nature of python's import mechanisms). pytype itself does not intentionally execute any part of the code, since it is meant to be a purely static analysis tool.

I know all you have said, I am saying *debatable* is for the exactly same reason: importlib is hard to fix.

If it's hard to fix, why not take advantage of it (it helps pytype to reduce the search spaces (with certain flags fixed)), and just doc this behavior clearly so the users know.

**Comment by martindemello** [comment]
it's a philosophical issue, perhaps, but i believe pytype should try really hard to analyse code purely as a chunk of text, and not rely on any effects from executing it in a python interpreter. 

as an aside, i believe both this issue and #1436 can be worked around by using `if __name__ = '__main__'`, which is arguably a best-practice anyway., since the bug is triggered by side effects when a parent module is implicitly imported.
