### ISSUE TITLE
couln't install it on windows

### ISSUE THREAD

**Issue by ravi005e** [google/pytype#1509]
building 'pytype.typegraph.cfg' extension
      creating build\temp.win-amd64-cpython-311
      creating build\temp.win-amd64-cpython-311\Release
      creating build\temp.win-amd64-cpython-311\Release\pytype
      creating build\temp.win-amd64-cpython-311\Release\pytype\typegraph
      "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Us
ers\private\AppData\Local\Temp\pip-build-env-veranuoe\overlay\Lib\site-packages\pybind11\include -IC:\Users\private\AppData\Local\Programs\Python\Python311\include -IC:\
Users\private\AppData\Local\Programs\Python\Python311\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\ATLMFC\incl
ude" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\inclu
de\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared" "-IC:\Program File
s (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt" /EHsc /Tppytype/typegraph/cfg.cc /Fobuild\temp.win-amd64-cpython-311\Release\pytype/typegraph/cfg.obj /EHsc /bigobj /std:c++14
      cfg.cc
      pytype/typegraph/cfg.cc(185): warning C4244: 'initializing': conversion from 'Py_ssize_t' to 'int', possible loss of data
      pytype/typegraph/cfg.cc(360): warning C4244: 'initializing': conversion from 'Py_ssize_t' to 'int', possible loss of data
      pytype/typegraph/cfg.cc(505): error C2065: 'tp_name': undeclared identifier
      pytype/typegraph/cfg.cc(505): error C2059: syntax error: ':'
      pytype/typegraph/cfg.cc(550): error C2143: syntax error: missing ';' before '}'
      pytype/typegraph/cfg.cc(550): error C2059: syntax error: '}'
      pytype/typegraph/cfg.cc(589): warning C4267: 'argument': conversion from 'size_t' to 'long', possible loss of data
      pytype/typegraph/cfg.cc(711): warning C4244: 'initializing': conversion from 'Py_ssize_t' to 'int', possible loss of data
      pytype/typegraph/cfg.cc(738): warning C4244: 'initializing': conversion from 'Py_ssize_t' to 'int', possible loss of data
      pytype/typegraph/cfg.cc(770): error C2065: 'tp_name': undeclared identifier
      pytype/typegraph/cfg.cc(770): error C2059: syntax error: ':'
      pytype/typegraph/cfg.cc(805): error C2143: syntax error: missing ';' before '}'
      pytype/typegraph/cfg.cc(805): error C2059: syntax error: '}'
      pytype/typegraph/cfg.cc(825): error C2065: 'name': undeclared identifier
      pytype/typegraph/cfg.cc(825): error C2059: syntax error: ':'
      pytype/typegraph/cfg.cc(829): error C2143: syntax error: missing ';' before '}'
      pytype/typegraph/cfg.cc(829): error C2059: syntax error: '}'
      pytype/typegraph/cfg.cc(897): warning C4267: 'argument': conversion from 'size_t' to 'long', possible loss of data
      pytype/typegraph/cfg.cc(1006): error C2065: 'tp_name': undeclared identifier
      pytype/typegraph/cfg.cc(1006): error C2059: syntax error: ':'
      pytype/typegraph/cfg.cc(1041): error C2143: syntax error: missing ';' before '}'
      pytype/typegraph/cfg.cc(1041): error C2059: syntax error: '}'
      pytype/typegraph/cfg.cc(1080): warning C4267: 'argument': conversion from 'size_t' to 'long', possible loss of data
      pytype/typegraph/cfg.cc(1408): error C2065: 'tp_name': undeclared identifier
      pytype/typegraph/cfg.cc(1408): error C2059: syntax error: ':'
      pytype/typegraph/cfg.cc(1443): error C2143: syntax error: missing ';' before '}'
      pytype/typegraph/cfg.cc(1443): error C2059: syntax error: '}'
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Professional\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pytype
Failed to build pytype
ERROR: Could not build wheels for pytype, which is required to install pyproject.toml-based projects

**Comment by rchen152** [comment]
Yes, unfortunately windows is currently unsupported (https://github.com/google/pytype/issues/1154), unless you're using WSL.

**Comment by ravi005e** [comment]
why not? people like me want to use itSent from my iPhoneOn Sep 27, 2023, at 10:37 AM, Rebecca Chen ***@***.***> wrote:﻿
Closed #1509 as not planned.

**Comment by kamahen** [comment]
I'm sure the authors of pytype would be very happy to receive a PR that adds support for Windows. :)

**Comment by rchen152** [comment]
Yes, it's not that we don't want to support Windows but rather that we don't have the resources to do so right now.
(On a side note, I think the GitHub interface makes this a little confusing by saying that I "closed this as not planned," when my intent was to close as a duplicate of our other Windows issue.)

**Comment by ravi005e** [comment]
okay thanks Sent from my iPhoneOn Sep 27, 2023, at 12:04 PM, Rebecca Chen ***@***.***> wrote:﻿
Yes, it's not that we don't want to support Windows but rather that we don't have the resources to do so right now.
(On a side note, I think the GitHub interface makes this a little confusing by saying that I "closed this as not planned," when my intent was to close as a duplicate of our other Windows issue.)
