### ISSUE TITLE
[bug] Import error: mach-o file, but is an incompatible architecture

### ISSUE THREAD

**Issue by TiansuYu** [google/pytype#1515]
```python
ImportError: dlopen(/xxx/project/.venv/lib/python3.8/site-
packages/pytype/typegraph/cfg.cpython-38-darwin.so, 0x0002): tried: '/xxx/project/.venv/lib/python3.8/site-packages/pytype/typegraph/cfg.cpython-38-darwin.so' (mach-o file, but is an 
incompatible architecture (have 'x86_64', need 'arm64')),
'/System/Volumes/Preboot/Cryptexes/OS/xxx/project/.venv/lib/python3.8/site-packages/pytype/typegraph/cfg.cpython-38-darwin.so' (no such file), 
'/xxx/project/.venv/lib/python3.8/site-
packages/pytype/typegraph/cfg.cpython-38-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```
python version: 3.11.4 
OS: MacOS 13.4.1

**Comment by rchen152** [comment]
What command did you run that generated this error?

**Comment by TiansuYu** [comment]
`pipenv run pytype`

**Comment by rchen152** [comment]
Thanks. I don't get that error when running your command, so it seems likely it's an OS-specific error. I don't have access to a non-Linux machine, so I can only provide a very limited amount of debugging help, unfortunately. Do any of the suggestions here help you? https://stackoverflow.com/questions/70723757/arch-x86-64-and-arm64e-is-available-but-python3-is-saying-incompatible-architect

**Comment by TiansuYu** [comment]
@rchen152 No worries. Just want to report this bug. Very likely that a c lib you guys are using doesnt have a arm dependency. I would recommend having tested the code on arm machines as well. (And github / MS should have supported it long time ago.)
