### ISSUE TITLE
pytype doesn't raise an error when singleton type (enum) is used in Union

### ISSUE THREAD

**Issue by p-malecki** [google/pytype#1564]
Pytype doesn't raise an error when singleton type (enum) is used in Union.
An example is taken from "PEP 484: Support for singleton types in unions". 

#### Example Code

```python
class Empty(Enum):
    token = 0
_empty = Empty.token


def func(x: Union[int, None, Empty] = _empty) -> int:

    boom = x * 42    # This should fail type check

    if x is _empty:
        return 0
    elif x is None:
        return 1
    else:
        return x * 2

func(None)
```

#### Expected Behavior

unsupported operand type(s) for *: 'x: None' and 'int' [unsupported-operands]
unsupported operand type(s) for *: 'x: Empty' and 'int' [unsupported-operands]

#### Actual Behavior

```
Success: no errors found
```

#### System info

```
$ python --version
Python 3.11.6
$ pytype --version
2024.01.05
```

**Comment by rchen152** [comment]
Thanks for the report. This looks like an instance of https://github.com/google/pytype/issues/365.
