### ISSUE TITLE
Type dict key redeclaration

### ISSUE THREAD

**Issue by Yatt0Ikigai** [google/pytype#1566]
As I am new to pytype and unsure whether this behaviour is a bug or not, does pytype allow the redeclaration of TypedDict keys?
```
from typing import TypedDict

class my_map_type(TypedDict):
    y: str
    y: int

my_map: my_map_type = {"y":1, "y":"a"}
```
![image](https://github.com/google/pytype/assets/86158289/bff48d09-17f9-4cee-9937-a2792cbdfffa)

when mypy return
![image](https://github.com/google/pytype/assets/86158289/89b6bcc8-5981-4b38-835e-5149f33e6a5b)

**Comment by rchen152** [comment]
Thanks for the report. This indeed looks like a bug in pytype; I think we should error on the duplicate "y" declaration.
