### ISSUE TITLE
Pytype fails to start if `exclude` option includes paths with `.pyc` files

### ISSUE THREAD

**Issue by drewbrew** [google/pytype#1579]
Hi, I think the [changes](https://github.com/google/pytype/commit/f5a677c9f2de8d4f5bcf0a1363bd6318b70e2a3e#diff-49b40415794ea8451b49a01fab0372c1c50ad90dbb7057ce8d6fc1b152725c4bR146-R153) introduced in #1419 are causing the exclude logic to crash on startup with a `UnicodeDecodeError`.

Here's how to replicate this:

1. In a path with `__pycache__` from old (pre-3.10) versions of Python (easy way appears to be [`python3.9 -m compileall .`](https://stackoverflow.com/questions/5607283/how-can-i-manually-generate-a-pyc-file-from-a-py-file)), add `**/__pycache__/**` to your `exclude` option in `pytype.cfg` (my use case is a Django project: I exclude `**/migrations/` so that pytype doesn't complain about the auto-generated code)
2. Using python 3.11, run `pytype --config pytype.cfg`
3. Observe the crash during startup.

The naive ways to fix this would be to either add in `if f.endswith(".pyc"): continue` in [`expand_source_files()`](https://github.com/google/pytype/blob/main/pytype/file_utils.py#L116-L126) or enclose the call to [read the line](https://github.com/google/pytype/blob/main/pytype/file_utils.py#L152) in a `try`/`except UnicodeDecodeError: return False`

**Comment by rchen152** [comment]
Thanks for the report and the investigation. Catching UnicodeDecodeError sounds like a reasonable solution.
