### ISSUE TITLE
ParseError: Duplicate top-level identifier(s): _N

### ISSUE THREAD

**Issue by tmladek** [google/pytype#159]
Hello,
apologies in advance if this is not appropriate for this repo, but I'm running pytype 2018.9.18 on my codebase, and I can't find my way around this error:

```
$ pytype mq
Analyzing 4 sources with 262 dependencies
File "*snip*/mq/queue.py", line 2, in <module>: Couldn't import pyi for 'kombu.mixins' [pyi-error]
  ParseError: Duplicate top-level identifier(s): _N

For more details, see https://github.com/google/pytype/blob/master/docs/errors.md#pyi-error.
```

When I look into the appropriate `pyi` file, I do indeed see a duplicate definition:

```
$ grep '_N' pytype_output/kombu/mixins.pyi
_N = TypeVar('_N', int, Union[float, int])
_N = TypeVar('_N', int, float)
def count(start: _N = ..., step: _N = ...) -> Iterator[_N]: ...
```

These two almost seem interchangeable, so I tried removing one of those and rerunning pytype, but as it turns out, the `pyi` file gets regenerated and the process fails again.

There is nothing in the file (https://github.com/celery/kombu/blob/master/kombu/mixins.py) that immediately suggests to me what's wrong (the `count` function seems to be imported from `itertools`), and I couldn't find any info on the `_N` type variable, so I'm pretty much stuck.

Thanks in advance!

**Comment by rchen152** [comment]
This is indeed the appropriate repo! My guess is that there's more than one imported function in mixins.pyi using `_N`, but I'll have to keep looking to see if I can find it.

You can get around this error by putting `# pytype: disable=pyi-error` at the end of the line that imports kombu.mixins, or by running pytype with `disable = pyi-error`. The former is probably the better workaround unless you're hitting multiple pyi errors.

**Comment by rchen152** [comment]
Huh, on further investigation, there isn't a second `_N` being imported anywhere; pytype just generates two for the single itertools.count import:
```
$ cat foo.py
from itertools import count
$ pytype-single foo.py -V3.6 -o - --quick
# (generated with --quick)

from typing import Iterator, TypeVar, Union

_N = TypeVar('_N', int, Union[float, int])
_N = TypeVar('_N', int, float)

def count(start: _N = ..., step: _N = ...) -> Iterator[_N]: ...
```
This is with pytype-2018.9.18 and importlab-0.3.0.

**Comment by martindemello** [comment]
only happens with -V 3.6 too

**Comment by martindemello** [comment]
minimal repro case:

```
$ cat foo.pyi 
from typing import TypeVar

T = TypeVar('T', float)

def f(x: T) -> T: ...
```

```
$ cat t.py 
from foo import f
```

```
$ pytype-single t.py -o -
```
from typing import TypeVar, Union

T = TypeVar('T', Union[float, int])
T = TypeVar('T', float)

def f(x: T) -> T: ...
```
