### ISSUE TITLE
Use typeshed for (the remaining files in) pytd/builtins/*.pytd

### ISSUE THREAD

**Issue by matthiaskramm** [google/pytype#16]
pytype still has a handful of its own builtins, since it can't parse the corresponding typeshed files yet. They're in `pytype/pytd/builtins/*.pytd` and `pytype/pytd/stdlib/*.pytd`.

`__builtins__.pytd` might be an exception, since it models the behaviour of mutable types more precisely than `builtins.pyi` in typeshed. `collections.pyi` and `itertools.pyi` we might want to keep, as well.

All the other `.pytd` files should be removed. Files like `os.pytd` and `codes.pytd` are shadowing a much better definition in `typeshed`.

**Comment by rchen152** [comment]
The problematic files left are
* stdlib/2and3/xmlrpclib.pytd - typeshed/stdlib/2/xmlrpclib.pyi is parseable, so we may be able to delete this file now, if it doesn't cause too many breakages.
* builtins/2and3/array.pytd - we should be able to remove this now that we recognize `arrray.array.__init__` method as doing a mutation!

**Comment by rchen152** [comment]
Actually, the `array.array` issue isn't fixed yet - I must've made a mistake in my earlier testing.

**Comment by rchen152** [comment]
There's also stdlib/3/asyncio/tasks.pytd (see https://github.com/google/pytype/issues/203).

**Comment by rchen152** [comment]
Closing this issue since we haven't been using it to track the removal of pytd stubs for a long time.
