### ISSUE TITLE
Pytype sometimes misses import-related module-attr errors

### ISSUE THREAD

**Issue by rchen152** [google/pytype#175]
Input:
```
test2/
  - __init__.py      # empty
  - main.py          # see below
  + deep/
    - __init__.py    # empty
    - a.py           # defines class A with attribute 'x'
  + far/
    - __init__.py    # empty
    - b.py           # defines class B with attribute 'y'
```

main.py:
```
import test2.dee.a
x = test2.deep.a.A(1)
y = test2.far.b.B(2)
print(x.x, y.y)
```

Python Output:
```
Command: `PYTHONPATH=.. python3.6 main.py`
Output:
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    y = test2.far.b.B(2)
AttributeError: module 'test2' has no attribute 'far'
```

**Pytype Output:**
```
Command: `pytype -V3.6 -P .. .`
Output:
Analyzing 6 sources with 0 dependencies
```

But also, sometimes:
```
Analyzing 6 sources with 0 dependencies
File "/tmp/test2/main.py", line 3, in <module>: No attribute 'far' on module 'test2' [module-attr]

For more details, see https://github.com/google/pytype/blob/master/docs/errors.md#module-attr
```

The Problem:
Pytype sometimes doesn't report an error that will occur at runtime. It's not really a type error, but it's still the kind of thing we should probably catch.

What's Going On?
Here's the source tree according to `pytype -V3.6 -P .. --tree .`:
```
Source tree:
+ test2/__init__.py
+ test2/deep/__init__.py
+ test2/main.py
    + test2/deep/a.py
+ test2/far/b.py
+ test2/far/__init__.py
```

(It's not wrong, based on the imports. `main.py` _should_ import `test2.far.b`, but it doesn't.)
The only guarantee we have is that `test2/deep/a.py` will be processed before `test2/main.py`. The leaves may be processed in any order.

When pytype is checking `test2/main.py`, it basically does the following:
1. Import `test2.deep.a`. Short version: the vm's loader loads the pyi, which exists because we know `test2/deep/a.py` was already processed.
2. Load `test2.deep.a.A` and call it with the given argument.
3. Load `test2.far.b.B` and call it with the given argument.
4. Load x.x and y.y and print them.

The bug is in step 3. When the vm tries to load_attr `far` of `test2`, it hits attribute.AbstractAttributeHandler._get_module_attribute, which will call abstract.Module.get_submodule. That, in turn, calls vm.VirtualMachine.import_module, same as if the file contained `import test2.far.b`. The loader attempts to load the pyi file for `test2/far/b.py`.
Does this succeed? Well, that depends on what order pytype processes the files. Since `b.py` is a leaf, it might have been processed. If it was, `b.pyi` exists and the load succeeds. If not, pytype produces the error.

**Comment by martindemello** [comment]
it looks like the fix is to never trigger an import statement from an attribute access (i.e. insist that all imports be explicit). not sure what else is relying on that behaviour.
