### ISSUE TITLE
bytearray.__delitem__ should support a slice argument?

### ISSUE THREAD

**Issue by byllyfish** [google/pytype#178]
Given this input, pytype 2018.9.26 (python 3.6.3) gives a wrong-arg-types warning.

```python
ba = bytearray(bytes("hello", encoding="utf-8"))
del ba[0:2]
```

Here is the warning:

```
File "/bytearray.py", line 2, in <module>: Function bytearray.__delitem__ was called with the wrong arguments [wrong-arg-types]
  Expected: (self, y: int)
  Actually passed: (self, y: slice)
```

It looks like the python3 stub for bytearray in builtins.pytd is not overloaded for slices? (same for python2).

https://github.com/google/pytype/blob/309a87fab8a861241823592157208e65c970f7b6/pytype/pytd/builtins/3/builtins.pytd#L345

**Comment by rchen152** [comment]
Good catch!
