### ISSUE TITLE
Cross platform congrats

### ISSUE THREAD

**Issue by antongonz** [google/pytype#1808]
Only Google engineers are incompetent enough to make this code non cross platform

**Comment by frigus02** [comment]
Hi there. I need to point you to the code of conduct here: https://github.com/google/pytype?tab=coc-ov-file#readme. Please be respectful.

If you have a particular issue to report, please include as much detail as possible, we we're going to see what we can do. In general pytype should work on macOS, Linux and Windows. Though Windows is still a bit experimental.
