### ISSUE TITLE
pytype should use the environment that it is run in by default

### ISSUE THREAD

**Issue by brianquinlan** [google/pytype#192]
That would make it more usage in virtual environments e.g.
```
$ /usr/bin/virtualenv -p python3.6 venv
$ source venv/bin/activate
$ pip install <my deps>
$ pip install pytype
$ pytype --some-flag <my path>
[pytype should use the environment of the python that it is running under]
```

**Comment by rchen152** [comment]
Is this currently broken for you? pytype should already be able to use the virtualenv's environment as long as the virtualenv is activated and its version is passed to pytype with `-V3.6`. From our discussion, I thought the request was for pytype to pick this version by default, but from the wording of the issue, it sounds like you're not able to get pytype working inside a virtualenv at all.

**Comment by brianquinlan** [comment]
Ah, I tried that and it did work, thanks! The usage is still slightly awkward and not (at least to me) intuitive.

**Comment by rchen152** [comment]
Great! I'll update the title then.
