### ISSUE TITLE
How to solve  build.ninja error

### ISSUE THREAD

**Issue by fahad80** [google/pytype#206]
I am trying to use pytype for the first time. But I got ninja error. Tried to google it, but couldn't find anything helpful. What am I missing?

OS: Windows 10
Python version: 3.7
```
D:\New>pytype foo.py
Computing dependencies
Analyzing 1 sources with 0 local dependencies
ninja: error: build.ninja:5: expected build command name
build D:\New\pytype_output\pyi\foo.pyi: check D:\New\foo.py
        ^ near here
ninja: Entering directory `D:\New\pytype_output'
```

**Comment by rchen152** [comment]
Thanks for checking out pytype! Unfortunately, we don't support Windows yet. I'm going to merge this issue with https://github.com/google/pytype/issues/90, which documents known problems with running pytype on Windows.
