### ISSUE TITLE
python 3.7 travis tests are using target python_version = (3, 6)

### ISSUE THREAD

**Issue by byllyfish** [google/pytype#208]
I'm making a PR to fix issue #203 (import asyncio fails under 3.7). I was puzzled that this failure was not being caught already; there are a few tests that import asyncio.

In pytype/tests/test_base.py, the python_version for Python3 is hard-wired to (3, 6). So, I changed this to use (3, 7), when the pytype host is 3.7. (see https://github.com/google/pytype/compare/master...byllyfish:asyncio_tasks)

This change forces the asyncio failure, but it also elicits a number of other test failures. Here's an example:

```
>>> FAIL - pytype.tests.test_dict - /root/pytype/out/pytype/tests/test_dict.log
```

There are 5 failures in this log. test_pop is one of them.

```
FAIL: pytype.tests.test_dict.DictTest.testPop_py3
Traceback (most recent call last):
  File "/root/pytype/out/pytype/tests/test_base.py", line 536, in Replacement
    return actual_method(self, *args, **kwargs)
  File "/root/pytype/out/pytype/tests/test_dict.py", line 22, in testPop
    """)
  File "/root/pytype/out/pytype/tests/test_base.py", line 459, in assertTypesMatchPytd
    self.assertMultiLineEqual(pytd_tree_src, ty_src)
AssertionError: 'from typing import Dict\n\nd: Dict[str, int]\nv1: int\nv2: None\n' != 'from typing import Any, Dict\n\nd: Dict[str, int]\nv1: Any\nv2: Any\n'
- from typing import Dict
+ from typing import Any, Dict
?                    +++++

  d: Dict[str, int]
- v1: int
?     ^ ^
+ v1: Any
?     ^ ^
- v2: None
+ v2: Any

```

I can confirm this difference using pytype. (It looks like many of the 3.7 test failures are the inferencer punting to Any).

```sh
$ cat test_pop.py 
d = {"a": 42}
v1 = d.pop("a")
v2 = d.pop("b", None)

$ pytype -V 3.7 test_pop.py 
...
$ cat pytype_output/pyi/test_pop.pyi 
# (generated with --quick)

from typing import Any, Dict

d: Dict[str, int]
v1: Any
v2: Any
$ pytype -V 3.6 test_pop.py 
...
$ cat pytype_output/pyi/test_pop.pyi 
# (generated with --quick)

from typing import Dict

d: Dict[str, int]
v1: int
v2: None

```

**Comment by rchen152** [comment]
The `Any`s look like they're probably caused by https://github.com/google/pytype/blob/master/pytype/vm.py#L2714: there's a new CALL_METHOD opcode in 3.7 that we haven't implemented yet. I'll take a stab at fixing that.
