### ISSUE TITLE
Generating pyis in the right order is cumbersome

### ISSUE THREAD

**Issue by gramster** [google/pytype#21]
I just see this kind of declaration being generated:

```
  def to_dataframe(self, ...) -> Any: ...
  def to_file(self, path, ...) -> Any: ...
  def to_view(self, view_name) -> Any: ...
```

I..e. with optional args it just generates '...' and with positional args it just outputs the arg name, and the return types are just Any. This seems to be so generic as to not be useful at all. What am I missing here?

I'm just running this like:

```
pytype foo.py -o foo.pyi
```

**Comment by matthiaskramm** [comment]
Hm, it typically generates better output. Let me do a sync to make sure github contains the newest version.

In the meantime, could you append your `foo.py`?

**Comment by gramster** [comment]
I was trying it out on Cloud Datalab; the specific examples above came from this:

https://github.com/GoogleCloudPlatform/datalab/blob/master/sources/lib/datalab/datalab/bigquery/_query.py

**Comment by matthiaskramm** [comment]
You'll want whole-program analysis for that. Did you get a lot of import errors? Or did you generate `.pyi` for all the modules used by `_query.py`?

**Comment by gramster** [comment]
I just ran it as a single file (like I describe in the report); based on
your talk I thought whole program analysis was not ready.

**Comment by matthiaskramm** [comment]
You can do whole-program analysis manually.
In your example, you'd run
```
pytype _view.py -o _view.pyi
pytype _query_job.py -o _query_job.pyi
```

etc., before doing

```
pytype --pythonpath=. foo.py -o foo.pyi
```

Does that improve things?

**Comment by gramster** [comment]
I started doing this but hit another problem on `import uuid`:

   Error while parsing pyi:

     File "(2, 7)/uuid.pyi", line 5
       class _UUIDFields(NamedTuple('_UUIDFields',
                                ^
   SyntaxError: Unexpected 'LPAREN'

**Comment by gramster** [comment]
Another one, from urllib:

    Error while parsing pyi:

      File "(2, 7)/urllib.pyi", line 131
        def getproxies() -> Mapping[str, str]: ... # type: Any
                                                   ^ 
    SyntaxError: Unexpected 'TYPECOMMENT'

**Comment by matthiaskramm** [comment]
Could you try pytype HEAD? I pushed a new version yesterday evening.

**Comment by gramster** [comment]
Second problem changed to:

    bash-3.2$ pytype -o _http.pyi _http.py
    File "_http.py", line 18, in <module>: Can't find module 'httplib2' [import-error]
    File "urllib.pyi", line 131: Unexpected 'TYPECOMMENT' [pyi-error]

**Comment by gramster** [comment]
First one changed to:

    File "uuid.pyi", line 5: Unexpected 'LPAREN' [pyi-error]

**Comment by gramster** [comment]
Some other errors in the first one:

    File "_job.py", line 15, in <module>: Can't find module 'concurrent' [import-error]

    File "_job.py", line 164, in _refresh_state: Missing parameter 'limit' in call to function traceback.format_exc
       [missing-parameter]
    File "_job.py", line 193, in wait: unsupported operand type(s) for __sub__: 'None' and 'int' [unsupported-operands]
    File "_job.py", line 194, in wait: Function time.sleep was called with the wrong arguments
      Expected: (a: float)
      Actually passed: (a: int) [wrong-arg-types]

**Comment by matthiaskramm** [comment]
You should have gotten a `.pyi`, anyway.

Try `_query.py` again, with `--pythonpath` pointing to the `pyi`s you just generated?

**Comment by gramster** [comment]
Some improvement:

    to_file_async = ...  # type: Any
    def __init__(self, sql: Any, *args, **kwargs) -> None: ...
    def __repr__(self) -> Any: ...
    def __str__(self) -> Any: ...
    def _repr_sql_(self) -> str: ...
    def execute(self, *args, **kwargs) -> _query_job.QueryJob: ...
    def execute_async(self, *args, **kwargs) -> _query_job.QueryJob: ...
    def execute_dry_run(self) -> Any: ...
    def extract(self, storage_uris, *args, **kwargs) -> Any: ...
    def results(self, *args, **kwargs) -> property: ...
    def sample(self, *args, **kwargs) -> property: ...
    def to_dataframe(self, *args, **kwargs) -> Any: ...
    def to_file(self, path, *args, **kwargs) -> Any: ...
    def to_view(self, view_name) -> _view.View: ...

**Comment by matthiaskramm** [comment]
Alright! It figured out that `to_view` returns a `_view.View`. I guess the next step would be to try to get it to infer the return of `to_file`, but for that you will need, at the very least, a `pyi` for `_query_job`.

**Comment by gramster** [comment]
Which I have but it isn't very useful:

    class QueryJob(_job.Job):
        __doc__ = ...  # type: str
        _bytes_processed = ...  # type: None
        _cache_hit = ...  # type: None
        _sql = ...  # type: Any
        _table = ...  # type: _query_results_table.QueryResultsTable
        _total_rows = ...  # type: None
        bytes_processed = ...  # type: property
        cache_hit = ...  # type: property
        results = ...  # type: property
        sql = ...  # type: property
        total_rows = ...  # type: property
        def __init__(self, job_id, table_name, sql, context) -> None: ...
        def wait(self, *args, **kwargs) -> QueryJob: ...

**Comment by matthiaskramm** [comment]
It contains the necessary piece of information, though. (The fact that `wait` returns `QueryJob`)

But looking deeper, that doesn't help with figuring out the return of `to_file`, since the latter just returns its first parameter, which can be anything.

Maybe the inherited `to_file` from the result of `QueryJob.__call__` (wherever that is defined) can be used to constrain the type of path, but for that you'll need to generate all the `pyi`s needed by `_query_job` (datalab.utils etc.)

All this will hopefully become easier once we have importlab and automated deep pyi generation.

**Comment by gramster** [comment]
Yes, I think I'll be waiting a bit :-)

**Comment by gvanrossum** [comment]
> All this will hopefully become easier once we have importlab and automated deep pyi generation.

Is that still coming? I am trying to hack that together myself but maybe I'm wasting my time?

**Comment by matthiaskramm** [comment]
I do still want to finish/release that, but there's no ETA. I wouldn't hold my breath.

**Comment by martindemello** [comment]
importlab has been released: https://github.com/google/importlab

bug reports, usability reports and feature requests welcome over there!
