### ISSUE TITLE
Protocols require ABCMeta to work

### ISSUE THREAD

**Issue by rickeylev** [google/pytype#214]
If a Protocol'd class is used, it will give errors unless ABCMeta is included as a metaclass.

Input:
```
from typing import Protocol
class Foo(Protocol):
  def __call__(self, a: str) -> str:
    ...
```
Expected:
should just work. My reading of pep 544 is that ABCMeta is optional.

Actual:
```
File "/tmp/foo.py", line 9, in __call__: bad option in return type [bad-return-type]
  Expected: str
  Actually returned: None
```

**Comment by rchen152** [comment]
I agree; we shouldn't be requiring ABCMeta.
