### ISSUE TITLE
Variable annotations are broken in Python 3.7

### ISSUE THREAD

**Issue by rchen152** [google/pytype#216]
In 3.7, for code like:
```
from typing import List
v: List[int] = []
```
pytype doesn't see the `List[int]` annotation. The problem is that we're processing variable annotations as part of the STORE_ANNOTATIONS opcode (https://github.com/google/pytype/blob/e09726603f40be9ee212f5d6c2de13719eb4936f/pytype/vm.py#L2564), but 3.7 stores this annotation via `LOAD_NAME(__annotations__)` followed by `STORE_SUBSCR(__annotations__, 'v', List[int])`.

**Comment by xunyang01** [comment]
Is it a typo, STORE_SUBSCR instead of BINARY_SUBSCR?

**Comment by rchen152** [comment]
Whoops, it's indeed supposed to be STORE_SUBSCR. I'll edit it.
