### ISSUE TITLE
PyPI project page includes broken links

### ISSUE THREAD

**Issue by rchen152** [google/pytype#239]
Pytype's README.md includes relative links, which are copied to DESCRIPTION.rst and then the PyPI page (https://pypi.org/project/pytype/), which therefore includes nonsensical links like https://pypi.org/project/pytype/docs/user_guide.md.

**Comment by ritwik12** [comment]
Same goes for https://pypi.org/project/pytype/docs/errors.md
https://pypi.org/project/pytype/docs/faq.md
