### ISSUE TITLE
bytearray.clear() and bytearray.copy() report as attribute-error

### ISSUE THREAD

**Issue by byllyfish** [google/pytype#243]
Given this input, pytype 2019.02.13 (python 3.6.7) reports some attribute-errors:

```
b = bytearray()
b.clear()
b.copy()
```

Here is the output:

```
File "/test_bytearray.py", line 2, in <module>: No attribute 'clear' on bytearray [attribute-error]
File "/test_bytearray.py", line 3, in <module>: No attribute 'copy' on bytearray [attribute-error]
```

All of the other methods for methods for mutable sequence types (https://docs.python.org/3/library/stdtypes.html#mutable-sequence-types) work correctly. These appear to be the only two that are missing for bytearray.

Thanks!

**Comment by rchen152** [comment]
Hmm, looks like we've been adding `clear()` and `copy()` to every subclass of MutableSequence instead of MutableSequence itself because the return type/mutated type depends on the type of `self`. Guess that means these methods need to be added to bytearray as well. Thanks for catching this!

**Comment by vuryleo** [comment]
In my case even `List` can't have `clear` method. This one is pretty basic.
```
a = list()
a.clear()
```
and pytype will report 

```
pytype-single --imports_info [redacted]/pytype_output/imports/b.imports --module-name b -V 3.7 -o [redacted]/pytype_output/pyi/b.pyi --analyze-annotated --nofail --quick /tmp/b.py
File "/tmp/b.py", line 2, in <module>: No attribute 'clear' on List[nothing] [attribute-error]
```

**Comment by rchen152** [comment]
I've made a fix; it should be exported to GitHub sometime today and released later this week.
