### ISSUE TITLE
Add test data to sdist

### ISSUE THREAD

**Issue by jayvdb** [google/pytype#245]
Attempting to run the tests in the sdist results in an error that `test_data` doesnt exist.

`setup.py test` should work out of the box, or at least the docs should indicate how to get it working, e.g. where to fetch extra test data from.

Im currently trying to package for openSUSE, and in rpmbuild can not use git submodules.

Almost working, building from the github archive, and will share it here when done.

**Comment by rchen152** [comment]
I think fixing this is as simple as adding `test_data` to `MAINFEST.in`. I'll pick it up tomorrow.

**Comment by jayvdb** [comment]
Im still have lots of failing tests, but here is the current .spec sequence I am using https://build.opensuse.org/package/show/home:jayvdb:coala:python3-bears/python-pytype

**Comment by rchen152** [comment]
Huh, this issue was supposed to be closed five days ago; guess the "Fixes" line can't be buried in the commit description.
