### ISSUE TITLE
Spurious attribute-error for '__init_subclass__'

### ISSUE THREAD

**Issue by NeilGirdhar** [google/pytype#255]
This is a normal use of `__init_subclass__`:
```
class HasPrograms:

    def __init_subclass__(cls, **kwargs):
        super().__init_subclass__(**kwargs)
        cls.init_programs = [...]
```
but pytype reports a spurious attribute-error.  `object` has `__init_subclass__` since Python 3.6.

**Comment by rchen152** [comment]
Thanks! We'll need to add __init_subclass__ to https://github.com/google/pytype/blob/2f97d0a6d5407003749a8d0ce487230177e435a6/pytype/pytd/builtins/3/__builtin__.pytd#L133 and teach pytype to call it (only) on subclasses.

**Comment by NeilGirdhar** [comment]
Also, `__init_subclass__` is a classmethod even though it is not decorated as such, and so pytype should know that its first argument is `Type[C]` rather than `C`.

**Comment by martindemello** [comment]
[typeshed does not define it as a classmethod](https://github.com/python/typeshed/blob/master/stdlib/2and3/builtins.pyi#L68) and neither does the python source, so i'm not sure we should.

**Comment by rchen152** [comment]
The documentation says it's a classmethod: https://docs.python.org/3/reference/datamodel.html#object.__init_subclass__. In the CPython source code, it appears to be special-cased: https://github.com/python/cpython/blob/4d231bcc77ac8ce7d11bda0804130dcdd678f710/Objects/typeobject.c#L2701-L2702.

Unless we special-case it in pytype as well, we probably need the decorator.

**Comment by rchen152** [comment]
pytype no longer raises an attribute error for `__init_subclass__`. It analyzes it as a classmethod of the class on which it is defined, which isn't quite right but should be good enough for most type-checking purposes.
