### ISSUE TITLE
Can't find module 'contextlib.AbstractContextManager'

### ISSUE THREAD

**Issue by NeilGirdhar** [google/pytype#256]
The following line gives an error: `from contextlib import AbstractContextManager`.  `AbstractContextManager` has been in Python since version 3.6.

**Comment by rchen152** [comment]
This is caused by the parser not re-exporting names that come from the typing module: https://github.com/google/pytype/blob/2f97d0a6d5407003749a8d0ce487230177e435a6/pytype/pyi/parser.py#L716. Should be a quick fix.

**Comment by kamahen** [comment]
Apparently mypy only re-exports names that have an "as" clause, e.g.
```python
from typing import ContextManager as ContextManager
```

https://github.com/python/mypy/issues/2927
https://github.com/python/typeshed/issues/2727

**Comment by rchen152** [comment]
This has been fixed, pending the next pytype release (this Friday if all goes well).

**Comment by NeilGirdhar** [comment]
Wow, that was fast!!
