### ISSUE TITLE
Default ast library

### ISSUE THREAD

**Issue by andreinaku** [google/pytype#265]
Hello! I was just browsing through the code and I was just wondering - is there a reason you don't use Python's **ast** library (i.e. https://docs.python.org/3/library/ast.html)?

**Comment by rchen152** [comment]
Hi! We don't use `ast` because it doesn't parse type comments or type annotations. There's a [`typed_ast`](https://pypi.org/project/typed-ast/) that we're considering switching to (and which is merged with `ast` in 3.8+), but there are a few open questions we need to work through first, like what the performance implications would be.

**Comment by kamahen** [comment]
An alternative to `typed_ast` is [lib2to3.pytree](https://github.com/python/cpython/blob/master/Lib/lib2to3/pytree.py). It's probably slower than typed_ast, but in my tests, the cost of parsing was at most a few percent of the overall cost of analysis. (And it probably would be faster if `lib2to3.pytree` were modified to specify `__slots__ = []` for the nodes and leaves.)

**Comment by andreinaku** [comment]
Thanks for the replies!

**Comment by kamahen** [comment]
If you use `lib2to3.pytree`, you probably want to use your own version of `convert` that removes the test for `if len(children) == 1` ... this is convenient for people writing `2to3` rules but causes pain if you're trying to do detailed analysis of the AST (ask me how I know).

And, in case it wasn't obvious from my earlier comments, `lib2to3.pytree` keeps all the comment information ... `Base.get_suffix()` can be handy.

Removed lines are marked by `####`:

```python
def convert(gr, raw_node):
    """
    Convert raw node information to a Node or Leaf instance.

    This is passed to the parser driver which calls it whenever a reduction of a
    grammar rule produces a new complete node, so that the tree is build
    strictly bottom-up.
    """
    type, value, context, children = raw_node
    if children or type in gr.number2symbol:
        #### # If there's exactly one child, return that child instead of
        #### # creating a new node.
        #### if len(children) == 1:
        ####    return children[0]
        return Node(type, children, context=context)
    else:
        return Leaf(type, value, context=context)
```

**Comment by rchen152** [comment]
@andreinaku You're welcome!
