### ISSUE TITLE
Shorten intermediate output.

### ISSUE THREAD

**Issue by rchen152** [google/pytype#277]
Currently, as pytype runs, at every step it prints `pytype-single --analyze-annotated --module-name my_module {blah, blah, blah} /long/absolute/path/my_module.py` to the terminal. ninja rules have a `description` key that we can use to shorten the output to something like `infer my_module`. We can run ninja with the `--verbose` flag when pytype has verbosity=2 to get the full output.

**Comment by hiyashichuka** [comment]
I'd like to take this issue.

**Comment by hiyashichuka** [comment]
I am sorry for the misunderstanding.
