### ISSUE TITLE
Use pylint

### ISSUE THREAD

**Issue by rchen152** [google/pytype#278]
It would be nice to be able to directly run pylint on PRs rather than importing them into Google and then finding out whether they contain lint errors. We can add a .pylintrc file and use options like
```
[FORMAT]
indent-string='  '
```
to get the right configuration.

**Comment by hiyashichuka** [comment]
I'd like to take this issue.

**Comment by rchen152** [comment]
Absolutely, we'd love your help! A couple thoughts:
* The pylintrc files of other Google open source projects (for example, [Python Fire](https://github.com/google/python-fire/blob/master/pylintrc)) would probably be a useful reference for figuring out a good configuration.
* I suspect some of our code won't lint cleanly no matter what we do, thanks to differences between the Google linter and vanilla pylint, so we may have to disable a lot of error classes.

**Comment by hiyashichuka** [comment]
Thanks for letting me know.
I have two questions I want to ask.

1.
>I suspect some of our code won't lint cleanly no matter what we do, thanks to differences 
>between the Google linter and vanilla pylint, so we may have to disable a lot of error 
>classes.

Examples follow
   vanilla pylint Errors occur.           →C0102: Black listed name "%s"　 judged that as Error
   Google linter  Errors NOT occur. →C0102: Black listed name "%s"　 judged that as NOT Error

In this case,I write this.
[MESSAGES CONTROL]
disable=C0102

Is this understanding of mine correct?

2. Let me know how to execute Google linter.
I would like to confirm differences between the Google linter and vanilla pylint.

Please reply when you have a time.

**Comment by rchen152** [comment]
1. Yep, that's exactly what I was imagining.
2. Unfortunately, the Google linter (gpylint) isn't opensourced. I'd be more than happy to work with you to address any issues that come up, but I don't think there's a way for you to run gpylint directly.

**Comment by hiyashichuka** [comment]
Thanks for letting me know.

I will do as follow. Would this be okay?

I will write pylintrc.
The purpose of the pylintrc is to disable vanilla pylint error. 

If my pylintrc is against the  Google linter, please let me know.

**Comment by rchen152** [comment]
Sounds good to me.

**Comment by rchen152** [comment]
@hiyashichuka Thanks again for fixing this issue!
