### ISSUE TITLE
Unable to parse stub conditionals

### ISSUE THREAD

**Issue by tharvik** [google/pytype#28]
In PEP 484, there is a [section](https://www.python.org/dev/peps/pep-0484/#version-and-platform-checking) on conditional stubs.

For example, the next code is a valid stub code
```python
import sys

if sys.version_info <= (3,):
    def old_code_stub() -> None: ...
```

But currently, running `pytd` on it will fail with
```
Error while parsing pyi:

  File "/tmp/asd.py", line 3
    if sys.version_info <= (3,):
          ^
SyntaxError: Unexpected 'DOT'
```

Found while doing [typeshed#345](https://github.com/python/typeshed/pull/345).

**Comment by matthiaskramm** [comment]
Fixed.
