### ISSUE TITLE
Match and __getitem__ error?

### ISSUE THREAD

**Issue by geoffreywiseman** [google/pytype#286]
Hey;

I'm using re to parse some content out of a filename:

```python
    match = self.PN_PATTERN.search(file)
    if match:
       pn = match[0]
       prefix = match[1]
```

pytype says:

`unsupported operand type(s) for item retrieval: 'Match[str]' and 'int' [unsupported-operands]
  No attribute '__getitem__' on Match[str]`

Match definitely does have [__getitem__](https://docs.python.org/3/library/re.html#re.Match.__getitem__).... so what's the issue?

**Comment by rchen152** [comment]
Looks like we're missing `__getitem__` here: https://github.com/google/pytype/blob/f943e9823f7770a954a804e35e09685766857513/pytype/pytd/builtins/2and3/typing.pytd#L356. I'll have a fix out shortly.

**Comment by geoffreywiseman** [comment]
I didn't file it separately because I wasn't sure if *I* was doing something unexpected, but Pattern.fullmatch() had a similar problem, IIRC.
