### ISSUE TITLE
Unable to parse stub platform conditionals

### ISSUE THREAD

**Issue by tharvik** [google/pytype#29]
In PEP 484, there is a [section](https://www.python.org/dev/peps/pep-0484/#version-and-platform-checking) on conditional stubs.

For example, the next code is a valid stub code
```python
import sys

if sys.platform == 'win32':
    def windows_def_only() -> None: ...
```

But currently, running `pytd` on it will fail with
```
Error while parsing pyi:
  File "/tmp/asd.pyi", line 3
    if sys.platform == 'win32':
                        ^
SyntaxError: Unexpected 'NAME'
```

**Comment by matthiaskramm** [comment]
Fixed in our local version. We're exporting the fix now.

**Comment by matthiaskramm** [comment]
Fix pushed.
