### ISSUE TITLE
pytype seems to ignore logging.setLoggerClass()

### ISSUE THREAD

**Issue by dcermak** [google/pytype#300]
First and foremost, thanks for pytype!

I've tried using pytype on [KIWI](https://github.com/SUSE/kiwi) and got the following errors from pytype:
```
File "kiwi/command_process.py", line 126, in _init_progress: No attribute 'progress' on logging.Logger [attribute-error]
File "kiwi/command_process.py", line 131, in _stop_progress: No attribute 'progress' on logging.Logger [attribute-error]
File "kiwi/command_process.py", line 143, in _update_progress: No attribute 'progress' on logging.Logger [attribute-error]
```

These are probably caused by the following issue: KIWI provides a custom logger class, that provides the attributes `_init_progress`, `_stop_progress` and `_update_progress`. This logging class is set in a module via `logging.setLoggerClass(Logger)`. It appears that pytype does not take this into account.

Could this either be added or can I work around this issue by somehow redefining what `logging.getLogger` returns only for the current project?

**Comment by rchen152** [comment]
Thanks for trying out pytype!

You can tell pytype the type of `log` using a variable annotation:
`log: Logger = logging.getLogger("kiwi")`
or, if you'd like to stay compatible with Python 2:
`log = logging.getLogger("kiwi")  # type: Logger`

**Comment by dcermak** [comment]
Would that work too when I add this type annotation to the corresponding `.pyi` file?

**Comment by rchen152** [comment]
If you could get pytype to use the `.pyi` file, then yes, but pytype will overwrite the `.pyi` file every time the corresponding `.py` file changes.

**Comment by dcermak** [comment]
Oh, there's no "only run checks" mode? I was hoping I could use pytype to generate the `.pyi` files but keep them around (the project is still maintaining Python2 compatibility but the main developers don't want to include Python 2 compatible type hints).

Anyway, my original question has been answered, so I'll close this. Thanks for your time and your work on pytype!

**Comment by rchen152** [comment]
Indeed, pytype doesn't do that yet =(
An upcoming feature (https://github.com/google/pytype/issues/151) is to support in-project pyi files, so that users can specify their own types outside of sources.
