### ISSUE TITLE
pytype spins CPU when trying to generate stubs for `relativedelta.py `

### ISSUE THREAD

**Issue by rowillia** [google/pytype#31]
I tried using pytype to generate stubs for https://github.com/dateutil/dateutil/blob/master/dateutil/relativedelta.py.  It pegged a core, I had to  kill the process after waiting ~10 minutes.

**Comment by matthiaskramm** [comment]
Thanks, I can reproduce this. I'd normally advice you to run pytype using `pytype --quick`, but since that causes a different error it won't help in this particular case.

**Comment by rowillia** [comment]
Thanks @matthiaskramm!

**Comment by rchen152** [comment]
This is working for me now. I did:
```
git clone git@github.com:dateutil/dateutil.git
pytype dateutil/dateutil/relativedelta.py
```
Pytype completes without any errors and generates a pyi file at `pytype_output/dateutil/relativedelta.pyi`.
