### ISSUE TITLE
Support @abstractmethod

### ISSUE THREAD

**Issue by tharvik** [google/pytype#32]
In typeshed, there is some stubs which use `@abstractmethod` to specify that a child class should implement a given method. For now, it fails with
```
Error while parsing pyi:
  File "stdlib/2and3/distutils/cmd.pyi", line 10
    @abstractmethod
    ^
SyntaxError: Decorator 'abstractmethod' not supported
```
in [typeshed#418](https://github.com/python/typeshed/pull/418).

It is used elsewhere, `grep -r @abstractmethod | wc -l` in typeshed gives 168 results.

**Comment by alvarocaceres** [comment]
just recently added support for this, will push to github soon

**Comment by tharvik** [comment]
Nice; thanks for the reactivity by the way!

**Comment by alvarocaceres** [comment]
no problem -- `@abstractmethod` should work now
