### ISSUE TITLE
using functools.partial as a class leads to spurious errors

### ISSUE THREAD

**Issue by rchen152** [google/pytype#322]
https://github.com/python/typeshed/commit/e45f443d8530f0dd9f9022720a994f222da6f0fd changed the definition of functools.partial from a class to a function. Things like isinstance() now cause spurious errors.

**Comment by tseaver** [comment]
@rchen152 Per our discussion on https://github.com/googleapis/google-cloud-python/pull/8106, I think it was the other way around (from a class / type to a function).

**Comment by tseaver** [comment]
Oops, the relevant discussion is on https://github.com/googleapis/google-cloud-python/pull/8097.

**Comment by rchen152** [comment]
You're absolutely right - fixed.
