### ISSUE TITLE
merge-pyi imports 1 type per line

### ISSUE THREAD

**Issue by mbarbier1995** [google/pytype#330]
I have a simple file: first_file.py with this function:
```python
def h():
    return {'la': [1, 2, 3]}
```
When I run pytype -V 3.7 first_file.py 
and then 
merge-pyi -i ./first_file.py ./first_file.pyi

It gives me:
``` python
from typing import Dict
from typing import List
def h() -> Dict[str, List[int]]:
    return {'la': [1, 2, 3]}
```

But I am expecting:
``` python
from typing import Dict, List
```
My first_file.pyi seems correct though:
```python
# (generated with --quick)

from typing import Dict, List

def h() -> Dict[str, List[int]]: ...
```

Is it a setting I should modify in my pytype.cfg ?

**Comment by rchen152** [comment]
This looks like a bug in merge-pyi! I suspect it's because we're calling touch_import on each individual typing import here:
https://github.com/google/pytype/blob/1020628ddeb085c9d164778fb58d2dca883db26f/pytype/tools/merge_pyi/merge_pyi.py#L639
