### ISSUE TITLE
Pytype fails with caught ImportError

### ISSUE THREAD

**Issue by pganssle** [google/pytype#337]
It is a fairly common Python idiom to attempt to import something from a given place, then fall through to some sort of backup definition if the import fails. For example, when writing Python 2/3 compatible code (without using `six.moves`), you might do this:

```python
try:
    from itertools import ifilterfalse as filterfalse
except ImportError:
    from itertools import filterfalse
```

However, `pytype` chokes on this in both Python 2 *and* Python 3, because in the Python 2 case, it raises `import-error`, and in Python 3 it raises `import-error` for the second line.

For now it can be "fixed" by adding `# pytype: disable=import-error`, but it would be better if `pytype` could be smarter about it and detect that `import-error` should not be raised in a `try` block that catches `ImportError`, and that `import-error` should not be raised from the `except` block of a `try` statement that catches `ImportError` and *isn't* raising `import-error`.

I'll note that this isn't limited to Python 2/3 polyglot code (which is likely to get rarer as time goes on), but it's also a common idiom for optional "opportunistic" dependencies, and some other situations where you want to import something conditional on whether or not the thing exists.

**Comment by rchen152** [comment]
Thanks for the report! This looks like https://github.com/google/pytype/issues/163, so I'm going to close this issue in favor of that one. I agree that try/except ImportError is worth supporting.

**Comment by pganssle** [comment]
@rchen152 Thanks Rebecca! I have no idea how I missed that. I searched "import" and "ImportError" and a few other terms. Sorry for the noise.
