### ISSUE TITLE
--noquick option?

### ISSUE THREAD

**Issue by kamahen** [google/pytype#344]
The pyi output from pytype has `# (generated with --quick)` at the top.
Presumably there's a slower version that gives deeper analysis, such as figuring out the types of parameters or of local variables. How can I invoke this? (When I tried `--noquick` I got an error)

**Comment by rchen152** [comment]
Non-quick analysis mostly follows call chains more deeply - it's not directly invocable from the main pytype executable, but it also won't do what you want. You can use `--protocols` to infer the types of function parameters (this flag is experimental - if you see any odd behavior, feel free to leave a comment on https://github.com/google/pytype/issues/58), and the `pyxref` binary with the `--debug` option will print types for things like local variables.
