### ISSUE TITLE
pytype unable to find some codecs attributes

### ISSUE THREAD

**Issue by komuw** [google/pytype#348]
this file
```python
import codecs

def encode(input, errors="strict"):
    return codecs.utf_16_be_encode(input, errors)

print(encode("name"))
```
produces;
`pytype --verbosity 0 --python-version 3.6 --protocols --strict-import --keep-going cool.py`

```sh
Computing dependencies
File "/Users/cool.py", line 5, in encode: No attribute 'utf_16_be_encode' on module 'codecs' [module-attr]
```

**Comment by rchen152** [comment]
Indeed, it looks like utf_16_be_encode is missing here: https://github.com/python/typeshed/blob/master/stdlib/2and3/codecs.pyi.

**Comment by rchen152** [comment]
I've added the missing method, so this bug will be fixed the next time we update the version of typeshed that pytype pins to.

**Comment by komuw** [comment]
fixed by; https://github.com/python/typeshed/commit/5dc89fe8cfc69a4dd6741181d2a16ac86ddb7786
