### ISSUE TITLE
wrong-arg-types for UnicodeDecodeError exception

### ISSUE THREAD

**Issue by komuw** [google/pytype#349]
```python
try:
    position = 1
    obj = "A"
    raise UnicodeDecodeError("mycodec", b"ddd", position, position + 1, repr(obj))
except Exception as e:
    print("error= ", str(e))
```

`pytype --verbosity 0 --python-version 3.6 --protocols --strict-import --keep-going cool.py`
```bash
File "/cool.py", line 4, in <module>: Function UnicodeDecodeError.__init__ was called with the wrong arguments [wrong-arg-types]
  Expected: (self, encoding, object: str, ...)
  Actually passed: (self, encoding, object: bytes, ...)
```

maybe `pytype` does not recognise I'm using python3

**Comment by rchen152** [comment]
This looks like a problem with our builtins definitions:

https://github.com/google/pytype/blob/27eb234da9f3477156dc653114867d07fc2353c9/pytype/pytd/builtins/3/__builtin__.pytd#L1071

Most likely, we copied the python 2 definition over and forgot to change the type of the `object` parameter.
