### ISSUE TITLE
io.TextIOWrapper.__init__() type error

### ISSUE THREAD

**Issue by dpursell** [google/pytype#356]
Hey there, I'm not 100% sure on this but I think a type on `io.TextIOWrapper.__init__()` may be incorrectly specified, so I'm filing a bug as per https://google.github.io/pytype/user_guide.html#pytypes-pyi-stub-files.

The [TextIOWrapper docs](https://docs.python.org/3.6/library/io.html#io.TextIOWrapper) say "A buffered text stream over a BufferedIOBase binary stream", which isn't totally clear what "over" means but I think indicates that the `buffer` parameter should be of type `io.BufferedIOBase`. However, it's specified as `IO[bytes]` instead, causing type errors when analyzed by pytype.

Sample program:
```
import io

def test():
    # FileIO implements RawIOBase.
    # https://docs.python.org/3.6/library/io.html#io.FileIO
    raw = io.FileIO('foo.txt')

    # BufferedReader takes RawIOBase and implements BufferedIOBase.
    # https://docs.python.org/3.6/library/io.html#io.BufferedReader
    buffered = io.BufferedReader(raw)

    # TextIOWrapper takes BufferedIOBase.
    # https://docs.python.org/3.6/library/io.html#io.TextIOWrapper
    text_wrapper = io.TextIOWrapper(buffered)
```
Result:
```
$ pytype test.py 
...
line 14, in test: Function TextIOWrapper.__init__ was called with the wrong arguments [wrong-arg-types]
  Expected: (self, buffer: IO[bytes], ...)
  Actually passed: (self, buffer: io.BufferedReader)
...
```

Thanks!

**Comment by rchen152** [comment]
Thanks for the report! I agree with your reading of the io docs. Maybe we need to make RawIOBase inherit from IO[bytes] in addition to IOBase: https://github.com/python/typeshed/blob/4ae4714e00b167d4280b379cab66ea6f15b0c0d3/stdlib/3/io.pyi#L49.

**Comment by rchen152** [comment]
pytype no longer reports any error on the example code.
