### ISSUE TITLE
Crash with the attached script

### ISSUE THREAD

**Issue by mcepl** [google/pytype#36]
When analyzing the script http://paste.fedoraproject.org/422337/30903421/ (yes, it is wrong), `pytype` crashes (see attached output with `-v 4`). I don't think crash is very a good idea, is it?

[compare_versions-pytype-log.txt](https://github.com/google/pytype/files/455323/compare_versions-pytype-log.txt)

**Comment by matthiaskramm** [comment]
Thanks for reporting this! It's a known issue. We'll export a fix soon.

**Comment by martindemello** [comment]
looking through the stack trace, i believe this is fixed, but cannot verify since the script link has expired.
