### ISSUE TITLE
Comment syntax for varargs, kwargs incompatible with PEP-484, mypy

### ISSUE THREAD

**Issue by wiml** [google/pytype#362]
If you're using comment syntax to annotate a function that takes variable arguments, [PEP-484](https://www.python.org/dev/peps/pep-0484/#suggested-syntax-for-python-2-7-and-straddling-code) and mypy want you to use this syntax:

```python
def somefunc(a, b, *c, **kw):
    # type: (int, bool, *str, **bytes) -> int
    return something
```

However, pytype requires you to omit the `*` and `**` in the `type:` comment,  or else you get an `invalid-function-type-comment` error.

**Comment by rchen152** [comment]
Thanks for the report! That indeed looks like a pytype bug.

**Comment by rchen152** [comment]
Now that Python 2 has reached end-of-life, we're very unlikely to add support for this, so closing.
