### ISSUE TITLE
__suppress_context__ not recognized

### ISSUE THREAD

**Issue by dumblob** [google/pytype#367]
`test_suppress_context.py`:
```python
e = BaseException( 'howk' )
print( e.__suppress_context__ )
```
BaseException shall probably not be instantiated, but it doesn't matter as `dir( BaseException( 'howk' ) )` shows the attribute `__suppress_context__` correctly and thus pytype shall do as well.
result:
```
[1/1] check test_suppress_context
FAILED: /home/xxx/app/.pytype/pyi/test_suppress_context.pyi 
pytype-single --imports_info /home/xxx/app/.pytype/imports/test_suppress_context.imports --module-name test_suppress_context -V 3.7 -o /home/xxx/app/.pytype/pyi/test_suppress_context.pyi --analyze-annotated --nofail --quick /home/xxx/app/test_suppress_context.py
File "/home/xxx/app/test_suppress_context.py", line 2, in <module>: No attribute '__suppress_context__' on BaseException [attribute-error]

For more details, see https://google.github.io/pytype/errors.html#attribute-error.
ninja: build stopped: subcommand failed.
```
This presumably shall not happen as it's a Python builtin feature...

**Comment by rchen152** [comment]
Thanks for the report! It looks like we need to define `__suppress_context__` here: https://github.com/google/pytype/blob/a123f085ac9ae0c1677ce31818042514da6e8f37/pytype/pytd/builtins/3/__builtin__.pytd#L944
