### ISSUE TITLE
pytype does not recognize token.NL, token.COMMENT and token.ENCODING

### ISSUE THREAD

**Issue by laike9m** [google/pytype#374]
They were moved from `tokenize` to `token` in Python 3.7:
https://docs.python.org/3.7/library/token.html#token.COMMENT

Reproduce
1. Create a `test.py` with one line:
```python
from token import NL, COMMENT, ENCODING
```
2. run 
```bash
$ pytype test.py
Computing dependencies
Analyzing 1 sources with 0 local dependencies
ninja: Entering directory `/Users/laike9m/Dev/Python/Cyberbrain/.pytype'
[1/1] check test
FAILED: /Users/laike9m/Dev/Python/Cyberbrain/.pytype/pyi/test.pyi
pytype-single --imports_info /Users/laike9m/Dev/Python/Cyberbrain/.pytype/imports/test.imports --module-name test -V 3.7 -o /Users/laike9m/Dev/Python/Cyberbrain/.pytype/pyi/test.pyi --analyze-annotated --nofail --quick /Users/laike9m/Dev/Python/Cyberbrain/test.py
File "/Users/laike9m/Dev/Python/Cyberbrain/test.py", line 1, in <module>: Can't find module 'token.NL'. [import-error]
File "/Users/laike9m/Dev/Python/Cyberbrain/test.py", line 1, in <module>: Can't find module 'token.COMMENT'. [import-error]
File "/Users/laike9m/Dev/Python/Cyberbrain/test.py", line 1, in <module>: Can't find module 'token.ENCODING'. [import-error]

For more details, see https://google.github.io/pytype/errors.html#import-error.
ninja: build stopped: subcommand failed.
```

**Comment by rchen152** [comment]
Looks like these constants are missing from https://github.com/python/typeshed/blob/master/stdlib/2and3/token.pyi. They're new in 3.7, so most likely the pyi file hasn't been updated in a while.

**Comment by rchen152** [comment]
I opened https://github.com/python/typeshed/pull/3175.

**Comment by laike9m** [comment]
Thanks :)

**Comment by rchen152** [comment]
The typeshed PR has been merged, so I'll go ahead and close this issue. The fix will be in the next pytype release.

**Comment by laike9m** [comment]
With 2019.08.09, this error still exists.

**Comment by rchen152** [comment]
Oops, sorry about that! This week's release ended up being really messy, so I decided not to bundle a typeshed update with it but forgot to update this bug. I'll reassign it to myself and close it once this fix is actually released.

**Comment by rchen152** [comment]
Sorry for the delay. pytype 2019.08.29 contains a more recent copy of typeshed in which this bug is fixed.

**Comment by laike9m** [comment]
Cool, thanks
