### ISSUE TITLE
TypeVar may appear only once in signature if used in the body

### ISSUE THREAD

**Issue by dumblob** [google/pytype#379]
```python
from typing import Callable, TypeVar
__T = TypeVar( '__T' )
def mywrap( func: Callable[..., __T] ):
  # __T shall be the one from signature
  def f( *a, **b ) -> __T:
    # __T shall be the one from signature
    x: List[Tuple[ bool, Type[BaseException], Callable[[__T], __T] ]] = []
    return func( *a, **b )
```
```
ninja: Entering directory `/home/user/app/.pytype'
[1/1] check pytype_issues
FAILED: /home/user/app/.pytype/pyi/pytype_issues.pyi 
pytype-single --imports_info /home/user/app/.pytype/imports/pytype_issues.imports --module-name pytype_issues -V 3.7 -o /home/user/app/.pytype/pyi/pytype_issues.pyi --analyze-annotated --nofail --quick /home/user/app/pytype_issues.py
File "/home/user/app/pytype_issues.py", line 3, in <module>: Invalid type annotation '__T'  [invalid-annotation]
  Appears only once in the signature

For more details, see https://google.github.io/pytype/errors.html#invalid-annotation.
ninja: build stopped: subcommand failed.
Computing dependencies
Analyzing 1 sources with 0 local dependencies
```

**Comment by rchen152** [comment]
Interesting. I don't think pytype takes into account the function body at all when checking the typevar count.

**Comment by domandinho** [comment]
Good afternoon,

I take a look at the code and it looks like @rchen152 is right and pytype don't check function body in this check. I suspect that it doesn't do a check for nested methods.
For example for this code it raises a warning:

```
from typing import TypeVar
T = TypeVar('T')

def f(x: T):
	def g(x: T):
		print(x)
```

But for that it doesn't detect anything:

```
from typing import TypeVar
T = TypeVar('T')

def mywrap(x):
  def f(x: T):
  	def g(x: T):
  		print(x)
```
I can imagine also such example:

```
from typing import TypeVar
T = TypeVar('T')

def mywrap(x: T):
  def f(x: T) -> T:
  	return x
  def g(x: T):
  	print(x)
  g(f(x))
```

where pytype raises a warning, but these type annotations are correct and may be beneficial.

I would like to kindly ask a question is this desired behavior to take into account nested methods during this check?

Kind Regards
Piotr Domański

**Comment by dumblob** [comment]
>I would like to kindly ask a question is this desired behavior to take into account nested methods during this check?

IMHO definitely. If there is any `TypeVar` variable, then this variable shall be taken into account everywhere including nested methods, functions, whatever. That is at least what makes sense to me and how I read [PEP 484](https://www.python.org/dev/peps/pep-0484/ ).

**Comment by thomasrea0113** [comment]
I should note, that decorators that they themselves return an argument are also not working properly. This signature should be valid:

```python
from typing import TYPE_CHECKING
from django.core.cache import caches

if TYPE_CHECKING:
    from typing import Callable, TypeVar
    _T = TypeVar('_T')


def singleton(default: '_T', timeout: 'int' = 5):
    def decorator(func: 'Callable[[], _T]'):
        def inner() -> '_T':
            cache_val: '_T | None' = caches['default'].get_or_set(
                func.__name__, func, timeout)
            return cache_val or default
        return inner
    return decorator
```

Type checking works exactly as expected when using the decorator

![image](https://user-images.githubusercontent.com/14018447/128633182-5f456029-58e4-44a2-8440-575c4744d76c.png)

But I get this error

![image](https://user-images.githubusercontent.com/14018447/128633205-8154bc97-b01c-46d6-87b0-a93ad93fe935.png)

**Comment by JelleZijlstra** [comment]
@thomasrea0113 that error is being produced by pyright, not pytype.

**Comment by rchen152** [comment]
Thanks, Jelle. Yep, that looks like pyright. I believe the pyright repository is https://github.com/microsoft/pyright.
