### ISSUE TITLE
isinstance() doesn't prevent type errors for some types

### ISSUE THREAD

**Issue by david-seiler** [google/pytype#391]
I'd expect a block defined by `if isinstance(val, someType):` to generate no type errors in the case where `val` is known to not be `someType`, but for some types (or some modules?) that doesn't work:

    import mxnet
    import numpy
    import datetime
    
    value = 3
    
    # raises "No attribute 'asnumpy' on int"
    if isinstance(value, mxnet.nd.NDArray):
        value.asnumpy()
    
    # raises "No attribute 'frob' on int".  numpy.ndarray has no frob() method, but that's ok.
    if isinstance(value, numpy.ndarray):
        value.frob()
    
    # type-checks successfully, as expected
    if isinstance(value, datetime.datetime):
        value = value.frob()

All the built-in libraries that I tried worked fine, and none of the modules I'd installed via pip did, but I didn't dig all that deeply so I don't know how generally that pattern holds.

**Comment by rchen152** [comment]
I think what's going on here is that pytype doesn't always have type information for pip-installed libraries, so something like `isinstance(value, mxnet.nd.NDArray)` gets interpreted as `isinstance(value, typing.Any)`, which doesn't constrain the type. At least for numpy, we have an internal stub, so I'll look into open sourcing that, but that doesn't solve the problem generally, I'm afraid.

**Comment by david-seiler** [comment]
Ah, that makes sense, and most of the time it's what I'd want (in a method signature, for example).  We don't have that pattern in many places, so in the short run I think we can just suppress those type errors.
