### ISSUE TITLE
Crashes with Python 3.5 script

### ISSUE THREAD

**Issue by impredicative** [google/pytype#40]
For [**this**](https://github.com/ab-sf-spark/genbank-fetch/blob/master/genbankfetch/__main__.py) python3.5 script, I was getting `urllib` errors. Even when I used `--nofail`, I was still getting `inspect` errors. Also, some messages printed by `pytype`, such as about `super()`, etc. were not relevant. Note that the script currently doesn't have any package dependencies, and so it's trivial to test. Thanks.

**Comment by martindemello** [comment]
link to script is broken, but 3.5 and 3.6 crashes should be fixed now - if you still run into this, could you reopen the bug or file a new one?
