### ISSUE TITLE
False error for @dataclass

### ISSUE THREAD

**Issue by laike9m** [google/pytype#400]
Python version : `3.7.3`, pytype version: `2019.08.29`

```
from dataclasses import dataclass

@dataclass()
class VarAppearance:
    id: str
    value: str

a = VarAppearance(id="x", value="y")
```

gives:
```
Invalid keyword arguments (id, value) to function VarAppearance.__init__ [wrong-keyword-args]
  Expected: (self)
  Actually passed: (self, id, value)
```

If called with `a = VarAppearance("x", "y")`, it gives
```
Function VarAppearance.__init__ expects 1 arg(s), got 3 [wrong-arg-count]
  Expected: (self)
  Actually passed: (self, _, _)
```

**Comment by rchen152** [comment]
Unfortunately, pytype doesn't support dataclasses yet (https://github.com/google/pytype/issues/234). We're hoping to add 3.7 support soon, including dataclasses, but we're all busy right now with 3.6-related work, so it's unclear when that'll happen.

I'm going to close this issue in favor of the already-open one for dataclasses, but thanks for filing it!
