### ISSUE TITLE
unexpected List type inference behavior

### ISSUE THREAD

**Issue by CX8** [google/pytype#401]
Pytype 2019.08.09

Hello, I found the following behaviour not intuitive and, possibly, not working as intended.
Pytype inference "tranforms" the type of a `List[x]` to a `List[Union[x,y]]` when appending or extending a `List[x]` with item `y` or `List[y]`.
When invoking a function `fun(a: List[x])` with `List[Union[x,y]]`, pytype will pass.

I thought it was a case of:
[https://github.com/google/pytype/blob/master/docs/faq.md#why-didnt-pytype-catch-that-my-program-might-pass-an-invalid-argument-to-a-function](url)

but I am not too sure of it. Any feedback is welcome.

```
#test.py
from typing import List

def fun(a: List[str]):
    pass

b: int = 6
a: List[str] = []
a.append(b)
# OK
fun(a)

c: List[str] = []
c.extend([b])
# OK
fun(c)

d: List[str] = []
e: List[int] = [b]
d.extend(e)
# OK
fun(d)

f: List[str] = []
f = [b]
# pytype complains
fun(f)

# test.pyi:
# a: List[Union[int, str]]
# b: int
# c: List[Union[int, str]]
# d: List[Union[int, str]]
# e: List[int]
# f: List[int]

# def fun(a: List[str]) -> None: ...
```

There is a pretty good chance that I am missing something and this is not an actual issue. If that is the case, my apologies. Thanks :)

**Comment by rchen152** [comment]
This does look like the bug mentioned in the FAQ to me. Since we already have an issue open (https://github.com/google/pytype/issues/365), I'm going to close this one in favor of that one, but thanks for bringing it up - it's helpful for us when we're planning/prioritizing work.

**Comment by CX8** [comment]
Thank you! :D
I will subscribe to (#365).
Is there a roadmap with an indication of the planning/prioritizing of issues work?
