### ISSUE TITLE
Don't crash on recursive type definitions

### ISSUE THREAD

**Issue by wiml** [google/pytype#407]
I've minimized a crashing file down to this:

```python
import typing

JsonValue = typing.Union[None, typing.Sequence['JsonValue'], str]

def lossy_jsonify(value: typing.Any) -> JsonValue:
    # (Body of function removed to minimize test case)
    return "blah"
```

Running Pytype 2019.09.06 on Python 3.7.4, this results in a false "success" report (see issue #285) followed by an infinite recursion in the exception handler, but the first crash recorded in the `.pyi` file is:

```python
# Traceback (most recent call last):
#   File "REDACTED/venv/lib/python3.7/site-packages/pytype/typegraph/cfg.py", line 260, in _FindOrAddOrigin
#     origin = self._cfgnode_to_origin[cfg_node]
# KeyError: <cfgnode 10 5>
```

**Comment by rchen152** [comment]
This is happening because pytype doesn't yet support recursive type aliases. I'm going to mark this as a bug, since even if we don't support this feature yet, we should print a sensible error message instead of crashing.

**Comment by rchen152** [comment]
We now properly report [not-supported-yet] in this case instead of crashing.
