### ISSUE TITLE
Does not handle @attr optional kw args

### ISSUE THREAD

**Issue by wiml** [google/pytype#408]
The `default=...` specification in this attr class means that `arg_encoding` is an optional keyword parameter, but pytype still complains that it is required:

```python
import attr

@attr.s(kw_only=True)
class FooClass:
    path: bytes = attr.ib()
    arg_encoding: str = attr.ib(default='utf-8')
    
def make_me_a_foo(path: bytes) -> FooClass:
    return FooClass(path=path)
```

Running pytype 2019.09.06 on Python 3.7.4 produces this output:

```
pytype-single --imports_info /private/tmp/ptt/foo/bar/.pytype/imports/atty.imports --module-name atty -V 3.7 -o /private/tmp/ptt/foo/bar/.pytype/pyi/atty.pyi --analyze-annotated --nofail --quick /private/tmp/ptt/foo/bar/atty.py
File "/private/tmp/ptt/foo/bar/atty.py", line 9, in make_me_a_foo: Missing parameter 'arg_encoding' in call to function FooClass.__init__ [missing-parameter]
  Expected: (self, *, arg_encoding, path)
  Actually passed: (self, path)
```

(Likewise, the generated `.pyi` file has the declaration `def __init__(self, *, path: bytes, arg_encoding: str) -> None: ...` which is incorrect but matches pytype's behavior.)

**Comment by rchen152** [comment]
Huh. Removing `kw_only=True` seems to fix pytype's behavior, so this is some odd interaction between kw_only and default.
