### ISSUE TITLE
Caught error in pytype: 'str' object has no attribute 'get_instance_type'

### ISSUE THREAD

**Issue by wiml** [google/pytype#409]
When typechecking this file:

```python
from typing import Generic, TypeVar, List

Ti = TypeVar('Ti', 'ClassOne', int)

class StuffSource (Generic[Ti]):
    def getSomeStuff(self) -> List[Ti]:
        return []

class ClassOne:
    pass
```

Running Pytype 2019.09.06 on Python 3.7.4, this results in a false "success" report (see issue #285) but [the generated `.pyi` file](https://github.com/google/pytype/files/3602840/generated-pyi.txt) contains a traceback and the message `Caught error in pytype: 'str' object has no attribute 'get_instance_type'`.

Making `StuffSource` non-generic eliminates the crash, as does defining the type variable with an actual reference to `ClassOne` instead of using a string.

**Comment by rchen152** [comment]
Yeah, that's almost certainly being caused by the forward reference in the definition of `Ti`.

**Comment by rchen152** [comment]
This seems to be fixed! The last two releases contained a number of improvements to forward reference support, so it's likely one of those fixed this issue.
