### ISSUE TITLE
AssertionError in match_Signature_against_Signature

### ISSUE THREAD

**Issue by wiml** [google/pytype#410]
When typechecking this file:

```python
def rearrange_proc_table(val):
    procs = val['procs']
    val['procs'] = dict( (ix, procs[ix]) for ix in range(0, len(procs)) )
    del val['fields']
```

Running Pytype 2019.09.06 on Python 3.7.4, this results in a false "success" report (see issue #285) but [the generated .pyi file](https://github.com/google/pytype/files/3602952/generated-pyi.txt) contains a traceback stemming from an assertion failure:

```
#   File "REDACTED/venv/lib/python3.7/site-packages/pytype/pytd/booleq.py", line 133, in simplify_exprs
#     for e in exprs:
#   File "REDACTED/venv/lib/python3.7/site-packages/pytype/pytd/type_match.py", line 460, in <genexpr>
#     for s in f.signatures)
#   File "REDACTED/venv/lib/python3.7/site-packages/pytype/pytd/type_match.py", line 412, in match_Signature_against_Signature
#     assert not sig1.template
# AssertionError
```

(The minimized code is a little dubious, I suppose, but I assume that any time pytype hits an assertion error it's a bug.)

**Comment by rchen152** [comment]
Thanks for the report! Looks like this is related to https://github.com/google/pytype/issues/58 - I'm able to reproduce the assertion error when running pytype with the `--protocols` flag on the code you provided.
