### ISSUE TITLE
No attribute 'from_bytes' on Type[int] [attribute-error]

### ISSUE THREAD

**Issue by pjz** [google/pytype#413]
I have a call that looks like:
```
i = int.from_bytes(h.digest(), byteorder='big')
```
and it got flagged with
```
No attribute 'from_bytes' on Type[int] [attribute-error]
```
which is clearly wrong since:
```
Python 3.7.4 (default, Sep  3 2019, 12:43:59) 
[GCC 7.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> help(int.from_bytes)
Help on built-in function from_bytes:

from_bytes(bytes, byteorder, *, signed=False) method of builtins.type instance
    Return the integer represented by the given array of bytes.
```

**Comment by rchen152** [comment]
I tried running pytype on:
```
h = __any_object__
i = int.from_bytes(h.digest(), byteorder='big')
```
and didn't see any errors. `from_bytes` is new in Python 3 - is it possible that pytype was running in Python 2 mode? Could you give a bit more information about what the surrounding code looks like?

**Comment by pjz** [comment]
Okay, it did come from mixing versions, but it was because `pytype moduledir/` apparently calls out to `pytype-single ...`, so running pytype in virtualenv directly (eg. doing `/path/to/venv/bin/pytype moduledir/`) doesn't work because the subsequent call to `pytype-single` uses the main path.  

My bad, though it would be nice if `pytype` used `pytype-single` as a library instead of via an exec.

**Comment by rchen152** [comment]
pytype uses [ninja](https://ninja-build.org/) to parallelize the pytype-single calls, so unfortunately, we have to call the binary.
