### ISSUE TITLE
Recursive protocols type inference not working

### ISSUE THREAD

**Issue by mfojtak** [google/pytype#417]
Following code should infer *ten2* type as *Tensor*.
But it only infers *Any*.

```python
import numpy as np
from typing import Protocol


class Tensor(Protocol):
    shape: tuple
    def __add__(self, other) -> "Tensor":
        ...

ten1: Tensor = np.array([1, 2, 3, 4])
ten2 = ten1 + 1
```
Here is the generated pyi:
```python
# (generated with --quick)

from typing import Any, Protocol, TypeVar

np: module
ten1: Tensor
ten2: Any

_TTensor = TypeVar('_TTensor', bound=Tensor)

class Tensor(Protocol):
    shape: tuple
    def __add__(self: _TTensor, other) -> _TTensor: ...
```
If I replace return type of add method with any type other than Tensor, it is inferred fine.

**Comment by rchen152** [comment]
Thanks for the report! That's an odd-looking bug - the addition seems to work correctly if I remove the inheritance from Protocol, so Tensor being a protocol is somehow causing the problem.

**Comment by rchen152** [comment]
This seems to work now - the type of `ten2` is inferred as `Tensor` rather than `Any`.
