### ISSUE TITLE
pytype crashes with syntax error on del statement

### ISSUE THREAD

**Issue by markshannon** [google/pytype#42]
This is causing the typeshed CI to reject the following valid code:
https://github.com/markshannon/typeshed/blob/362bedecd9778196e44d4c88acc39313bb38a6ba/stdlib/2/os/path.pyi

**Comment by matthiaskramm** [comment]
So far, we have put an underscore in front of classes or types that are internal to a module. The advantage is that sometimes you do need to refer to an (internal) class of a module from a different `pyi`.

In the example of `path.pyi`, the internal type is a `Union`. Maybe we just shouldn't export union types from `pyi`, by default? Do we have any use cases where you'd actually want to declare a union in one `pyi`, but use it in another?

**Comment by rchen152** [comment]
Typeshed's convention is still to prefix the names of typing constructs with an underscore; it's unlikely that pytype's parser will ever (intentionally) support `del`.
