### ISSUE TITLE
Pyi error when running on larger codebases -- can't import for ''

### ISSUE THREAD

**Issue by dmccrevan** [google/pytype#428]
### Description
I am trying to run pytype on larger repositories such as scikit-learn. When I run pytype from either the root directory of the repository or any of the sub-directories, I run into an issue where pytype fails and stops because of the following message: `Couldn't import pyi for '' [pyi-error]`

### Example
An example snippet of code where this breaks is here: 
```
from .. import auc
from .. import roc_curve
```
This file is located here: scikit-learn/sklearn/metrics/_plot/roc_curve.py

I have tried to run this within the same directory as the file as well as outside. 
I believe this is a circular dependency issue, but I don't have yet to figure out how to fix this. Is there any way for these issues to be ignored? Or is there some other workaround?

**Comment by rchen152** [comment]
Yeah, circular imports will confuse pytype. Might be related to https://github.com/google/pytype/issues/320 or https://github.com/google/pytype/issues/355. As a workaround, you can add `# pytype: disable=pyi-error` to the ends of the lines that pytype complains about or run pytype with `--disable=pyi-error`. (The latter option can also be saved in a config file: https://github.com/google/pytype#config-file.)

**Comment by rchen152** [comment]
Including repro instructions for posterity:
```
git clone git@github.com:scikit-learn/scikit-learn.git
pip install pytype numpy scipy joblib matplotlib
cd scikit-learn
pytype sklearn/metrics/_plot/roc_curve.py
```

**Comment by dmccrevan** [comment]
> Yeah, circular imports will confuse pytype. Might be related to #320 or #355. As a workaround, you can add `# pytype: disable=pyi-error` to the ends of the lines that pytype complains about or run pytype with `--disable=pyi-error`. (The latter option can also be saved in a config file: https://github.com/google/pytype#config-file.)

Is there a way to disable 2 types of errors (import-error and pyi-error)?

**Comment by dmccrevan** [comment]
@rchen152  Thank you, this fixed my issue!
