### ISSUE TITLE
Python exe can't handle space in path

### ISSUE THREAD

**Issue by CraftSpider** [google/pytype#437]
On Windows, the way pytype calls subprocess in `get_python_exe_version` (In `utils.py`), isn't able to handle a space in the path. So Passing python_exe as `/Program Files/Python36/python.exe` results in an error. The argument to subprocess should be wrapped in double-quotes to handle this case on windows. Alternatively, using a list of arguments instead of a concatenated string means that subprocess will handle the correct escaping per-OS

**Comment by rchen152** [comment]
Thanks for the report! I'll change `python_exe + " -V"` to `[python_exe, "-V"]`, although we don't have support/testing for Windows, so you'll likely run into other issues.
