### ISSUE TITLE
Support Python 3.8

### ISSUE THREAD

**Issue by cjolowicz** [google/pytype#440]
Invoking pytype under Python 3.8 fails with the following error:

```
Python versions > 3.7 are not yet supported.
```

Is there an ETA for Python 3.8 support?

**Comment by kamahen** [comment]
https://bugs.python.org/issue36541 contains a proposed PR to bring lib2to3 up-to-date. But I think pytype also uses another parser?

**Comment by staticdev** [comment]
Any expectations on this one? Starting a new 3.8 project, and deciding if using pytype may be viable in some timeframe.

**Comment by rchen152** [comment]
No progress to report yet, unfortunately. We've run into some unexpected difficulties trying to get internal testing set up for minor version upgrades.

**Comment by ibozhilov** [comment]
I saw that you are working on setting up testing for python 3.8 https://github.com/google/pytype/pull/559. Do you have any update on how much work it will take to support python 3.8.

**Comment by gpshead** [comment]
The opcode changes in Python 3.8:
  https://github.com/python/cpython/commit/520b7ae27e39d1c77ea74ccd1b184d7cb43f9dcb

**Comment by staticdev** [comment]
I am pretty sure @rchen152 make a very nice job at pytype, but this project is just too big for one person. Unfortunately, I had to drop pytype in new projects in favor to mypy and pyre that are more maintained and support latest python. We use type checkers to ensure quality, and projects normally can't wait this long.

**Comment by gpshead** [comment]
Use whatever works for you.  There are several of us interally actively working on pytype where it is used daily on tens of millions of lines of Python code.  We obviously haven't focused a lot on externally usability ease like this as other projects such as mypy have.  pytype's type inferencing is valuable, but only when you can _actually run it_ in your environment.  :)

**Comment by rchen152** [comment]
Apologies for the lack of response. We discussed this at our last team meeting, and @martindemello and @Solumin have gamely volunteered to take a stab at implementing basic 3.8 support when their schedules allow. (New features, such as `typing.TypedDict`, will take longer.)

The problem is that, internally at Google, the need for 3.8 support is still ~months out, which makes it hard to prioritize above other features. We do hope to naturally get better at minor version upgrades as we do more of them, but we're also exploring whether it's feasible to deliver support for new versions externally on an faster timeline - no promises yet, though.

**Comment by kamahen** [comment]
If you need lib2to3-like parser support, I've written up a proposal to replace lib2to3 with an augmented stdlib ast module:
https://mail.python.org/archives/list/python-ideas@python.org/thread/X2HJ6I6XLIGRZDB27HRHIVQC3RXNZAY4/

(No promises that I'll actually do the work, of course)

**Comment by rchen152** [comment]
pytype's functional tests all pass in Python 3.8 now, and we'll start offering Python 3.8 manylinux and macos wheels with the next release.

If you encounter 3.8-specific bugs, please file individual issues for them. I've opened https://github.com/google/pytype/issues/679 (runtime features) and https://github.com/google/pytype/issues/680 (typing features) for the new features that pytype is still missing; please comment on those if you discover a missing feature that I overlooked.

**Comment by jaraco** [comment]
I encountered this error while attempting to install pytype on Python 3.11, which causes installation of `pytype 2020.2.6`. Presumably this issue will occur anytime there is a newer Python without pytype support. Perhaps this project should consider yanking older versions of pytype that don't exclude newer Pythons (and possibly re-release them with the necessary exclusions).
