### ISSUE TITLE
Enum functional API throw error

### ISSUE THREAD

**Issue by erdnaxeli** [google/pytype#459]
Hi,

Consider this code:
```Python
from enum import Enum

class Lol(Enum):
    mdr = 1
    xd = 2

def f(x: Lol):
    return x
```

Pytype founds nothing to complain against.

Now consider the following which use the Enum [functional API](https://docs.python.org/3/library/enum.html#functional-api), and so is equivalent to the previous code:
```Python
from enum import Enum

Lol = Enum('Lol', ('mdr', 'xd'))

def f(x: Lol):
    return x
```

Now pytype complains with the following error:
> File "...", line 5, in <module>: Invalid type annotation '<instance of enum.Enum>' for x [invalid-annotation]
>  Not a type

Tested with pytype 2019.10.17.

**Comment by rchen152** [comment]
Thanks for the report! We had add native support for collections.namedtuple to make the similar namedtuple constructor work, so we'll probably have to do the same for enum.
