### ISSUE TITLE
"AttributeError: module 'time' has no attribute 'clock'" when running pytype in Python 3.8

### ISSUE THREAD

**Issue by OrBin** [google/pytype#466]
I'm trying to run pytype on Python 3.8, with Python 3.7 target code (`-V 3.7`), and encounter the following error:

```
$  pytype --config ./setup.cfg -V 3.7 ./*.py ./gramhopper ./tests
Computing dependencies
Analyzing 44 sources with 0 local dependencies
ninja: Entering directory `/code/python/gramhopper/.pytype'
[1/44] check gramhopper.gramhopper.responses.response_helper
FAILED: /code/python/gramhopper/.pytype/pyi/gramhopper/gramhopper/responses/response_helper.pyi 
pytype-single --disable wrong-keyword-args --imports_info /code/python/gramhopper/.pytype/imports/gramhopper.gramhopper.responses.response_helper.imports --module-name gramhopper.gramhopper.responses.response_helper -V 3.7 -o /code/python/gramhopper/.pytype/pyi/gramhopper/gramhopper/responses/response_helper.pyi --analyze-annotated --nofail --quick /code/python/gramhopper/gramhopper/responses/response_helper.py
Traceback (most recent call last):
  File "/opt/anaconda3/envs/gh_2019_12_03-2/bin/pytype-single", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/envs/gh_2019_12_03-2/lib/python3.8/site-packages/pytype/main.py", line 86, in main
    with metrics.StopWatch("total_time"):
  File "/opt/anaconda3/envs/gh_2019_12_03-2/lib/python3.8/site-packages/pytype/metrics.py", line 154, in __enter__
    self._start_time = time.clock()
AttributeError: module 'time' has no attribute 'clock'
ninja: build stopped: subcommand failed.
```

Python version: 3.8.0
Pytype version: 2019.11.27

I'm aware to the fact that pytype does not yet support analyzing Python 3.8 code (#440), but not that this is an error when running pytype on Python 3.8, not analyzing Python 3.8 code.

This is caused by removing `time.clock()` function in Python 3.8, as warned [here](https://docs.python.org/3.7/library/time.html#time.clock): `Deprecated since version 3.3, will be removed in version 3.8: The behaviour of this function depends on the platform: use perf_counter() or process_time() instead, depending on your requirements, to have a well defined behaviour.`

**Comment by rchen152** [comment]
Hmm, I don't think we've tried running pytype under 3.8 yet. Good to know that this needs fixing - thanks!

**Comment by komuw** [comment]
When runing pytype in python3.8 I get error:

```
Python versions > 3.7 are not yet supported.
```

**Comment by OrBin** [comment]
> When runing pytype in python3.8 I get error:
> 
> ```
> Python versions > 3.7 are not yet supported.
> ```

This error is raised when trying to run pytype with a 3.8 target code. This issue is about what occurs when running pytype with a 3.7 target code, but on Python 3.8.
