### ISSUE TITLE
missing-parameter on a derived dataclass

### ISSUE THREAD

**Issue by OrBin** [google/pytype#469]
When running pytype and having this specific occasion of derived dataclasses, I'm getting a missing-parameter error.

Code (`pytype_example.py`):
```
from dataclasses import dataclass


@dataclass
class Parent:
    name: str
    count: int


@dataclass
class ChildA(Parent):
    def __init__(self, count: int):
        super().__init__(name='A', count=count)


child_a = ChildA(count=3)
print(child_a.name)  # Prints 'A'
```

Running `python pytype_example.py`, it prints `A`.

Running `pytype -V 3.7 pytype_example.py`:
```
Computing dependencies
Analyzing 1 sources with 0 local dependencies
ninja: Entering directory `/home/or/pytype-demo/.pytype'
[1/1] check pytype_example
FAILED: /home/or/pytype-demo/.pytype/pyi/pytype_example.pyi 
pytype-single --imports_info /home/or/pytype-demo/.pytype/imports/pytype_example.imports --module-name pytype_example -V 3.7 -o /home/or/pytype-demo/.pytype/pyi/pytype_example.pyi --analyze-annotated --nofail --quick /home/or/pytype-demo/pytype_example.py
File "/home/or/pytype-demo/pytype_example.py", line 16, in <module>: Missing parameter 'name' in call to function ChildA.__init__ [missing-parameter]
  Expected: (self, name, count)
  Actually passed: (self, count)

For more details, see https://google.github.io/pytype/errors.html#missing-parameter.
ninja: build stopped: subcommand failed.
```

Please note that the child class does provide the `name` parameter when calling the parent's constructor.

Python version: 3.7.5
Pytype version: 2019.11.27

This issue is related to #234, but I'm filing this issue separately [as @rchen152 requested](https://github.com/google/pytype/issues/234#issuecomment-560344542).

**Comment by rchen152** [comment]
This is happening because we're ignoring the custom `__init__` on the dataclass. We already have a pending fix for this internally - hopefully we'll be able to get it exported and released soon.
