### ISSUE TITLE
Don't fail on mypy-style '# type: ignore[code, ...]' comments

### ISSUE THREAD

**Issue by udim** [google/pytype#485]
Currently a comment like `# type: ignore[assignment]` generates the error:
```
Invalid type comment: ignore[assignment] [invalid-type-comment]
  Name 'ignore' is not defined
  Name 'assignment' is not defined
```

I would expect pytype to consider such a comment as a plain `# type: ignore`.

ref: https://mypy.readthedocs.io/en/latest/error_codes.html#silencing-errors-based-on-error-codes

**Comment by rchen152** [comment]
Hmm, I'm not sure if we'll support this mypy-specific feature, since pytype has its own way of silencing errors (https://google.github.io/pytype/user_guide.html#silencing-errors), but at a minimum we can change the `# type: ignore` regex to accept an error code after the ignore.

**Comment by dumblob** [comment]
I'd advocate at least for not reporting it as an error, but a warning - i.e. not hindering execution (i.e. not requiring any code changes).
