### ISSUE TITLE
Confusing error for a correct python snippet

### ISSUE THREAD

**Issue by dumblob** [google/pytype#486]
```
ninja: Entering directory `/home/x/.pytype'
[1/1] check pytypebug00
FAILED: /home/x/.pytype/pyi/pytypebug00.pyi 
/home/x/env00/bin/python3 -m pytype.single --imports_info /home/x/.pytype/imports/pytypebug00.imports --module-name pytypebug00 -V 3.7 -o /home/x/.pytype/pyi/pytypebug00.pyi --analyze-annotated --nofail --quick /home/x/pytypebug00.py
File "/home/x/pytypebug00.py", line 7, in <module>: Invalid type annotation '5' for z [invalid-annotation]
  Not a type

For more details, see https://google.github.io/pytype/errors.html#invalid-annotation.
ninja: build stopped: subcommand failed.
Computing dependencies
Analyzing 1 sources with 0 local dependencies
```
(I'm running pytype from a virtual environment where I installed it using pip)

pytypebug00.py:
```python
class K( dict ):
  pass
x = K()
if True:
  y: int = 9
  # some comment
  x['z'] = 5
```

**Comment by rchen152** [comment]
Wow.

I ran `pytype-single -v4` on this file, which showed the invalid annotation being added during analysis of the STORE_SUBSCR opcode:
```
INFO:pytype.errors:Added error to log: invalid-annotation
File "foo.py", line 7, in <module>: Invalid type annotation '5' for z [invalid-annotation]
  Not a type
```
STORE_SUBSCR calls `_is_annotations_dict` to check whether the dictionary being modified is `__annotations__`. But the latter method contains a bug:
https://github.com/google/pytype/blob/ca2ea4a5f39cd214735cd481c5017a78617810ca/pytype/vm.py#L2055-L2056

That line returns a generator, which always evaluates to `True` :man_facepalming:
Luckily, the fix should be simple.
