### ISSUE TITLE
Support builtins.object

### ISSUE THREAD

**Issue by udim** [google/pytype#488]
The following code generates an error (Python 3.7.5rc1 and 3.6.9):
```py
from builtins import object

class A(object):
  def __init__(self, b):
    pass

A(1)
```
```
File "test.py", line 7, in <module>: Function object.__new__ expects 1 arg(s), got 2 [wrong-arg-count]
  Expected: (cls)
  Actually passed: (cls, _)
```

**Comment by udim** [comment]
From what I understand, `object` and `builtins.object` should be the same object in Python 3.

**Comment by rchen152** [comment]
Yeah, they should be the same thing. Out of curiosity, why do you need to explicitly import `builtins.object`?

**Comment by udim** [comment]
We use https://pypi.org/project/future/ to provide compatible builtins in Py2. Specifically, future.builtins.object provides some function mappings listed here:
https://python-future.org/changelog.html?highlight=object#newobject-base-object-defines-fallback-py2-compatible-special-methods

**Comment by rchen152** [comment]
I see, thanks!

**Comment by rchen152** [comment]
pytype seems happy with this code now (perhaps because we renamed its builtins stubs from `__builtin__.pytd` to `builtins.pytd`).
