### ISSUE TITLE
isinstance confusion on classes that have the Any type

### ISSUE THREAD

**Issue by udim** [google/pytype#491]
This happens, for instance when using a class imported from a module that has `# pytype: skip-file` at the top. The class is considered to have the `Any` type, as in the toy example below:

```py
from typing import Any, Union

class A(object):  # type: Any
  def m(self):
    pass
   
a = 1  # type: Union[int, str, A]
if isinstance(a, A):
  a.m()
```
Running pytype on this gives the errors:
```
File "test2.py", line 9, in <module>: No attribute 'm' on str [attribute-error]
  In Union[Any, int, str]
File "test2.py", line 9, in <module>: No attribute 'm' on int [attribute-error]
  In Union[Any, int, str]
```

**Comment by rchen152** [comment]
Oh I see =(
The isinstance check allows the entire union because A is Any, so then the attribute check is done on `int` and `str`.

**Comment by rchen152** [comment]
Revisiting this, unfortunately I don't think it's possible to fix this. If a file contains `# pytype: skip-file`, then all types are treated as Any, so there's no way to distinguish between, e.g., `A = int` and `class A: ...`, so we don't know if an int or a str can satisfy `isinstance(..., A)`.
