### ISSUE TITLE
pytype can't parse hex literals

### ISSUE THREAD

**Issue by CraftSpider** [google/pytype#494]
The following code causes the error `ParseError: syntax error, unexpected NAME, expecting ']'`:

```py
from typing import Literal

a: Literal[0x00ff]
```

**Comment by rchen152** [comment]
I think we need to expand our definition of NUMBER here: https://github.com/google/pytype/blob/ce086c5c6ef55364dac96a3c1e97a4a21b1aefeb/pytype/pyi/lexer.lex#L117.

**Comment by kamahen** [comment]
Is [py3_test_grammar.py](https://github.com/python/cpython/blob/master/Lib/lib2to3/tests/data/py3_test_grammar.py) part of your test suite? It has hex numbers.
