### ISSUE TITLE
utcoffset error

### ISSUE THREAD

**Issue by minusf** [google/pytype#503]
i am very new to type annotation and just learning about it. if i understand the tool's purpose correctly, this should have passed?

```
$ python3 -V
Python 3.7.6
$ pytype --version
2020.01.24
$ cat t.py
from datetime import datetime
print(datetime.now().astimezone().utcoffset().seconds)

$ python3 t.py
3600

$ pytype t.py
Computing dependencies
Analyzing 1 sources with 0 local dependencies
ninja: Entering directory `src/.pytype'
[1/1] check t
FAILED: src/.pytype/pyi/t.pyi
python3 -m pytype.single --imports_info src/.pytype/imports/t.imports
--module-name t -V 3.7 -o src/.pytype/pyi/t.pyi --analyze-annotated
--nofail --quick src/t.py
File "src/t.py", line 3, in <module>: No attribute 'seconds' on None [attribute-error]
  In Optional[datetime.timedelta]

For more details, see https://google.github.io/pytype/errors.html#attribute-error.
ninja: build stopped: subcommand failed.

**Comment by rchen152** [comment]
This looks like a bug in typeshed. (typeshed is a shared repository of type information that a number of Python type checkers use.) typeshed models `utcoffset` as possibly returning `None` [1]. This matches the documentation, which says: "`datetime.utcoffset()`: If `tzinfo` is `None`, returns `None`" [2]. However, the documentation also says that `astimezone` without any arguments sets `tzinfo` to the system local timezone, so it cannot be `None` in this case [3].

I'm not sure how to fix this (maybe by making datetime.datetime generic in the type of the `tzinfo` attribute?), but feel free to open an issue against typeshed - one of the other maintainers might have a better idea of what to do.

To silence the pytype error, you can use `typing.cast` to tell pytype the right type:
```
from typing import cast
cast(datetime.timedelta, datetime.now().astimezone().utcoffset()).seconds
```

[1] https://github.com/python/typeshed/blob/47409f3e254afc69bbff902fe490f00e44400fd0/stdlib/2and3/datetime.pyi#L295
[2] https://docs.python.org/3.5/library/datetime.html#datetime.datetime.utcoffset
[3] https://docs.python.org/3.5/library/datetime.html#datetime.datetime.astimezone
