### ISSUE TITLE
module-attr errors on name collisions

### ISSUE THREAD

**Issue by orsinium** [google/pytype#505]
We have `project/redis.py` module that has `import redis` directive. And pytype produces `module-attr error` for every symbol from `redis`:

```
File "/.../project/redis.py", line 67, in do_something: No attribute 'Redis' on module 'redis' [module-attr]
```

Similar on #198 but about name collision with third-party packages.

**Comment by rchen152** [comment]
Assigning to me for triage.

**Comment by orsinium** [comment]
I can't make a minimal reproducible example from zero. I'll try to reduce the project where it happened to make an example from it.

**Comment by rchen152** [comment]
Thanks, let me know when you have a repro. Alternatively, if you have a link to the project and the command you ran to get the error, I can take a look at that.

**Comment by orsinium** [comment]
Cannot make a reproducible example, and reducing the existing codebase to a suitable example is too hard to done. I'll reopen the issue if I could handle it. Thank you.
