### ISSUE TITLE
Pytype seems get wrong builtins range definition

### ISSUE THREAD

**Issue by bbtfr** [google/pytype#513]
```
# test.py
r = range(100)
r.start
r[:]
```

```
$ python3 --version
Python 3.6.8
$ pytype --version
2020.02.06

$ pytype test.py
Computing dependencies
Analyzing 1 sources with 0 local dependencies
ninja: Entering directory `/home/[===]/.pytype'
[1/1] check test
FAILED: /home/[===]/.pytype/pyi/test.pyi
/usr/bin/python3 -m pytype.single --imports_info /home/[===]/.pytype/imports/test.imports --module-name test -V 3.6 -o /home/[===]/.pytype/pyi/test.pyi --analyze-annotated --nofail --quick /home/[===]/test.py
File "/home/[===]/test.py", line 2, in <module>: No attribute 'start' on range [attribute-error]
File "/home/[===]/test.py", line 3, in <module>: unsupported operand type(s) for item retrieval: 'range' and 'slice' [unsupported-operands]
  Function __getitem__ on range expects int

For more details, see https://google.github.io/pytype/errors.html.
ninja: build stopped: subcommand failed.
```

while I found

https://github.com/python/typeshed/blob/d5851eca6f448b648e1a7b3f3010cc3dde498535/stdlib/2and3/builtins.pyi#L1084-L1102

**Comment by rchen152** [comment]
We have our own builtin definitions because we model some of them a little differently from other type checkers. Indeed, `__getitem__(slice)` is missing: https://github.com/google/pytype/blob/07640ec06bf0c21406ba283b3410be00ba8bc221/pytype/pytd/builtins/3/builtins.pytd#L918. I'll go ahead and add it.

**Comment by bbtfr** [comment]
Thanks for the response, do you think 

```
        start: int
        stop: int
        step: int
```

should also be added? Since they are not starting with underscores

**Comment by vuryleo** [comment]
Hi, regards `start`, `stop` and `step`, is there a pointer to the mr?

**Comment by rchen152** [comment]
Oh, sorry, I already added the attributes but forgot to push the change to GitHub. I'll do that now.
