### ISSUE TITLE
ninja: error: build.ninja:7: expected build command name

### ISSUE THREAD

**Issue by Eshan-Agarwal** [google/pytype#522]
Got error when using` pytype kaggle.py` on windows

> Computing dependencies
Analyzing 1 sources with 0 local dependencies
ninja: error: build.ninja:7: expected build command name
build C:\Users\eshan\Desktop\Tensoflow\Tfds\datasets\tensorflow_datasets...
        ^ near here
ninja: Entering directory `C:\Users\eshan\Desktop\Tensoflow\Tfds\datasets\tensorflow_datasets\core\download\.pytype'

**Comment by Eshan-Agarwal** [comment]
Actually I recently know pytype not support windows so I install WSL can anyone help me with that how can i run pytype using wsl

**Comment by kamahen** [comment]
What problem are you having with running pytype under WSL? It works for me. (I had to install a few other things and add `export PATH="$PATH:$HOME/.local/bin"`).

If you're using the Ubuntu 16.0.4 version of WSL, I recommend upgrading to 18.0.4 ... this might require uninstalling and reinstalling WSL. There's a newer version of WSL with apparently better performance, but it requires a "developer" version of Windows, which is too unstable for me, so I haven't tried it.

**Comment by Eshan-Agarwal** [comment]
I am using ubuntu 18.04 lts for wsl and install python 3.6 Now when I doing `pip install pytype` it gives me this :

> Collecting pytype
  Using cached https://files.pythonhosted.org/packages/75/7c/eeca09a23b347b2fd12f0965714e62c1ff900f7e7436fb488972f1133389/pytype-2020.2.20.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/pytype.egg-info
    writing requirements to pip-egg-info/pytype.egg-info/requires.txt
    writing pip-egg-info/pytype.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/pytype.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/pytype.egg-info/dependency_links.txt
    writing entry points to pip-egg-info/pytype.egg-info/entry_points.txt
    writing manifest file 'pip-egg-info/pytype.egg-info/SOURCES.txt'
    error: package directory 'find:' does not exist

**Comment by Eshan-Agarwal** [comment]
I successfully installed pytype actually after installing wheel and setuptools. So closing this issue. Thanks

**Comment by Eshan-Agarwal** [comment]
Got another problem I sucessfully install pytype but when I was running `pytype kaggle.py` it says :

> Command 'pytype' not found, did you mean:

  command 'pktype' from deb texlive-binaries

Try: sudo apt install <deb name>
