### ISSUE TITLE
Empty Protocol fails with wrong-arg-types

### ISSUE THREAD

**Issue by hatal175** [google/pytype#523]
Running on python 3.6, the following code fails on pytype and passes on mypy.

```
from typing_extensions import Protocol
class Concrete:
    pass
    
class MyProtocol(Protocol):
    pass        

def ff(x: MyProtocol) -> None:
    pass

ff(Concrete())
```

**Comment by rchen152** [comment]
Good catch. The problem is that `Class.is_protocol` is checking for the existence of protocol methods: https://github.com/google/pytype/blob/348b45fcfa0d169861eae6357d70e411210c3373/pytype/mixin.py#L267-L269.
