### ISSUE TITLE
Support non-method attributes in Protocols

### ISSUE THREAD

**Issue by hatal175** [google/pytype#524]
Running on python3.6 the following code seems to fail without any informative message while passing on mypy. I would expect the same message I see when a method is missing.

```
from typing_extensions import Protocol
class Concrete:
    a: str
    
class MyProtocol(Protocol):
    a: str

def ff(x: MyProtocol) -> None:
    pass

ff(Concrete())
```

**Comment by rchen152** [comment]
We haven't added support for non-method attributes in protocols yet.

**Comment by rchen152** [comment]
This will be fixed in the next release.
