### ISSUE TITLE
How to run pytype in WSL

### ISSUE THREAD

**Issue by Eshan-Agarwal** [google/pytype#525]
After sucessfully install pytype, when I was running pytype kaggle.py it says :

> Command 'pytype' not found, did you mean:
  command 'pktype' from deb texlive-binaries
Try: sudo apt install <deb name>

**Comment by Eshan-Agarwal** [comment]
Hey found my error so closing this issue

**Comment by rchen152** [comment]
Glad to hear you figured it out!

**Comment by martindemello** [comment]
could you add what the problem was to this bug, in case someone else with the same issue finds it by googling?

**Comment by Eshan-Agarwal** [comment]
Actually If you want to run pytype in windows then you have to enable `WSL` on your windows refer [here](https://www.windowscentral.com/install-windows-subsystem-linux-windows-10) after that just download ubuntu from app store as mentioned in above link. And after that run bash.exe and install some tools before installing `pytype `: `pip install wheel` and  `pip install setuptools` then `pip install pytype` after that you can use `pytype `using wsl.
