### ISSUE TITLE
No _SupportsIndex in module __builtin__

### ISSUE THREAD

**Issue by CraftSpider** [google/pytype#526]
As in the title. Full error is:
`pytype.load_pytd.BadDependencyError: No _SupportsIndex in module __builtin__, referenced from 'builtins'`

\_\_builtin\_\_.pytd doesn't have a _SupportsIndex class, unlike typeshed's builtins.pyi

**Comment by CraftSpider** [comment]
Error is actually windows-specific I think, I made a mistake with my analysis. I can close this if desired (as windows isn't fully supported), or leave it open

**Comment by CraftSpider** [comment]
Further context: _SupportsIndex doesn't exist in the real builtins, but is a private typeshed 'lie' used for numeric types

**Comment by rchen152** [comment]
pytype has its own builtins definitions (https://github.com/google/pytype/tree/master/pytype/pytd/builtins), so it shouldn't be using (or checking, I think?) typeshed's builtins.

**Comment by CraftSpider** [comment]
Nevermind, this is on typeshed's end. I did some further looking into it, and the way typeshed blacklists paths is not OS-independent.
