### ISSUE TITLE
Deduction error on the type of async function

### ISSUE THREAD

**Issue by ZHmao** [google/pytype#527]
We have two example codes, they show the `pytype` unable to express async function correctly.

### 1 When check it with pytype, it will show this error:
```
Function bar was called with the wrong arguments [wrong-arg-types]
       Expected: (fun: Callable[[str], Awaitable[str]]) 
Actually passed: (fun: Callable[[str], str])
```

```
from typing import Callable, Awaitable


async def foo(a: str) -> str:
    return a


async def bar(fun: Callable[[str], Awaitable[str]]) -> str:
    return await fun('a')


async def go() -> None:
    await bar(foo)

```

We have tried with `Union` and `Any`, both of them can help us ignore this error.

### 2 This one, used `Union`, but another error happened:
```
in bar: bad option in return type [bad-return-type]
           Expected: Awaitable
  Actually returned: str
```

```
from typing import Callable, Awaitable, Union


async def foo(a: str) -> str:
    return a


class Bar:

    def __init__(self, fun: Callable[[str], Union[Awaitable[str], str]]) -> None:
        self.fun = fun

    async def bar(self) -> str:
        return await self.fun('a')


async def go() -> None:
    Bar(foo)
```

We have tried with `Any`, it worked.

**Comment by rchen152** [comment]
Thanks for the report. This happens because pytype treats `foo` as having type `Callable[[str], str]`, when it should be wrapping the return type in `Awaitable`.

**Comment by makkesi** [comment]
Is there any updates on fixing this issue? The workaround of using Any is not nice due really wanting to enforce strict as possible typing and also f.e. IDEs (like VS code) work much nicer when the typing is really correct.
