### ISSUE TITLE
Incorrect ParseError for type comment in unexpected location

### ISSUE THREAD

**Issue by JelleZijlstra** [google/pytype#53]
From https://travis-ci.org/python/typeshed/jobs/212532837:

```
Running pytype tests...
pytd error processing "stdlib/2and3/cgi.pyi":
  File: "stdlib/2and3/cgi.pyi", line 107
    def values(self, key: Any) -> Any: ...  # type: ignore
                                            ^
ParseError: syntax error, unexpected TYPECOMMENT, expecting DEF or '@'
```

Type comments should be allowed here.

**Comment by matthiaskramm** [comment]
You need that for disabling mypy's check for methods being compatible with their superclass's methods?

Maybe we need a `# mypy: ignore`, after all. See https://github.com/python/typed_ast/pull/14

**Comment by gvanrossum** [comment]
Only `# type: ignore` should be allowed virtually anywhere. Type comments expressing types are only allowed in specific places (though the spec is probably a bit vague -- IIRC typed_ast just picked a set of rules that are good enough).

But I'm also fine with just working around this in typeshed by moving the `...` to the next line.

**Comment by JelleZijlstra** [comment]
Moving `...` to the next line still generates a parse error in pytype.

**Comment by gvanrossum** [comment]
Oh, that's unfortunate. But I do think that this is not just a mypy-specific thing. Liskov substitutability is taken pretty seriously by PEP 484. (It's the reason we have to declare variance.)

**Comment by matthiaskramm** [comment]
Fair enough. We'll add `#type: ignore` after function signatures to the pytype parser.

**Comment by matthiaskramm** [comment]
Fix pushed.
