### ISSUE TITLE
Any recommendations for running pytype with a linter?

### ISSUE THREAD

**Issue by LucasLLC** [google/pytype#531]
I've been doing some research on pytype and I'm trying to understand the relationship between pytype with, say, pylint. 

As far as I can tell, pytype is not a replacement for a linter, and most comments say to use both. With that being said, does pytype have any opinions or recommendations for running alongside a linter? Especially helpful would be any tips on including pytype in CICD.

**Comment by rchen152** [comment]
My opinion would also be to use both. There's some overlap between the types of issues they catch (e.g., both pylint and pytype will flag name errors), but a linter will also warn about style issues, and pytype can do more in-depth analysis to catch type errors that a linter would likely miss (for example, defining a method in one module and calling it with the wrong arguments in another).

Here's an example of a Travis configuration set up to run both pylint and pytype: https://github.com/google/python-fire/blob/master/.travis.yml. The two don't really interact with each other, so you can drop in your linter of choice. For example, here's a personal project in which I use flake8 and pytype: https://github.com/rchen152/maze/blob/master/.travis.yml. Both of these projects have pytype options defined in their `setup.cfg` file so they can run `pytype` without any arguments.

**Comment by rchen152** [comment]
I'm going to go ahead and close this, but feel free to reopen if your question wasn't fully addressed.

**Comment by LucasLLC** [comment]
Excellent feedback! Thank you so much!
