### ISSUE TITLE
pytype cannot analyze Python 3: invalid syntax [python-compiler-error]

### ISSUE THREAD

**Issue by ovidiugabriel** [google/pytype#54]
I was running the following command with Python 2.7.5
>> $ pytype hello.py 
File "hello.py", line 33: invalid syntax [python-compiler-error]

This is the line where the error happens:

```python
def bold(text : str) -> str:
```

But this is exactly as specified in [PEP 484 ](https://www.python.org/dev/peps/pep-0484/), for example:
```python
def greeting(name: str) -> str:
    return 'Hello ' + name
```
So I think pytype does not work yet with PEP 484.

**Comment by ovidiugabriel** [comment]
With Python 3.3.2 it doesn't work either.

>> $ python3 /usr/bin/pytype hello.py 
  File "/usr/bin/pytype", line 147
    raise type(e), type(e)(message), sys.exc_info()[2]
                 ^
SyntaxError: invalid syntax

**Comment by matthiaskramm** [comment]
For Python 3, the command line should be

```
pytype -V 3.4 file.py
```

(For Python 2, you need a patched python interpreter. See https://github.com/google/pytype/blob/master/pytype/patches/python_2_7_type_annotations.diff)

**Comment by ovidiugabriel** [comment]
Yes, it didn't worked with `/usr/local/bin/python3.4  /usr/bin/pytype -V 3.4 hello.py `
But it worked with `/usr/bin/python2.7 /usr/bin/pytype -V 3.4 hello.py`

Thanks!
