### ISSUE TITLE
Typing failure when assigning function from other modules to method

### ISSUE THREAD

**Issue by brunokim** [google/pytype#548]
When assigning a method to a 'generic' function defined in other package, it may have been assigned an inferred type that clashes with its new usage (see MWE below).

This looks like a difficult problem to solve, what's a recommended way to typecheck this code?

### file1.py
```
def add_to(self, x: int) -> int
  return self.value + x


class MyInt1:
  def __init__(self, value: int):
    self.value = value

  add = add_to


if __name__ == '__main__':
  print(MyInt1(40).add(2))
```

### file2.py
```
from file1 import add_to

class MyInt2:
  def __init__(self, value: int):
    self.value = value

  add = add_to


if __name__ == '__main__':
  print(MyInt2(40).add(2))
```

### Pytype execution

```
$ pytype file1.py file2.py
File "/home/bkim/Projects/mwe/file2.py", line 12, in <module>: Missing parameter 'x' in call to function file1.add_to [missing-parameter]
         Expected: (self, x)
  Actually passed: (self)
```

### file1.pyi

```
# (generated with --quick)

class MyInt1:
    value: int
    def __init__(self, value: int) -> None: ...
    def add(self, x: int) -> int: ...

def add_to(self: MyInt1, x: int) -> int: ...
```

### file2.pyi

```
# (generated with --quick)

import file1
    
class MyInt2:
    value: int
    def __init__(self, value: int) -> None: ...
    def add(self: file1.MyInt1, x: int) -> int: ...

def add_to(self: file1.MyInt1, x: int) -> int: ...
```

**Comment by rchen152** [comment]
Huh, that's a corner case I haven't considered before. As a workaround, you could try casting MyInt2.add to a Callable?
```
from typing import Callable, cast
class MyInt2:
  add = cast(Callable[[int], int], add_to)
```

**Comment by brunokim** [comment]
The workaround works, though it is odd-looking and requires an explaining comment.

Better to simply use `def add(self, x): return add_to(self, x)`. This way, the `self` arg of `add_to` is unnanotated in file2.pyi

**Comment by rchen152** [comment]
That's definitely better!

**Comment by rchen152** [comment]
I'm going to close this issue, as (1) the use case is unusual, and (2) the last suggested workaround seems satisfactory to me. (As an aside, if I saw this in a code review, I'd probably suggest just making MyInt2 inherit from MyInt1.)
