### ISSUE TITLE
merge-pyi feature request: do not annotate builtin functions

### ISSUE THREAD

**Issue by brunokim** [google/pytype#550]
After using merge-pyi, the code base is littered with new annotations to `__str__`, `__eq__`, `__hash__` etc., which I don't bother annotating because they have well known data types. Would it be possible to not annotate these methods, when they match the expected builtin types?

**Comment by rchen152** [comment]
I think we could skip methods that start and end with `__` by adding a check here: https://github.com/google/pytype/blob/51bcd3a2d7be9db0af39a64074cd5ea4917eee4c/pytype/tools/merge_pyi/merge_pyi.py#L628

**Comment by souravbadami** [comment]
@rchen152 - I would like to work on this.

**Comment by rchen152** [comment]
@souravbadami Sure, we'd love the help! Let me know if you have any questions.

**Comment by souravbadami** [comment]
@rchen152 - Can you share a sample where builtins are annotated?

**Comment by brunokim** [comment]
@souravbadami I'm thinking about the builtin special functions, as defined [here](https://github.com/google/pytype/blob/master/pytype/pytd/builtins/3/builtins.pytd#L152).

So this example...

```
class MyInt:
  def __init__(self, value: int):
    self.value = value

  def get_value(self):
    return self.value

  def __repr__(self):
    return f"MyInt(value={self.value})"
```

...receives an annotation for `get_value` and `__repr__` in the pyi file...

```
class MyInt:
  value: int
  def __init__(self, value: int) -> None: ...
  def __repr__(self) -> str: ...
  def get_value(self) -> int: ...
```

...but only `get_value`'s annotation should be merged back by merge-pyi:

```
class MyInt:
  def __init__(self, value: int):
    self.value = value

  def get_value(self) -> int:
    return self.value

  def __repr__(self):  # str return type is well-known, no need to annotate
    return f"MyInt(value={self.value})"
```

**Comment by martindemello** [comment]
i agree with @rchen152 - it should be enough to check the function name for `name.startswith("__") and name is not "__init__"`

**Comment by kamahen** [comment]
I think that not annotating builtins should be an option. I like *everything* to be annotated, because I'm too lazy to look for over-ridden methods -- also it would be nice if mypy or pylint or pytype complained if an override changes the type signature.
