### ISSUE TITLE
Does pytype support deferred typing imports?

### ISSUE THREAD

**Issue by bsolomon1124** [google/pytype#551]
We have a Python 2 runtime environment where `typing` is not available at module runtime (only in CI/CD, if need be).

`mypy` supports deferred typing imports which are ideal for this situation:

Example:

```python
if False:
    from typing import Dict

def foo():
    # type: () -> Dict[str, int]
    return {"a": 1}
```

`mypy` is OK with this and will type-check `foo`, and `flake` also supports it: https://github.com/PyCQA/pyflakes/issues/501.  (That is, flake8 will not give a NameError for Dict.)

Does pytype offer this same functionality or a workaround way to achieve it?

**Comment by rchen152** [comment]
`if False` doesn't work because pytype assumes that branch is unreachable. However, you can hide the literal `False` value from pytype by doing something like:
```
TYPE_CHECKING = False  # type: bool
if TYPE_CHECKING:
    from typing import List
def f(x):
    # type: (List[int]) -> None
    pass
```
In my testing, this toy example appears to work with all of pytype, mypy, and flake8.

**Comment by bsolomon1124** [comment]
Works well, thanks @rchen152. I noticed that the `# type: bool` annotation comment is required here.
