### ISSUE TITLE
sqlalchemy stubs support

### ISSUE THREAD

**Issue by ohadraz** [google/pytype#578]
pytype generate a stub with the general type `Any` for sqlalchemy models and properties.

For example, a code as follows:

**/proj/common/model/MyModel.py**:
```
Base = declarative_base()

class MyModel(Base):
   __tablename__ = "my_table"

    id = Column(Integer, primary_key=True, autoincrement=True)
    my_data = Column(String(64),  nullable=True)
```
**/proj/services/some_path/MyObj.py**:
```
class MyObj:
   def __init__(self, db_session):
      self._db_session = db_session

   def create_my_model(self, data):
      my_model = MyModel(my_data=data)

      self._db_session.add(my_model)
      self._db_session.flush()

      return my_model.id

   def get_by_id(self, id):
      return self._db_session.query(MyModel).filter(MyModel.id == id).one()
```
Running pytype:
```
cd /proj
pytype services/some_path/
```
generates a `pyi` as follows:
```
import __future__
from typing import Any
...

class MyObj(Any):
    def __init__(self, db_session) -> None: ...
    def create_my_model(self, data) -> Any: ...
    def get_by_id(self, id) -> Any: ...
```
The expected `pyi` is:
```
...
class MyObj(Any):
    def __init__(self, db_session) -> None
    def create_my_model(self, data) -> int
    def get_by_id(self, id) -> MyModel
```

**Comment by rchen152** [comment]
Could you also include the import statements for your sample code? For example, I don't know where `declarative_base`, `Column`, etc., in `MyModel.py` come from, so I can't tell what the inferred types should be.

**Comment by iamareebjamal** [comment]
```python
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String
```

More info here - https://docs.sqlalchemy.org/en/14/orm/tutorial.html

However, please note that these result as int, str on actual object. For eg, `MyModel(my_data=data).id` will be int, and not `sqlalchemy.Integer`

**Comment by rchen152** [comment]
Thanks for the additional information. pytype only infers types for local code, so it makes sense that objects imported directly from `sqlalchemy` are typed as `Any`. To produce better types, we'd need to add type stubs and possibly an overlay for this library. Looks like mypy has a plugin for sqlalchemy (https://github.com/dropbox/sqlalchemy-stubs).

**Comment by rchen152** [comment]
typeshed now has sqlalchemy stubs, so we should try to use those: https://github.com/python/typeshed/tree/master/stubs/SQLAlchemy. Unfortunately, pytype can't parse them yet: https://github.com/google/pytype/issues/1087 ^^;
Closing this issue in favor of the more specific one for parsing the typeshed stubs.
