### ISSUE TITLE
False positive due to ignored None check

### ISSUE THREAD

**Issue by yugr** [google/pytype#581]
_Sorry if that's a known issue._

This code:
```
import sys, re

def error_if(cond):
    if cond:
        sys.exit(1)

def foo(s):
    m = re.search(r'(1)', s)
    error_if(m is None)
    return m.group(1)
```
fails under pytype 2020.4.22 with
```
No attribute 'group' on None [attribute-error]
```
It looks like the None check in `error_if` is ignored.

**Comment by rchen152** [comment]
I'm unfortunately unsurprised that pytype didn't handle this properly, since it requires preserving the `m is None` condition across function boundaries. I wonder if adding overload signatures for error_if using Literal would help (once we support Literal...).

**Comment by rchen152** [comment]
Revisiting this, I still don't think this is something that pytype is likely to be able to handle. However, you may be able to achieve the same effect with a method that filters out None:

```
import sys, re

from typing import Optional, TypeVar
T = TypeVar('T')

def error_if(val: Optional[T]) -> T:
  if val is None:
    sys.exit(1)
  return val

def foo(s):
    m = re.search(r'(1)', s)
    m = error_if(m)
    return m.group(1)
```
