### ISSUE TITLE
Dumping inferred type annotations

### ISSUE THREAD

**Issue by sridhargopinath** [google/pytype#583]
Hi,

I am trying to use pytype to infer type annotations to an unannotated Python function. Is there a way to dump the inferred type into a readable file?

Example of a simple function:
```Python
def foo(l1, l2):
    result = 0
    a1, a2 = len(l1), len(l2)
    for i in range(max(a1, a2)):
        if i < a1:
            result += l1[i]
        if i < a2:
            result += l2[i]
    return result
```
If pytyper infers the types of `l1` and `l2` as `List[Int]`, is there a way to extract this information?

**Comment by rchen152** [comment]
Hi! Unfortunately, pytype doesn't infer the types of function parameters yet. You can use the experimental `--protocols` flag to turn on parameter inference, but the results can be questionable. (For example, here it infers the types of `l1` and `l2` as `Union[Sized, Mapping[int, Any]]`.)

In general, inferred types will be in pytype's generated type stubs. For example, if your code was in a file called `foo.py` and you ran `pytype foo.py`, the type stub would be located at `.pytype/pyi/foo.pyi`.
