### ISSUE TITLE
pytype ignores bad-return-type error for matplotlib class

### ISSUE THREAD

**Issue by tekumara** [google/pytype#601]
The following produces no errors in pytype:
```
from matplotlib.axes import SubplotBase

def bad_func(input: str) -> SubplotBase:
    return input
```

I was expecting a `bad-return-type` error. PyCharm does recognise this as an error.

**Comment by martindemello** [comment]
pytype could not determine any type information for matplotlib (there were no stubs in typeshed, and matplotlib itself was imported as a "system" file, and so treated as though every method was just `f(*args) -> Any`.

you can see it in the `pytype -v 2` output:
```
INFO generate default: System module matplotlib.axes.__init__
```

unfortunately there's no real fix for this other than checking out the matplotlib source tree and then adding it to your pythonpath when running pytype.

**Comment by tekumara** [comment]
Thanks @martindemello for clarifying the log line, that was not obvious to me!

I've discovered [data-science-types](https://pypi.org/project/data-science-types/). pip installing them allows mypy to identify the type error. Is there a way to get pytype to use these third-party stubs?
