### ISSUE TITLE
Incorrect type if func name is same as module name

### ISSUE THREAD

**Issue by lorien** [google/pytype#603]
Repo to reproduce the problem: https://github.com/lorien/pytype-bug

Run: `pytype test.py`

You get:
```
...
/usr/bin/python3 -m pytype.single --imports_info /home/lorien/web/pytype-bug/.pytype/imports/test.imports --module-name test -V 3.7 -o /home/lorien/web/pytype-bug/.pytype/pyi/test.pyi --analyze-annotated --nofail --quick /home/lorien/web/pytype-bug/test.py
File "/home/lorien/web/pytype-bug/test.py", line 2, in <module>: module [reveal-type]
...
```

But `reuqest` is not a module. It is a function.

**Comment by rchen152** [comment]
Thanks for the report! This looks like https://github.com/google/pytype/issues/264, so I'm going to close this issue in favor of that one. A possible workaround is to do `import some_mod; some_mod.request` instead of `from some_mod import request`.
