### ISSUE TITLE
New Release for fixes required for typeshed's Big Reformat?

### ISSUE THREAD

**Issue by srittau** [google/pytype#608]
Is it possible to cut a new release that incorporates the fixes to pytype's parser required for typeshed's Big Reformat? See python/typeshed#4224 for details.

**Comment by rchen152** [comment]
Ah sorry, this slipped my mind. I'll try to get a release out today.

**Comment by rchen152** [comment]
Ok, pytype 2020.06.26 is out. I checked that it can successfully analyze all of the files in typeshed/stdlib after running black on them and that it's also happy with the changes in https://github.com/python/typeshed/pull/4224/commits/a6d73ac7c6a7417d9ce8b430f1592c5e521d5e95 (applied to the master branch).
