### ISSUE TITLE
typeshed fails on builtin

### ISSUE THREAD

**Issue by michaelmerwitz** [google/pytype#61]
=> pytype --pythonpath=. settings.py -o settings.pyi
File "settings.py", line 27, in <module>: Couldn't import pyi for 'logging' [pyi-error]
    File: "/Library/Python/2.7/site-packages/pytype/typeshed/stdlib/2/types.pyi", line 22
      StringTypes = (StringType, UnicodeType)

**Comment by matthiaskramm** [comment]
Thanks for reporting this. Seems we needed a typeshed upgrade.
