### ISSUE TITLE
Unindented comment inside class confuses parser

### ISSUE THREAD

**Issue by srittau** [google/pytype#610]
Please consider the following stub file:

```python
class Foo:
    y: int
# comment
    x: int
```

This confuses pytype's parser (2020.06.01):

```
third_party/3/test2/__init__.pyi: ParseError: syntax error, unexpected INDENT, expecting DEF
```

A non-critical issue for me, discovered during debugging.

**Comment by rchen152** [comment]
O_o
I'm a little surprised this works, but I just tried it out in an interpreter, and apparently you indeed can have unindented comments.

**Comment by Gouravsingh21** [comment]
Sir I want to contribute to this  repo.

**Comment by rchen152** [comment]
Realistically, we're not going to get around to fixing this before the current pyi parser is retired (and the new one is typed_ast-based, so it shouldn't have this problem).
