### ISSUE TITLE
Inner class can't be used as type

### ISSUE THREAD

**Issue by srittau** [google/pytype#611]
Please consider the following stub file:

```python
class Foo:
    bar: Bar 
    class Bar: ...
```

pytype 2020.06.01 complains:

```python
third_party/3/test2/__init__.pyi: pytype.pytd.visitors.SymbolLookupError: Couldn't find Bar in test2
```

As stub files should generally be considered to be using `from __future__ import annotations`, I believe this should work. (mypy accepts it also.) Easily worked around, so just a minor issue.

**Comment by srittau** [comment]
Actually, this is not related to order. Even if `Bar` is defined before `bar`, it fails. Using `Foo.Bar` to reference it seems to work.

**Comment by rchen152** [comment]
Ah, I vaguely recall dealing with this a couple years ago when I was trying to figure out how to handle nested classes. I don't remember anymore why I could only get things working with the fully qualified name, but it might be time to take another look.

**Comment by martindemello** [comment]
this works now, after @rchen152's work on inner class support.
