### ISSUE TITLE
TypedDict and total=false

### ISSUE THREAD

**Issue by srittau** [google/pytype#613]
This came up in python/typeshed#4276: It seems that pytype doesn't allow `TypedDict`s that use `total=False`. It will complain "Only 'metaclass' allowed as classdef kwarg". We will work around this by adding nmap.nmap to the blacklist for now,

**Comment by rchen152** [comment]
Agh. Well, at least this one should be easy to fix, since it's an error in postprocessing rather than the parser itself: https://github.com/google/pytype/blob/e9ff94330c567703a6281671607f85c7b35a65ee/pytype/pyi/parser.py#L1126.

**Comment by rchen152** [comment]
This issue should be fixed by today's release.
