### ISSUE TITLE
Python 3.8: Pytype fails when returning tuple or list within a contextmanager scope

### ISSUE THREAD

**Issue by lgeiger** [google/pytype#617]
Pytype v2020.06.26 will not accept the following code in Python 3.8 (Python 3.7 didn't throw errors here).
```python
import contextlib

def foo():
    with contextlib.nullcontext():
        return [1, 2]  # 'list' object is not callable [not-callable]

def bar():
    x, y  = 1, 3
    with contextlib.nullcontext():
        return x, y  # 'tuple' object is not callable [not-callable]
```
This is not specific to `contextlib.nullcontext()` but happens with other contextmanagers as well.

**Comment by rchen152** [comment]
If this error occurs in 3.8 but not 3.7, then it's probably just a symptom of our incomplete 3.8 support. I'll make sure to check that we handle this case correctly once basic 3.8 support is complete.

**Comment by rchen152** [comment]
Running pytype over the sample code no longer produces an error, so I believe this is fixed now. Feel free to reopen if you're still seeing this issue.
