### ISSUE TITLE
Incorrectly inferring result of ternary operation with lambda

### ISSUE THREAD

**Issue by wontonst** [google/pytype#62]
Minimal repro

test.py

```
(default) myusername$ cat test.py
def stuff(foo):
    bar = {} if foo else []
    bar.values()
```

Output
```
(default) myusername$ pytype test.py
File "test.py", line 3, in stuff: No attribute 'values' on List[nothing] [attribute-error]
```

**Comment by matthiaskramm** [comment]
What output would you expect?

**Comment by wontonst** [comment]
since `foo` could evaluate to `True` or `False`, I think the expected output should be no output.

**Comment by matthiaskramm** [comment]
But wouldn't the actual program crash with an AttributeError if foo evaluates to "False"?

**Comment by wontonst** [comment]
Hmm, I see what you're getting at and I'm inclined to agree that the output for my poorly written minimal repro makes sense. Let me revise my minimal repro and title.

```
def foo(fnc=None):
    return {} if fnc else []

def bar():
    foo(fnc=lambda: True).values()

File "go.py", line 5, in bar: No attribute 'values' on List[nothing] [attribute-error]
```

`fnc` is evaluates to True so `foo(...)` is guaranteed to be a dict. If I change `fnc` from a lambda to `True`, the warning goes away.

**Comment by matthiaskramm** [comment]
Right. That's a better example. pytype doesn't know that a lambda type, by itself, always evaluates to true. (As do function types)

That already came up in another context. It's something we need to fix.
