### ISSUE TITLE
Machine readable output

### ISSUE THREAD

**Issue by Anthchirp** [google/pytype#634]
I would like to look into introducing pytype to an existing code base gradually. For this I would like to keep a list of known errors and parse the pytype output to ignore those known errors (plus a bit of additional logic to cope with unparsed files due to those erros).

While the output of pytype looks like it would not be too complex to scrape that wouldn't be very future proof.
Could we have pytype produce explicitly machine-readable output? The [`xunit2` format used by pytest, Jenkins and Microsoft Azure](https://docs.pytest.org/en/stable/deprecations.html#junit-family-default-value-change-to-xunit2) could be a useful and established format to adopt.

**Comment by rchen152** [comment]
Is [adding disable directives](https://google.github.io/pytype/user_guide.html#silencing-errors) not enough for ignoring known errors?

**Comment by Anthchirp** [comment]
I would have to disable the set of all observed errors in all observed files, whereas with a known list of error classes per file I can also check for introductions of a new error class into a file that didn't have that before.

Aside from my particular use case being able to reliably process pytype output would enable other uses as well: for example in the context of eg. Azure pipelines on GitHub machine readable output would also be straightforward to turn into GitHub Checks API type information, which could annotate pull requests on the relevant code line.

**Comment by rchen152** [comment]
I don't disagree that machine readable output would be useful. In fact, we already have an `--output-errors-csv` flag for the `pytype-single` tool. But we haven't exposed it to `pytype` and aren't likely to be able to prioritize that anytime soon, so you'll be unblocked much sooner if we can find a way to make your use case work with existing means. (I also remembered that we have a previous issue for this, https://github.com/google/pytype/issues/92, which looks like it was accidentally closed a couple years ago. I'll reopen it.)

> I would have to disable the set of all observed errors in all observed files, whereas with a known list of error classes per file I can also check for introductions of a new error class into a file that didn't have that before.

I don't follow. Suppose you run pytype over your entire code base and add `disable` statements everywhere they're needed. Then if pytype introduces a new error class in the future, the existing disables won't cover that, so you'll be made aware of the new error.

As a side note, if you'd prefer not to edit your source code to add disables, the `--exclude` flag can be used to omit files from type-checking.

**Comment by rchen152** [comment]
I'm going to close this issue in the interest of having only a single canonical issue for machine-readable output, but feel free to continue commenting if you have any questions about how to use disable directives or `--exclude`.

**Comment by Anthchirp** [comment]
> I don't follow. Suppose you run pytype over your entire code base and add `disable` statements everywhere they're needed. Then if pytype introduces a new error class in the future, the existing disables won't cover that, so you'll be made aware of the new error.

Sorry, I misunderstood. I discounted adding `disable` statements as I don't think this is feasible for us, but that would indeed be a good general solution.
I'll have a look into the `output-errors-csv` bits, that sounds promising.

Thanks for finding the other issue :+1:
