### ISSUE TITLE
Problem handling union types

### ISSUE THREAD

**Issue by MatthiasThul** [google/pytype#638]
Consider the following:

```python
from typing import Tuple, Union

def test(x: Union[float, Tuple[float, float]]) -> Tuple[float, float]:
    if not isinstance(x, tuple):
        x = (x, x)
    reveal_type(x)
    return x
```

Pytype 2020.07.30 gives:

```
File "test.py", line 6, in test: Union[Tuple[Union[float, Tuple[float, float]], Union[float, Tuple[float, float]]], Tuple[float, float]] [reveal-type]
```

Mypy 0.782 does what I would have expected:

```
test.py:6: note: Revealed type is 'Tuple[builtins.float, builtins.float]'
```

**Comment by rchen152** [comment]
Confirmed, pytype produces a spurious [bad-return-type] error here. The curious thing is that if I remove the return type and have pytype infer it, it comes up with `Tuple[float, float]`, and also a `reveal_type` call inserted right before `x = (x, x)` reveals `float`.

**Comment by rchen152** [comment]
This seems to work now, in that [bad-return-type] is no longer raised. The result of [reveal-type] still looks odd, but that's probably just us not filtering strictly enough until a potential error is actually detected.
