### ISSUE TITLE
attribute-error ignores parent variable annotations

### ISSUE THREAD

**Issue by rhofour** [google/pytype#652]
Example:
```
class BaseFoo:
    x: int

    def init(self, x):
        self.x = x

    def doThing(self):
        print(f"BaseFoo thing: {self.x}")

class Foo(BaseFoo):
    def doThing(self):
        print(f"Foo thing: {self.x}")

a = BaseFoo()
a.init(3)
a.doThing()

b = Foo()
b.init(4)
b.doThing()
```

I would this to pass pytype, but instead I see:

> File "...", line 12, in doThing: No attribute 'x' on Foo [attribute-error]

**Comment by martindemello** [comment]
simpler repro of the pytype error:

```
class BaseFoo:
    x: int

    def doThing(self):
        self.x

class Foo(BaseFoo):
    def doThing(self):
        self.x
```

i agree that either `BaseFoo` should raise an error (because `x` is not set in `__init__`) or `Foo` should inherit the annotation and not raise an error, preferably the latter.

**Comment by rchen152** [comment]
This error doesn't seem to occur anymore.
