### ISSUE TITLE
[QUESTION] Use Pytype for static type inference of local variables. 

### ISSUE THREAD

**Issue by maldil** [google/pytype#655]
Hello,
This is not a bug report or a feature request. I have a question to ask from the experts of this repository. 

**Requirement** 
I want to get your opinion on using Pytype to statically analyze python code with type information. I think this is slightly different from Pytype's intended purpose.   

**Example of the Requirement** 
```
import numpy as np
from typing import Any, Iterable, List

class Test ():
    def add_arrays(self,A):
        M = [[1,2,3],[4,5,6],[7,8,9]]
        result= np.add(np.sum(np.array(M),axis=1) ,A)
        return result

    def add_one(self,M):
        result=[]
        for m in M:
            list1=[]
            for x in m:
                list1.append(x+1)
            result.append(list1)
        return result

    def add(self) -> None:
        B = self.add_one([[1,2,3],[4,5,6],[7,8,9]])
        final_result = self.add_arrays ([2,3,4])
```
I want to obtain the infrared type of the variables **A, M, B, final_result,  result, M1, result1, m,** and **x.** . This includes all the variables used inside the methods including loop variables. 

**Question**
1. I tried `pytype --protocols testfile13.py` as suggested in [link](https://github.com/google/pytype/issues/344). However, it gives me a `testfile13.pyi` file only with the return type information as given below. 

```
from typing import Any, Iterable, List

np: module

class Test:
    def add(self) -> None: ...
    def add_arrays(self, A) -> Any: ...
    def add_one(self, M: Iterable) -> List[list]: ...
```
It doesn't give the inferred types of local variables. I know that Pytype is designed to check type related errors. For my requirement I am not interested in errors, all I need is the type information that Pytype uses to check errors. I might not be able to get this information from command line tool. I might need to query the data from Pytype's internal API or access internal data structures to get type information. 

I would like to have a helping hand on this requirement. 

Thanks a lot.

**Comment by rchen152** [comment]
You might be interested in https://github.com/google/pytype/tree/master/pytype/tools/traces. It has very little documentation at the moment, but https://github.com/google/pytype/blob/master/pytype/tools/annotate_ast/annotate_ast.py shows an example of how traces can be used to get at pytype's internal type information.

**Comment by maldil** [comment]
Thanks a lot for your prompt reply. I will go through the materials. Thanks again.

**Comment by rchen152** [comment]
You're very welcome. Let me know if you have any questions :)

**Comment by maldil** [comment]
@rchen152 
I want to thank you and the team again for this amazing tool. 

I have a further clarification question for you. By referring the test cases in the tool [pytype/tools/traces](https://github.com/google/pytype/tree/master/pytype/tools/traces), I could successfully infer types of source code blocks (the example given in original question). I use  [annotate_source(source, ast_factory, pytype_options)](https://github.com/google/pytype/blob/b1f27ecaa005e2d15f4dec20dd2b5b2d74087218/pytype/tools/annotate_ast/annotate_ast.py#L12). As far as I understand, I can use the method `annotate_source()` only on a python file. 
My exact requirement is, I have a large python project with hundreds of python files in multiple packages and it has several dependencies. 
**For example:**
```
from package2 import example_file
import numpy as np

def foo():
        aa = example_file.get_a_class()
        bb=aa.boo()
        cc = np.array(1,2,3)
        dd = np.array(3,4,5)
        ee = np.add(cc,dd)
```
If I use `annotate_source()` on the above source code, it annotates type information of all the variables as `Any`. In the above code, `numpy` is a third-party dependency and `package2` is another package in the project. I extracted the code block in the above example from the same project. 

**My Requirement:** 
1. When inferring type of `aa`, I want the tool to access the `example_file.get_a_class()` in the project and  infer return type of `example_file.get_a_class()`. Then, consider it as the type of `aa`. 
2. When inferring type of `dd`, I want the tool to infer the return type of numpy.array() (or use typeshed of Numpy if available) and use it as the type `dd`. 

**Question:**
How can I configure Pytype to check third party libraries and other packages in a project when inferring types of the source code segment as explained above? 

Since the tool does an amazing job when inferring type information of the code in my original question, I am sure this an easy task for the tool. Could you please help me to figure this out. 

Thank you in advance!

**Comment by rchen152** [comment]
1. Ah, traces is currently not integrated with whole-project analysis. I think what you can do is first run the `pytype` command-line tool over the file you want to trace, which will generate type information for its dependencies, plus a .imports file (probably located at `.pytype/imports/<your file>.imports`) that tells pytype where to find the type information. Then pass an Options object to traces.trace (https://github.com/google/pytype/blob/80e95781dda427e3dd273f6ff948f13466525341/pytype/tools/traces/traces.py#L62) with the imports_info option (https://github.com/google/pytype/blob/80e95781dda427e3dd273f6ff948f13466525341/pytype/config.py#L203) set to the .imports file.
1. pytype should already have type information for numpy: https://github.com/google/pytype/tree/master/pytype/pytd/builtins/2and3/numpy. I'll have to look into why it's not using it - seems like a bug.

**Comment by maldil** [comment]
@rchen152 
I want to thank you again for your kind help. 
I followed the above mentioned steps. I could successfully integrate inferred types in `.pytype/imports/` directory (generated by Pytype CLY tool) when inferring type information of a code segment.  
I want to do a small correction in the mentioned steps. When I use `imports_info` option, it did not work in the first glance. However, I noticed similar task in a test case ([link](https://github.com/google/pytype/blob/284d0f0edb3c60cf02367645bf8a8d055ca50fe9/pytype/tools/traces/traces_test.py#L53)) and it uses the option `imports_map`. Once I use `imports_map` it works nicely. **I hope this is the correct option to use.** 

I have a couple of questions regarding `numpy`. I want to ask these question because I could not find any supportive document that describes these information. If there are documents, please be kind enough to share the links. 

**Questions**
1. When you say that you support numpy, does that mean the implementation of Pytype is library dependent? Python contains thousand of third part libraries. Can't I assume that Pytype can be used with any dependent library?
2. I tried to use the tool on following code samples that uses `numpy` and `tensorflow`. 

```
import numpy as np
import tensorflow as tf

def foo():
        cc = np.array([1,2,3])
        dd = np.array([3,4,5])
        x1 = np.arange(9.0).reshape((3, 3))
        x2 = np.arange(3.0)
        x3 = np.add(x1, x2)
        rank_2_tensor = tf.constant([[1, 2],
                                     [3, 4],
                                     [5, 6]], dtype=tf.float1
```
I am glad to say that the tool `pytype/tools/traces` correctly annotated the type of `cc` and `dd` as `numpy.ndarray`. 
However, I observed following undesirable behaviors. 
1. It inferred the type of `x1, x2 , x3` as `Any`. 
2. The node `rank_2_tensor` in augmented AST (by [annotate_source](https://github.com/google/pytype/blob/b1f27ecaa005e2d15f4dec20dd2b5b2d74087218/pytype/tools/annotate_ast/annotate_ast.py#L12))  does not even contain an attribute 'resolved_type' (I think the tool omits the invocation tensorflow.constant())

I am not sure whether these observations are bugs or not. I am going to use `Pytype` to analyze 3000 open source python projects in my research. If these observations are bugs, I would be happy to use my efforts to solve them. 

I am attaching the code that I used to get type informations. [mainPyTypetest.py.zip](https://github.com/google/pytype/files/5139015/mainPyTypetest.py.zip). I hope this would help the people who are looking for a solution to the original question (I extracted these code pieces from the test code of this repo).

**Comment by rchen152** [comment]
1. pytype will infer all types as `Any` for most pip-installed libraries. If we didn't do this, it would simply take way too long to analyze any project with non-trivial dependencies. But pytype does use stubs from typeshed (https://github.com/python/typeshed), plus a few of its own, to get types for some of the most popular libraries. numpy is one for which we have our own (incomplete) stub that was contributed by a user.
1. The behavior here is caused by (1) our numpy stub falling back to Any for missing members (https://github.com/google/pytype/blob/3c7a3a0142bd5877ac34ec828c740450fb3d7822/pytype/pytd/builtins/2and3/numpy/__init__.pytd#L179), and (2) not having any stubs for tensorflow. So yes, these are bugs. We're always happy to accept contributions! If you're interested in helping type tensorflow, there's a tensor typing group that has monthly virtual meet-ups to discuss the latest developments: https://mail.python.org/archives/list/typing-sig@python.org/thread/PU6QFUW2NO5ORMDEOEB7BABTY4OIKRFH/.
