### ISSUE TITLE
Pytype fails on MacOSX(Mojave-10.14.9) when inferring types. 

### ISSUE THREAD

**Issue by maldil** [google/pytype#661]
Hello,

I am trying to execute Pytype in a project as below. 

`pytype --pythonpath=./$PROJECT_DIRECTORY  --no-report-errors  $PROJECT_DIRECTORY`

What I need is to run Pytype over a project (first step) and then use AST annotator to get type information of variables in a file. When I run above command it gives me the following error.

```
[2/154] infer pymc3.backends.HDF5
FAILED: /Users/user_name/Documents/Research_Topic_2/PytypeTest/.pytype/pyi/pymc3/backends/HDF5.pyi 
/Users/user_name/Documents/Research_Topic_2/VMS/pytestenv/bin/python -m pytype.single --imports_info /Users/user_name/Documents/Research_Topic_2/PytypeTest/.pytype/imports/pymc3.backends.HDF5.imports --module-name pymc3.backends.HDF5 -V 3.7 -o /Users/user_name/Documents/Research_Topic_2/PytypeTest/.pytype/pyi/pymc3/backends/HDF5.pyi --no-report-errors --nofail --quick /Users/user_name/Documents/Research_Topic_2/PytypeTest/pymc3-master/pymc3/backends/HDF5.py
ERROR:pytype.imports_map_loader Invalid imports_map entries (checking from root dir: /Users/user_name/Documents/Research_Topic_2/PytypeTest/.pytype)
ERROR:pytype.imports_map_loader   file does not exist: '/Users/user_name/Documents/Research_Topic_2/PytypeTest/.pytype/pyi/pymc3/backends/HDF5.pyi' (mapped from 'pymc3/backends/HDF5')
ERROR:pytype.imports_map_loader   file does not exist: '/Users/user_name/Documents/Research_Topic_2/PytypeTest/.pytype/pyi/pymc3/backends/NDArray.pyi' (mapped from 'pymc3/backends/NDArray')
ERROR:pytype.imports_map_loader   file does not exist: '/Users/user_name/Documents/Research_Topic_2/PytypeTest/.pytype/pyi/pymc3/backends/SQLite.pyi' (mapped from 'pymc3/backends/SQLite')
ERROR:pytype.imports_map_loader   file does not exist: '/Users/user_name/Documents/Research_Topic_2/PytypeTest/.pytype/pyi/pymc3/backends/Text.pyi' (mapped from 'pymc3/backends/Text')
ERROR:pytype.imports_map_loader   file does not exist: '/Users/user_name/Documents/Research_Topic_2/PytypeTest/.pytype/pyi/pymc3/backends/__init__.pyi' (mapped from 'pymc3/backends/__init__')
ERROR:pytype.imports_map_loader   file does not exist: '/Users/user_name/Documents/Research_Topic_2/PytypeTest/.pytype/pyi/pymc3/backends/base.pyi' (mapped from 'pymc3/backends/base')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/user_name/Documents/Research_Topic_2/VMS/pytestenv/lib/python3.7/site-packages/pytype/single.py", line 103, in <module>
    sys.exit(main() or 0)
  File "/Users/user_name/Documents/Research_Topic_2/VMS/pytestenv/lib/python3.7/site-packages/pytype/single.py", line 66, in main
    options = config.Options(sys.argv[1:])
  File "/Users/user_name/Documents/Research_Topic_2/VMS/pytestenv/lib/python3.7/site-packages/pytype/config.py", line 54, in __init__
    Postprocessor(names, options, self).process()
  File "/Users/user_name/Documents/Research_Topic_2/VMS/pytestenv/lib/python3.7/site-packages/pytype/config.py", line 392, in process
    node.processor(value)
  File "/Users/user_name/Documents/Research_Topic_2/VMS/pytestenv/lib/python3.7/site-packages/pytype/config.py", line 550, in _store_imports_map
    imports_map, self.output_options.output)
  File "/Users/user_name/Documents/Research_Topic_2/VMS/pytestenv/lib/python3.7/site-packages/pytype/imports_map_loader.py", line 90, in build_imports_map
    raise ValueError(msg)
ValueError: Invalid imports_map: /Users/user_name/Documents/Research_Topic_2/PytypeTest/.pytype/imports/pymc3.backends.HDF5.imports
Bad entries:
  pymc3/backends/HDF5 -> /Users/user_name/Documents/Research_Topic_2/PytypeTest/.pytype/pyi/pymc3/backends/HDF5.pyi
  pymc3/backends/NDArray -> /Users/user_name/Documents/Research_Topic_2/PytypeTest/.pytype/pyi/pymc3/backends/NDArray.pyi
  pymc3/backends/SQLite -> /Users/user_name/Documents/Research_Topic_2/PytypeTest/.pytype/pyi/pymc3/backends/SQLite.pyi
  pymc3/backends/Text -> /Users/user_name/Documents/Research_Topic_2/PytypeTest/.pytype/pyi/pymc3/backends/Text.pyi
  pymc3/backends/__init__ -> /Users/user_name/Documents/Research_Topic_2/PytypeTest/.pytype/pyi/pymc3/backends/__init__.pyi
  pymc3/backends/base -> /Users/user_name/Documents/Research_Topic_2/PytypeTest/.pytype/pyi/pymc3/backends/base.pyi
```
**Steps to reproduce**
1. Clone https://github.com/pymc-devs/pymc3
2. Run `pytype --pythonpath=./$PROJECT_DIRECTORY --no-report-errors $PROJECT_DIRECTORY`
(Pytype version = 2020.08.17, OS version = macOS Mojave-10.14.9)

**Questions**

1. Do you have any idea on the above error?
2. Suppose that, I want to run Pytype without failing. I observed two options (`--nofail` and `--return-success`) in the [configuration](https://github.com/google/pytype/blob/7f6df736352f84d8648d96127ca227d4ccdc7b64/pytype/config.py) file . When I try to run pytype with these two options, pytype does not identify the options. It says `pytype: error: unrecognized arguments: --nofail`. What could be the reason for these errors and what options should I use to run Pytype without failing?

The command that I tried is 
`pytype --pythonpath=$PROJECT_DIRECTORY --no-report-errors --nofail $PROJECT_DIRECTORY`
Thank you in advance.

**Comment by maldil** [comment]
Could anyone please help me to figure out this error? Thanks!

**Comment by martindemello** [comment]
could you run `find .pytype/pyi/pymc3` and see what pyi files did get generated?

**Comment by maldil** [comment]
It gives me lot files including flowing files. 

```.pytype/pyi/pymc3/backends/base.pyi-1
.pytype/pyi/pymc3/backends/__init__.pyi-1
.pytype/pyi/pymc3/backends/report.pyi
.pytype/pyi/pymc3/backends/Text.pyi-1
.pytype/pyi/pymc3/backends/HDF5.pyi-1
.pytype/pyi/pymc3/backends/NDArray.pyi-1
.pytype/pyi/pymc3/backends/SQLite.pyi-1
```
The attachment [file.txt.zip](https://github.com/google/pytype/files/5166928/file.txt.zip) contain all the files that were generated. 

But it doesn't have the files mentioned in the error (`.pytype/pyi/pymc3/backends/HDF5.pyi` and ......). What are these `xxxx.pyi-1` files? 
Do you have any idea about the error?

**Comment by martindemello** [comment]
the `pyi-1` files are part of pytype's import cycle analysis - a set of mutually dependent files are analysed using a restricted first pass, which generates `pyi-1` files which are then used in a second pass to generate the actual `pyi` files. it looks like the second pass failed here, still investigating why.

**Comment by maldil** [comment]
@martindemello Thanks for your comment. I was analyzing types of this repository. https://github.com/pymc-devs/pymc3 
If you could run `pytype --pythonpath=./$PROJECT_DIRECTORY --no-report-errors $PROJECT_DIRECTORY` on it, you will be able to reproduce the error. 

@rchen152 I am not sure whether we should move the the label of this ticket to `bug`. 

I have a question for you. 
are the options `--nofail` and `--return-success` working?. When I try to execute Pytype with those two options, it says `pytype: error: unrecognized arguments: --nofail`

**Comment by martindemello** [comment]
`--nofail` and `---return-success` are arguments to `pytype-single`, the executable that analyses a single file. `pytype` analyses a project by computing the dependency tree and then calling `pytype-single` internally on each file in order.

**Comment by martindemello** [comment]
analysing pymc3 worked for me on linux:
```
$ pytype --pythonpath=pymc3 --no-report-errors pymc3
Computing dependencies
Analyzing 163 sources with 0 local dependencies
ninja: Entering directory `/home/mdemello/tmp/.pytype'
[220/220] check pymc3.tests.test_glm
Success: no errors found
```

if it's a macos-specific error we won't be able to help much :( could you try testing in a linux virtual machine and see if that works for you?

**Comment by maldil** [comment]
@martindemello thanks for the message.
I created a linux virtual environment and it worked perfectly. Unfortunately, I can not move my project to linux. It seems there is some Mac OS specific setup that breaks `pytype`.  Do you have a clue about this behavior?

**Comment by martindemello** [comment]
@maldil the probem is that there are only three pytype developers and all three of us use linux. macosx and windows are officially "unsupported" - we're happy when they work and we're always willing to merge in patches for them, but we are not able to debug and maintain non-linux platforms ourselves.

**Comment by tmbo** [comment]
I think we are running into the same error while using pytype on rasahq/rasa: testing works on Linux but fails on the latest OSX versions.

```
ERROR:pytype.imports_map_loader Invalid imports_map entries (checking from root dir: /Users/tmbo/lastmile/bot-ai/rasa/.pytype)
ERROR:pytype.imports_map_loader   file does not exist: '/Users/tmbo/lastmile/bot-ai/rasa/.pytype/pyi/rasa/core/actions/Action.pyi' (mapped from 'rasa/core/actions/Action')
Traceback (most recent call last):
  File "/Users/tmbo/.pyenv/versions/3.7.5/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/tmbo/.pyenv/versions/3.7.5/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/tmbo/Library/Caches/pypoetry/virtualenvs/rasa-U5VQkfdm-py3.7/lib/python3.7/site-packages/pytype/single.py", line 103, in <module>
    sys.exit(main() or 0)
  File "/Users/tmbo/Library/Caches/pypoetry/virtualenvs/rasa-U5VQkfdm-py3.7/lib/python3.7/site-packages/pytype/single.py", line 66, in main
    options = config.Options(sys.argv[1:])
  File "/Users/tmbo/Library/Caches/pypoetry/virtualenvs/rasa-U5VQkfdm-py3.7/lib/python3.7/site-packages/pytype/config.py", line 54, in __init__
    Postprocessor(names, options, self).process()
  File "/Users/tmbo/Library/Caches/pypoetry/virtualenvs/rasa-U5VQkfdm-py3.7/lib/python3.7/site-packages/pytype/config.py", line 392, in process
    node.processor(value)
  File "/Users/tmbo/Library/Caches/pypoetry/virtualenvs/rasa-U5VQkfdm-py3.7/lib/python3.7/site-packages/pytype/config.py", line 550, in _store_imports_map
    imports_map, self.output_options.output)
  File "/Users/tmbo/Library/Caches/pypoetry/virtualenvs/rasa-U5VQkfdm-py3.7/lib/python3.7/site-packages/pytype/imports_map_loader.py", line 90, in build_imports_map
    raise ValueError(msg)
ValueError: Invalid imports_map: /Users/tmbo/lastmile/bot-ai/rasa/.pytype/imports/rasa.core.actions.Action.imports
Bad entries:
  rasa/core/actions/Action -> /Users/tmbo/lastmile/bot-ai/rasa/.pytype/pyi/rasa/core/actions/Action.pyi
```

Is there anything we can help you with to debug this?

**Comment by martindemello** [comment]
one weird thing i notice in both error logs is the capital letters in module names, e.g. `rasa/core/actions/Action -> /Users/tmbo/lastmile/bot-ai/rasa/.pytype/pyi/rasa/core/actions/Action.pyi`. does the directory tree on osx actually have files with capitalised names? looking up rasa on github the file seems to be `action.py` rather than `Action.py`: https://github.com/RasaHQ/rasa/tree/master/rasa/core/actions

**Comment by maldil** [comment]
I observed the same thing except for `base.py` and `__init__.pyi`. 
Below is the error that I get for the project `pymc3`
```
Bad entries:
  pymc3/backends/HDF5 -> /Users/user_name/Documents/Research_Topic_2/PytypeTest/.pytype/pyi/pymc3/backends/HDF5.pyi
  pymc3/backends/NDArray -> /Users/user_name/Documents/Research_Topic_2/PytypeTest/.pytype/pyi/pymc3/backends/NDArray.pyi
  pymc3/backends/SQLite -> /Users/user_name/Documents/Research_Topic_2/PytypeTest/.pytype/pyi/pymc3/backends/SQLite.pyi
  pymc3/backends/Text -> /Users/user_name/Documents/Research_Topic_2/PytypeTest/.pytype/pyi/pymc3/backends/Text.pyi
  pymc3/backends/__init__ -> /Users/user_name/Documents/Research_Topic_2/PytypeTest/.pytype/pyi/pymc3/backends/__init__.pyi
  pymc3/backends/base -> /Users/user_name/Documents/Research_Topic_2/PytypeTest/.pytype/pyi/pymc3/backends/base.pyi
```
Below is the real file names. 

<img width="445" alt="Screen Shot 2020-09-11 at 12 57 02 PM" src="https://user-images.githubusercontent.com/20140049/92967559-58942c00-f42e-11ea-821a-ef4e1094c6ca.png">

The real file names in https://github.com/pymc-devs/pymc3/tree/master/pymc3/backends does not contain capital letters.  But this is not true for `base.py` and `__init__.pyi`. They are not capitalized. Strange!

**Comment by cihati** [comment]
We're having this `ValueError: Invalid imports_map ` issue in MacOS 10.15.7 as well. pytype works fine in CI (linux) though. I'm afraid we'll probably disable pytype as this is degrading our local dev experience 😢

**Comment by msuozzo** [comment]
I think I have a lead:

* Both of those cases seem to have symbols exported by the `__init__.py` files that shadow the names of modules: `NDArray` is exported by `backends/__init__.py` and `backends/ndarray.py` exists.
* macOS uses a case-insensitive filesystem by default so `NDArray.py` is the exact same file as `ndarray.py`

I suspect that after loading the `NDArray` symbol, some bit of the import mechanism is getting that confused with the module at `ndarray.py` and failing to generate the appropriate stubs. I'm not familiar enough with the pytype internals to speculate on where that might be happening but that at least feels like a likely culprit here.

**Comment by martindemello** [comment]
possibly related bug: https://github.com/google/pytype/issues/264

**Comment by gpshead** [comment]
I _am_ able to reproduce this on my mac, so if you want me to try something, let me know. But you can do this on Linux... Being case insensitive filesystem related makes sense. To get one of these on Linux:

Just test on a vfat filesystem (ascii case insensitive by definition), as such:

```
sudo dd if=/dev/zero of=case-insensitive-fs.img bs=1G count=2
sudo mkfs.vfat case-insensitive-fs.img
sudo mount -o uid=$USER case-insensitive-fs.img /mnt
touch /mnt/lower-case
cat /mnt/LOWER-caSE
ls /mnt
rm /mnt/Lower-Case
# case insensitive as intended.
```

now with a case insensitive fs on /mnt get the source tree to run pytype on over there.

```
cd /mnt
git clone --depth 1 https://github.com/pymc-devs/pymc3
pytype --pythonpath=./pymc3 --no-report-errors pymc3/
```

That takes a long time... before "success" the problem has been reproduced on Linux!

don't forget to both umount /mnt and delete your overly large filesystem image when done. ;)  the `--depth 1` on the git clone above should keep the pymc3 tree reasonably small without a 700mb .git/ subtree it'd have otherwise so my 2G image size is way overkill.

Now that you know the situation, a tiny example could be created instead of pymc3.  Yes I agree, this seems probably related to #264.  Is that TL;DR pytype import logic not exactly matching Python?

**Comment by martindemello** [comment]
yes, it probably is a case where pytype's import logic does not match python's; we use heuristics rather than actual module loading to see if `from a.b import c` is importing a class or a module

**Comment by msuozzo** [comment]
> possibly related bug: #264

I do think this is related and it seems to be a special case of #264. That one's likely much rarer, though, given it's error-prone to directly shadow a module with a different symbol.

**Comment by martindemello** [comment]
upgrading to `importlab-0.7` should fix this. thanks again, @msuozzo !
