### ISSUE TITLE
[Q] How to supply user-defined stubs?

### ISSUE THREAD

**Issue by sizmailov** [google/pytype#665]
Hi! I want pytype to recognize types from my C extension. Is it supported?

[The paragraph](https://google.github.io/pytype/user_guide.html#pyi-stub-files) in docs suggests that it's possible, but I couldn't find a way to make it work. 

Is there (undocumented?) analog for `MYPYPATH` env variable?

**Comment by rchen152** [comment]
Hello! Unfortunately, open-source pytype doesn't support this yet. (We do internally, which is why that paragraph in the docs exists.) https://github.com/google/pytype/issues/151 is the issue for it, although as you can probably see from the lack of activity, we haven't found time to work on it.
