### ISSUE TITLE
merge-pyi doesn't work with walrus operator

### ISSUE THREAD

**Issue by matmarczak** [google/pytype#672]
Hi!

I was just experimenting with pytype and found that walrus operator blocks `merge-pyi`.

Consider simple example (`test.py`):
```
var = 3
if (a:=var-3):
    pass
```
`merge-pyi test.py .pytype/pyi/test.pyi` returns
`lib2to3.pgen2.parse.ParseError: bad input: type=11, value=':', context=('', (2, 5))`

**Comment by rchen152** [comment]
Ah, I don't think pytype handles the walrus operator at all yet. We'll have to add it to the list of 3.8 features to support.

**Comment by rchen152** [comment]
@martindemello is rewriting merge-pyi from the ground up, so I'm closing as obsolete issues related to its current implementation.
