### ISSUE TITLE
Support new typing constructs in Python 3.8

### ISSUE THREAD

**Issue by rchen152** [google/pytype#680]
An umbrella issue for new typing features in 3.8 that pytype needs to add support for. May be broken up into smaller issues as we start work on this (tentatively scheduled for Q1 2021). List compiled by searching for "new in version 3.8" in https://docs.python.org/3/library/typing.html.

- [ ] Literal: #790
- [x] Protocol: #524, #789, #792
- [x] TypedDict
- [x] final, Final
- [x] get_args - probably just needs to be added to typing.pytd
- [x] runtime_checkable

**Comment by mrahtz** [comment]
On the subject of `Literal` - I notice that in the example below, `x` is inferred to be `int` instead of `Literal[1]`. Is this intentional?

```python
from typing_extensions import Literal

def get_x() -> Literal[1]:
    return 1

x = get_x()
reveal_type(x)
```

**Comment by ibozhilov** [comment]
Is introducing support for typing.Final on the roadmap?

**Comment by rchen152** [comment]
Yep, that's coming up soon, after TypedDict!

**Comment by theahura** [comment]
What's the current timeline for TypedDict? I spotted a recent change in the [docs](https://github.com/google/pytype/blob/main/docs/errors.md#annotation-type-mismatch) related to catching TypedDict errors, so I was wondering if this is coming through the pipe soon

**Comment by martindemello** [comment]
yes, TypedDict should be coming up soon! hopefully fully complete within the next couple of weeks.

**Comment by rchen152** [comment]
TypedDict support is ready! (Thanks to @martindemello for implementing this :slightly_smiling_face:) It's guarded behind a feature flag until we can roll it out internally, but feel free to try it out today by passing in `--enable-typed-dicts` to pytype-2022.01.05 and later.

**Comment by rchen152** [comment]
Now that we've got just one issue left (https://github.com/google/pytype/issues/790), I'm going to close this omnibus one, since I don't think it makes sense to have two issues open to track the same feature request.
