### ISSUE TITLE
Question: goals of pytype

### ISSUE THREAD

**Issue by atollk** [google/pytype#681]
Hi,
I'm working on my own Python typing library at the moment as mypy was not sufficient for me and I just found pytype. I wanted to see if my goals align with those of that pytype aims for, in which case I'd stop working on my own project and try to contribute to pytype instead. It would be great if someone could comment on these two points, to see whether they align.

First, my main target application was to provide a "base" for a typing library that could be used by different tools, e.g. static analyzers. Basically an internal library that can annotate, e.g. an AST, with types of all the nodes that represent an identifier. As a more specific example, I might want to write a flake8 plugin that would report warnings when `len(x) > 0` is used instead of just `x` if `x` is a `list` but not for any other types like `str` or `dict`.

I see that pytype offers something in that direction with `reveal_type` but I couldn't find an actual public, easy-to-use API for that. Does that already exist or is that something that is planned for the near future?

Second, I sometimes got the feeling that pytype is reliant on a complete CFG analysis to work properly and does not actually take user-specified type hints into account (at least not to their full potential). Consider the following example.

```python
from typing import List, Callable, TypeVar

T = TypeVar("T")

def append_to_list(l: List[T]) -> Callable[[T], None]:
    return lambda x: l.append(x)

def test_function():
    x = []
    f = append_to_list(x)
    f(12)
    return x

reveal_type(test_function())
```

This results in the output `List[nothing]`. Without the type hints at `append_to_list`, the output is `List[int]`, which is what I would expect. Would this be considered a bug or intended behavior?

Thanks!

**Comment by rchen152** [comment]
1. You may be interested in the `traces` library (https://github.com/google/pytype/tree/master/pytype/tools/traces) or the (incomplete) `annotate-ast` (https://github.com/google/pytype/tree/master/pytype/tools/annotate_ast). The former provides access to pytype's inferred local types, and the latter uses those types to annotate an AST. Both are quite rough around the edges - we put just enough work into `traces` to get it working well enough that it could feed types into Python 2 to 3 migration tooling, and annotate_ast is an experimental project that has somewhat stalled out - but they may still be a reasonable starting point/inspiration. Although we'd love to improve these tools at some point, we don't have any near-term plans to do so.
1. The `List[nothing]` output looks like a bug. pytype used to be fairly lackadaisical about enforcing user-provided type hints. We've been tightening that up recently, but it's an ongoing effort.

**Comment by kamahen** [comment]
For AST-annotation and static analysis, this might interest you:
https://github.com/Instagram/LibCST
https://instagram-engineering.com/static-analysis-at-scale-an-instagram-story-8f498ab71a0c

**Comment by rchen152** [comment]
Hope this was helpful - feel free to keep commenting on this issue if you have other questions.
