### ISSUE TITLE
 No module named ninja.__main__

### ISSUE THREAD

**Issue by wj-Mcat** [google/pytype#685]
```shell
pytype src/ --disable=import-error,pyi-error
Computing dependencies
WARNING generate default: System module wechaty.__init__
Analyzing 24 sources with 7 local dependencies
/Users/wujingjing/miniconda3/envs/wechaty/bin/python: No module named ninja.__main__; 'ninja' is a package and cannot be directly executed
```
I don't have a ninja dependency package, but there is an error from it.

**Comment by rchen152** [comment]
ninja is a dependency of pytype itself. Now that I think about it, the last release of pytype requires the most recent release of ninja-python-distributions, but I forgot to update the setup file to include a version requirement for ninja. Do you have ninja version 1.10.0.post2 (https://pypi.org/project/ninja/#history)? If not, could you try running `pip install -U ninja` and see if that fixes your issue?

**Comment by rchen152** [comment]
The next release of pytype will explicitly require ninja 1.10.0.post2, which should resolve this issue. (If you'd like to test out the fix before then, you can [install pytype from the source](https://github.com/google/pytype#installing)). Please let me know if you're still experiencing issues after that.
