### ISSUE TITLE
typeshed downgraded instead of upgraded

### ISSUE THREAD

**Issue by gizmoguy** [google/pytype#69]
Commit a86093f79e5b63a081339ed814e50c4da27459c5 claims to update typeshed, it actually does the opposite and takes us back to typeshed from Feb 9, 2017 which has some bugs that break our test suite.

> brad@nix:/tmp/pytype$ git diff a86093f79e5b63a081339ed814e50c4da27459c5^ a86093f79e5b63a081339ed814e50c4da27459c5
> diff --git a/typeshed b/typeshed
> index 81f77b1..f192b8c 160000
> --- a/typeshed
> +++ b/typeshed
> @@ -1 +1 @@
> -Subproject commit 81f77b17eca63ee718e1c57e533440db412bf847
> +Subproject commit f192b8c784f3cbe5e840e10274e4429bb146653e

https://github.com/python/typeshed/tree/f192b8c784f3cbe5e840e10274e4429bb146653e
https://github.com/python/typeshed/tree/81f77b17eca63ee718e1c57e533440db412bf847

**Comment by matthiaskramm** [comment]
Huh. No kidding. I'm seeing the same thing. How weird

 Let me try upgrading it again.

**Comment by matthiaskramm** [comment]
Upgraded typeshed to the latest version. Closing this issue, but please reopen if you're still seeing issues.

**Comment by gizmoguy** [comment]
Re-opening this issue again, looks like the commit bddf0d70966c15ec920de185a5e78fbbc7aecb00 " remove broken line" also has the side-effect of rolling back typeshed to an early commit from 2017 that has broken types again.

**Comment by matthiaskramm** [comment]
Thanks for letting me know! Looks like the submodule sneaked into that commit, indeed. I just upgraded typeshed to the latest version.
