### ISSUE TITLE
Issue with dataclass

### ISSUE THREAD

**Issue by dgorelik** [google/pytype#697]
Hi, I am trying to remove the `ignore` here:

https://github.com/google/python-spanner-orm/blob/039f7c3aba35916df4a129165f4bf6c8c5a544a4/spanner_orm/relationship.py#L94

But, when I run `pytype` (python version 3.7, pytype version 2020.8.28), I get the following error:

```
Function RelationshipConstraint.__init__ expects 1 arg(s), got 5 [wrong-arg-count]
  Expected: (self)
  Actually passed: (self, _, _, _, _)
```

This seems pretty similar to the error reported in https://github.com/google/pytype/issues/234, which has been fixed. Is there something particular about the dataclass in the linked code that pytype is not working correctly here?

Thanks!

**Comment by rchen152** [comment]
Could you provide more detailed repro instructions? I tried (in a Python 3.7 virtualenv):
1. `git clone git@github.com:google/python-spanner-orm.git`
2. Remove `# type: ignore` from python-spanner-orm/spanner_orm/relationship.py:94
3. ```
    pip install pytype
    cd python-spanner-orm
    pytype spanner_orm/relationship.py  
    ```
and didn't get any pytype errors.

Also, in whichever directory you're running pytype from, there should be a `.pytype` directory with type-checking artifacts. What are the contents of `.pytype/pyi/spanner_orm/relationship.pyi`? That file has the inferred type information for `relationship.py`, and seeing what pytype thinks the `RelationshipConstraint` class looks like could help narrow down what went wrong.

**Comment by dgorelik** [comment]
As I tried to create more detailed repro instructions, I created a fresh virtual env, and did not get any pytype errors for that file. Thanks for taking a look and sorry for the noise!

**Comment by rchen152** [comment]
No worries, glad you figured it out!
