### ISSUE TITLE
typeshed tests are broken due to a recent pytype commit

### ISSUE THREAD

**Issue by ilevkivskyi** [google/pytype#70]
typeshed tests seem to be broken because of this commit https://github.com/google/pytype/commit/e2e334a4bae29342820e41d43e24c17826a7f8b0, see https://travis-ci.org/python/typeshed/jobs/320508796

**Comment by matthiaskramm** [comment]
Looks like our scrubber went overboard.

Fixing.

**Comment by matthiaskramm** [comment]
Fixed, restarting travis.

**Comment by ilevkivskyi** [comment]
Thanks! :+1:

**Comment by ilevkivskyi** [comment]
Oops! It looks like something else went wrong, see https://travis-ci.org/python/typeshed/jobs/320508796 and https://travis-ci.org/python/typeshed/jobs/320665032
```
pytype.load_pytd.BadDependencyError: Can't find pyi for 'importlib.machinery', referenced from 'importlib.util'
```

**Comment by ilevkivskyi** [comment]
OK, it is fixed again by extending the blacklist.
