### ISSUE TITLE
function annotation is not checked against union type

### ISSUE THREAD

**Issue by frank-swp** [google/pytype#721]
The following code does not fail with pytype but it should.

```python
class A:
     def do(self):
         print("A")


class B:
    def doIt(self):
         print("B")


def useB(thing: B):  # it fails without annotation
    thing.doIt()

things = [A(), B()]

for thing in things:
   # a: B = thing  # fails correctly
   useB(thing)  # does not fail

# useB(A()) # fails correctly
```
it seems that it does not check function annotations correctly against union types.

pytype version: 2020.10.08

**Comment by rchen152** [comment]
Thanks for the report, and sorry for the slow response. This looks like https://github.com/google/pytype/issues/365, so I'm going to close this issue in favor of that one. The tl;dr is that not checking all possible combinations of parameter types for function calls is a known bug, which we can't fix until we either significantly improve pytype's performance or somehow rewrite the algorithm to avoid having to check all combinations.
