### ISSUE TITLE
TypeVar doesn't work with quoted bound type

### ISSUE THREAD

**Issue by kamahen** [google/pytype#73]
(I'm guessing that this isn't a problem in typeshed, which seems to define `TypeVar = object()`)
Mypy seems to be OK with this.

```
File "pod.py", line 7, in PlainOldData: wrong arguments [invalid-typevar]
  Expected: (name, *constraints, bound: Optional[type] = ..., ...)
  Actually passed: (name, bound: str)
```

```
from typing import Any, Dict, Sequence, Text, TypeVar

class PlainOldData:

    __slots__ = ()  # type: Sequence[Text]

    _SelfType = TypeVar('_SelfType', bound='PlainOldData')

    def _replace(self: _SelfType, **kwargs) -> _SelfType:
        """Make a new object, replacing fields with new values."""
        new_attrs = {
            k: kwargs.pop(k) if k in kwargs else getattr(self, k)
            for k in self.__slots__
        }
        if kwargs:
            raise ValueError('Unknown field names: {!r}'.format(list(kwargs)))
        return self.__class__(**new_attrs)
```

**Comment by gvanrossum** [comment]
I assume it's specifically the recursive reference. Those don't work in mypy in general.

**Comment by kamahen** [comment]
Mypy doesn't complain ... are you saying that the lack of complaint doesn't mean it's anyalyzing things correctly?

**Comment by gvanrossum** [comment]
NM, I didn't realize this was in the pytype tracker. :-) Mypy typically complains loudly if it doesn't get something like that.

**Comment by kamahen** [comment]
For context, this code snippet is from a "replacement" for `namedtuple`, using a plain Python class rather than tuple as the base (this seems to be faster in microbenchmarks; but it isn't immutable).  If I remove the `bound` argument to `TypeVar`, it seems fine. Typeshed also has examples of `bound` with a string; e.g., `typeshed/stdlib/3/io.pyi` and `typeshed/2and3/profile.pyi`.

BTW, when I tried running pytype on `typeshed/stdlib/3/io.pyi` it failed with maximum recursion depth exceeded; and `typeshed/2and3/profile.pyi` generated a ConversionError.

**Comment by martindemello** [comment]
how were you running pytype on the typeshed files? this works for me:
````
$ pytype --parse-pyi -V3.6 typeshed/stdlib/3/io.pyi
$ pytype --parse-pyi -V3.6 typeshed/stdlib/2and3/profile.pyi 
````

**Comment by rchen152** [comment]
Reproduced with (in a .py file, not a .pyi file):

```
from typing import TypeVar
class Foo:
  T = TypeVar("Foo", bound="Foo")
```

**Comment by martindemello** [comment]
note that this has nothing to do with recursion; it just doesn't like the string bounds. `T = Typevar("T", bound="int")` doesn't work either.
