### ISSUE TITLE
Import-error on multiprocessing.RawValue

### ISSUE THREAD

**Issue by alexchang8** [google/pytype#736]
Pytype seems to be unable to find `multiprocessing.RawValue`. Checked that this behavior occurs in both python3.6.9 and python3.5.3

To reproduce:

foo.py:
```
from multiprocessing import RawValue
```

**Comment by rchen152** [comment]
Looks like the `multiprocessing.context` module has a `_default_context` attribute (an instance of `multiprocessing.context.DefaultContext`), all of whose public methods are exported in `multiprocessing.__init__` (https://github.com/python/cpython/blob/85720596f1baf8db2cd456c8c2bd07dc03c6beca/Lib/multiprocessing/context.py#L27).

This is missing from the multiprocessing stubs in https://github.com/python/typeshed/tree/master/stdlib/3/multiprocessing. A reasonable way to represent this would be to add
```
_default_context: DefaultContext
```
to `context.pyi` and
```
from multiprocessing.context import _default_context
RawValue = _default_context.RawValue
Value = _default_context.Value
# etc.
```
to `__init__.pyi`. Unfortunately, I just checked and pytype does not support aliasing an attribute of a constant in a pyi file, so we would have to first support that in our pyi parser. A possible workaround would be to just redefine `RawValue` and friends in the `__init__` file, but that makes it possible for the redefinitions to go out-of-sync with the original definitions.

**Comment by rchen152** [comment]
The pytype issue has been fixed (pending a release), and there's a typeshed PR to add multiprocessing.RawValue (https://github.com/python/typeshed/pull/5231), so I don't think we need to track this in pytype anymore.
