### ISSUE TITLE
Python 3.9 is not supported

### ISSUE THREAD

**Issue by dundee** [google/pytype#749]
Python 3.9 is out for some time now, it would be great if it's supported.

**Comment by rchen152** [comment]
I recently did some work to start supporting 3.9, but we still need to implement new opcodes (https://github.com/google/pytype/blob/0790b3f0c1600d21a7d7a917eb408e29d772c365/pytype/vm.py#L3413) and fix test failures (https://github.com/google/pytype/runs/1488890229?check_suite_focus=true - the overall status is a lie, expand the "Run tests for python 3.9" section to see failures).

Added a "help wanted" label because I'd love help on this issue! Internally, we don't need 3.9 yet, so I've been chipping away at this in my spare time.

**Comment by ShayNehmad-RecoLabs** [comment]
I'd like to add that we'd want this as well. How can I help if help is wanted? @rchen152 I'm not super familiar with pytype but with some direction, I could probably help.

**Comment by kamahen** [comment]
Is there documentation on how to add a bytecode? I suppose I could figure it out by looking through the source (and maybe looking at https://github.com/nedbat/byterun), but if there's more information than contained in bytecode.md, that would be nice.
(No promises that I'll actually work on this, of course).

BTW, it would be nice to have type annotations in vm.py (and elsewhere) ... I presume pytype could be run on itself to generate thiese?

**Comment by rchen152** [comment]
@ShayNehmad-RecoLabs The main thing standing in the way of 3.9 support is updating pytype to reflect changes in the Python bytecode. (pytype works by compiling source files to bytecode and then analyzing the bytecode.) pytype/vm.py contains a `byte_OPCODE_NAME` method for every bytecode operation, and the [documentation for the dis library](https://docs.python.org/3/library/dis.html) describes what each opcode does. What I typically do is add implementations for the new opcodes (I've put in empty stubs for the 3.9 ones at the bottom of vm.py: https://github.com/google/pytype/blob/0790b3f0c1600d21a7d7a917eb408e29d772c365/pytype/vm.py#L3413) based on the descriptions in the `dis` docs, then use test failures to figure out what behavior changes need to be made to existing opcode implementations.

@kamahen Have you seen the rest of the [developer guide](https://google.github.io/pytype/developers/index.html)? In particular, you might want to check out the other docs in the "Program Analysis" section.

**Comment by Marto32** [comment]
Any updates on the timeline here? Would love to see this in 3.9.

**Comment by rchen152** [comment]
All of the Python 3.9 tests pass at head now. The next release, which should be later this week unless it gets held up, will include 3.9 support (minus new 3.9+ features).

**Comment by dylrich** [comment]
Thank you so much!
