### ISSUE TITLE
None return type generates error message

### ISSUE THREAD

**Issue by kamahen** [google/pytype#75]
This error message goes away if I remove the `->None`.
```
$ pytype -V3.6 /tmp/z.py
ERROR:pytype.matcher:Invalid type: <class 'pytype.abstract.AbstractOrConcreteValue'>
File "z.py", line 6, in __init__: bad option in return type [bad-return-type]
  Expected: Any
  Actually returned: None
```
```python
$ cat /tmp/z.py
from typing import Any

class C:
    def __init__(self, **kwargs: Any) -> None:
        for key, value in kwargs.items():
            setattr(self, key, value)
```

**Comment by kamahen** [comment]
I can also make the error message go away by changing `->None` to `type(None)` (Python 3 doesn't have `types.NoneType`)

Mypy accepts `None`; and [PEP 484](https://www.python.org/dev/peps/pep-0484/#id13) says that the "return type of `__init__` ought to be annotated with `-> None`. (It also [says](https://www.python.org/dev/peps/pep-0484/#using-none): "When used in a type hint, the expression `None` is considered equivalent to `type(None)`.")

**Comment by rchen152** [comment]
This appears to have been fixed.
