### ISSUE TITLE
False positive name-error with list comprehension and del statement

### ISSUE THREAD

**Issue by Cebtenzzre** [google/pytype#750]
pytype reports a false positive under certain conditions.

#### Example Code
```python
def foo(x):
    num = 1
    nums = [num for _ in range(2)]
    del num
```
#### Actual Behavior
```
$ pytype-single repr.py
File "repr.py", line 3, in <listcomp>: Name 'num' is not defined [name-error]

For more details, see https://google.github.io/pytype/errors.html#name-error.
```

No error is reported if I move the body of foo to the global scope, replace the list comprehension with `nums = num`, or remove the `del` statement.

#### Expected Behavior
This code is correct, so pytype shouldn't report an error. num is defined at the time of use; pytype seems to understand this for simple loads but not for list comprehensions.

#### Software Versions
pytype master (2020.12.02)
Python 3.8

**Comment by rchen152** [comment]
Ha, this seems to be a regex matching failure: https://github.com/google/pytype/blob/22545931decb6e14a63e1ed66c81899c9277203b/pytype/analyze.py#L31. The name of the list comprehension is `foo.<locals>.<listcomp>`. Sent a fix out for review, should be exported to GitHub sometime next week.
