### ISSUE TITLE
`lru_cache` decorator in Protocol implementations messes up matching

### ISSUE THREAD

**Issue by MatthiasThul** [google/pytype#753]
Consider the following `test.py`:

```python
from dataclasses import dataclass
from typing_extensions import Protocol, runtime_checkable

@runtime_checkable
class SomeProtocol(Protocol):
    def foo(self) -> "SomeProtocol":
        raise NotImplementedError

@dataclass
class SomeClass:
    a: int

    @classmethod
    def build(cls, a: int) -> "SomeClass":
        return cls(a)

    def foo(self) -> SomeProtocol:
        return SomeClass.build(2 * self.a)
```

PyType `2020.11.23` and `2020.11.12` as well as MyPy `0.790` pass this. When decorating `foo` in `SomeClass` with `@lru_cache(maxsize=None)` from `functools`, then PyType `2020.11.12` as well as MyPy `0.790` still pass. PyType `2020.11.23` fails however:

```bash
Computing dependencies
Analyzing 1 sources with 0 local dependencies
ninja: Entering directory `/var/folders/wd/gpgynm3j4h947l1mkjj3hx7h0000gq/T/tmpqnnkygz4'
[1/1] check test
FAILED: /var/folders/wd/gpgynm3j4h947l1mkjj3hx7h0000gq/T/tmpqnnkygz4/pyi/test.pyi
/Users/someone/code/pytype/venv/bin/python -m pytype.single --imports_info /var/folders/wd/gpgynm3j4h947l1mkjj3hx7h0000gq/T/tmpqnnkygz4/imports/test.imports --module-name test -V 3.7 -o /var/folders/wd/gpgynm3j4h947l1mkjj3hx7h0000gq/T/tmpqnnkygz4/pyi/test.pyi --analyze-annotated --nofail --quick /Users/someone/code/pytype/test.py
File "/Users/someone/code/pytype/test.py", line 22, in foo: bad option in return type [bad-return-type]
           Expected: SomeProtocol
  Actually returned: SomeClass

For more details, see https://google.github.io/pytype/errors.html#bad-return-type.
ninja: build stopped: subcommand failed.
Leaving directory '/var/folders/wd/gpgynm3j4h947l1mkjj3hx7h0000gq/T/tmpqnnkygz4'
```

**Comment by rchen152** [comment]
Ah, we recently fixed a bug in pytype where decorating a protocol with runtime_checkable converted it to Any. Looks like that exposed this bug in protocol matching.

**Comment by rchen152** [comment]
The latest version of pytype doesn't raise an error on this code. I must confess that I don't know which of our recent changes fixed this, but I put in a couple reveal_type() calls, and it looks like pytype is now both inferring precise types (not Any) and successfully matching SomeClass to SomeProtocol.

**Comment by rchen152** [comment]
Wait, I think I misread the example, sorry!

**Comment by rchen152** [comment]
Yeah, this bug is still present. Here's a slightly reduced code snippet that triggers it:
```
from functools import lru_cache
from typing_extensions import Protocol

class SomeProtocol(Protocol):
    def foo(self) -> "SomeProtocol":
        raise NotImplementedError

class SomeClass:

    @lru_cache(maxsize=None)
    def foo(self) -> SomeProtocol:
        return SomeClass()  # pytype incorrectly raises [bad-return-type] on this line
```

**Comment by MatthiasThul** [comment]
Hi,

is there a chance to see this and related protocol tickets on the 2021 roadmap? Unfortunately this bug in particular prevents us from upgrading beyond version 2020.11.12 as we use protocols extensively and it would require an unreasonable amount of `typing: ignore` comments. Or do you see a better way to work around it for the moment?

Thanks!

**Comment by rchen152** [comment]
I won't get to pytype's larger protocol issues (like attribute matching) until next quarter, but I can take a look at this bug and see if there's a quick fix.

**Comment by MatthiasThul** [comment]
Thanks for addressing this one. I think I am running into some of the other issues you mention now - I opened https://github.com/google/pytype/issues/845 for it.
