### ISSUE TITLE
_HAS_DYNAMIC_ATTRIBUTES should be taken into account in protocol matching

### ISSUE THREAD

**Issue by MatthiasThul** [google/pytype#754]
Consider the following `test.py`

```python
from typing_extensions import Protocol, runtime_checkable

@runtime_checkable
class SomeProtocol(Protocol):
    def foo(self, x: int) -> int:
        raise NotImplementedError

class SomeMixin:
    def bar(self: SomeProtocol, x: int) -> int:
        return 2 * self.foo(x)
```

This passes inspection by mypy `0.790`. See in particular https://mypy.readthedocs.io/en/latest/more_types.html#mixin-classes where they explicitly suggest to use the host class protocol to annotate `self`.

This has not been supported by PyType in the past but up until version `2020.11.12`, adding `_HAS_DYNAMIC_ATTRIBUTES = True` to `SomeMixin` would result in a pass. Since `2020.11.23`, PyType fails with

```bash
Computing dependencies
Analyzing 1 sources with 0 local dependencies
ninja: Entering directory `/var/folders/wd/gpgynm3j4h947l1mkjj3hx7h0000gq/T/tmpfrxn9112'
[1/1] check test
FAILED: /var/folders/wd/gpgynm3j4h947l1mkjj3hx7h0000gq/T/tmpfrxn9112/pyi/test.pyi
/Users/someone/code/pytype/venv/bin/python -m pytype.single --imports_info /var/folders/wd/gpgynm3j4h947l1mkjj3hx7h0000gq/T/tmpfrxn9112/imports/test.imports --module-name test -V 3.7 -o /var/folders/wd/gpgynm3j4h947l1mkjj3hx7h0000gq/T/tmpfrxn9112/pyi/test.pyi --analyze-annotated --nofail --quick /Users/someone/code/pytype/test.py
Function SomeMixin.bar was called with the wrong arguments [wrong-arg-types]
         Expected: (self: SomeProtocol, ...)
  Actually passed: (self: SomeMixin, ...)
  The following methods aren't implemented on SomeMixin:
  foo

For more details, see https://google.github.io/pytype/errors.html#wrong-arg-types.
ninja: build stopped: subcommand failed.
Leaving directory '/var/folders/wd/gpgynm3j4h947l1mkjj3hx7h0000gq/T/tmpfrxn9112'
```

This is unexpected since `foo` should be considered a potentially dynamic attribute as well. I see that the [PyType suggestion](https://google.github.io/pytype/faq.html) regarding mixins is different but wonder if this change in behavior was deliberate and if yes, why.

**Comment by rchen152** [comment]
Ah, I think this is another issue caused by pytype now supporting typing_extensions.runtime_checkable. Before version `2020.11.23`, SomeProtocol was being treated as Any. If you remove `@runtime_checkable`, pytype reports the wrong-arg-types error even in earlier versions.

I agree that `_HAS_DYNAMIC_ATTRIBUTES` should be taken into account in protocol matching.
