### ISSUE TITLE
pyi parser crashes on file that imports typing.Literal inside version check

### ISSUE THREAD

**Issue by rchen152** [google/pytype#757]
See https://github.com/python/typeshed/pull/4807. The pytype test failed with the following error:
```
free(): invalid pointer
/home/runner/work/_temp/c2a28e77-7168-488e-8f26-da1cbba538c8.sh: line 1:  2734 Aborted                 (core dumped) ./tests/pytype_test.py
```
srittau fixed the failure with the following change: https://github.com/python/typeshed/pull/4807/commits/02dfcc69913bb0cb1bb689ae05c2180f4de6a161, which modified:
```
if sys.version_info >= (3, 9):
    from typing import Literal
```
to:
```
from typing_extensions import Literal
```

**Comment by Solumin** [comment]
I was able to reproduce this with:

```
git clone http://github.com/python/typeshed
cd typeshed
python3 tests/pytype_test.py
```

That is, with a completely fresh install, I'm still seeing the double free error.

Python version: 3.6.6
Pytype version: 2020.02.20
Typeshed commit: 3d1401

**Comment by Solumin** [comment]
Every time there are 10 or more errors found, the double free error appears.

**Comment by rchen152** [comment]
Is this still an issue with the new parser?

**Comment by rchen152** [comment]
I introduced an error to typeshed that causes pytype to report 56 errors and didn't manage to trigger this issue, so I think it's fixed...? I suggest we close it unless it comes up again.
