### ISSUE TITLE
RFE: add a .gitignore to output dir

### ISSUE THREAD

**Issue by scop** [google/pytype#759]
Would be good to automatically add a `.gitignore` to the output dir when creating it, e.g. with contents
```gitignore
# Automatically created by pytype
*
```
This way people wouldn't need to manually add it to their upper level gitignores. Many tools already do this for their similar dirs, mypy and pytest to name a couple.

**Comment by rchen152** [comment]
That sounds totally reasonable to me! I must confess, I didn't know until now that you could add a `.gitignore` to a subdirectory.

**Comment by UrielMaD** [comment]
Hi @rchen152 I'd like to take this issue :)

**Comment by rchen152** [comment]
Sweet, thank you for your interest in contributing to pytype! The path to the output directory is available as the "output" attribute on the configuration object (`conf`); it would probably make the most sense to add the `.gitignore` right after the directory is created here: https://github.com/google/pytype/blob/51e930ca7d29a73ede531129111fb600e761c8cc/pytype/tools/analyze_project/main.py#L76.

**Comment by UrielMaD** [comment]
Hello @rchen152 I just send a PR for adding the git ignore file to the output dir, I'm wondering if there's an specific configuration for the file that will be created.

The current configuration that I set is just what @scop suggested as example

**Comment by rchen152** [comment]
`*` seems fine to me; I don't think there's anything we specifically want to not be excluded.

**Comment by UrielMaD** [comment]
Nice. Let me know if there's something else that needs to be implemented!

**Comment by rchen152** [comment]
@UrielMaD Thank you for implementing this feature! It'll be in the next pytype release (first or second week of January).
