### ISSUE TITLE
Support bound methods in stubs

### ISSUE THREAD

**Issue by hauntsaninja** [google/pytype#761]
For instance,
```
class WorkingSet:
    def require(self, *requirements: _NestedStr) -> Sequence[Distribution]: ...

working_set: WorkingSet
require = working_set.require
```

This is something mypy supports and has come up a couple times in typeshed, since it reduces redundancy / allows changes to be made in only one place. e.g. https://github.com/python/typeshed/pull/4817, https://github.com/python/typeshed/blob/ac234f25927634e06d9c96df98d72d54dd80dfc4/stdlib/2and3/turtle.pyi#L284-L291 and https://github.com/python/typeshed/pull/4282#issuecomment-650477906

**Comment by rchen152** [comment]
Hmm, aliasing to a method of an instance of a class in the same file is relatively straightforward; I can probably get that done sometime this week. It gets trickier when the class is in another file, as we don't currently have a way of representing that.

**Comment by hauntsaninja** [comment]
Thanks for fixing this! Are you planning on adding support for bound methods when the class is in another file? (This came up again in a change to multiprocessing stubs https://github.com/python/typeshed/pull/5231)
