### ISSUE TITLE
ImportError name and path attributes not known

### ISSUE THREAD

**Issue by scop** [google/pytype#769]
```shellsession
$ pytype --version
2020.12.16
$ cat t.py 
try:
    import nonexistent
except ImportError as err:
    print(err.name)
    print(err.path)
$ pytype t.py | grep ^File
File "/tmp/t.py", line 2, in <module>: Can't find module 'nonexistent'. [import-error]
File "/tmp/t.py", line 4, in <module>: No attribute 'name' on ImportError [attribute-error]
File "/tmp/t.py", line 5, in <module>: No attribute 'path' on ImportError [attribute-error]
```

The `name` and `path` attributes were added in 3.3, typeshed has them.
https://docs.python.org/3.9/library/exceptions.html#ImportError

**Comment by parampatidar** [comment]
I'd like to work on this issue.

**Comment by martindemello** [comment]
@parampatidar great! it looks like an issue of us overriding a typeshed stub in our own builtins and doing an incomplete job of it. 

[this](https://github.com/google/pytype/blob/master/pytype/stubs/builtins/3/__builtin__.pytd#L975) is the relevant stub file definition; you will need to find the corresponding stub in [typeshed](https://github.com/python/typeshed/) and copy over its definition, then add a test to confirm that we are seeing the new definition.

**Comment by scop** [comment]
https://github.com/python/typeshed/blob/4f81ac10aec63e0e0672647f2369b4ee42d35f62/stdlib/3/builtins.pyi#L1300
