### ISSUE TITLE
open('foo', 'rb') treated as a file of str rather than bytes in Python 3

### ISSUE THREAD

**Issue by kamahen** [google/pytype#77]
The following illustrates a problem with `typing.AnyStr`, which is defined as `TypeVar('AnyStr', str, bytes)`. It seems to be only picking up the first type and ignoring the rest.

(There's a separate problem, that `IO.read()` doesn't seem to have a clear way of differentiating files opened in text and binary mode.)

```
$ pytype -V3.6 /tmp/z7.py 
File "/tmp/z7.py", line 8, in <module>: Function foo was called with the wrong arguments [wrong-arg-types]
  Expected: (src: bytes)
  Actually passed: (src: str)
```
```python
$ cat /tmp/z7.py
def foo(src: bytes) -> None:
    print(src)

def bar(src: str) -> None:
    print(src)

with open('foo', 'rb') as my_file:
    foo(my_file.read())
    bar(my_file.read())
```

**Comment by rchen152** [comment]
This seems to work now! When I run pytype over the code in question, it reports an error in `bar` rather than `foo`.
