### ISSUE TITLE
[Question] Why can't pytype infer the type of pd.read_excel(...) (method from pandas) even with source code?

### ISSUE THREAD

**Issue by Yuanhong-Lan** [google/pytype#774]
I have code like :
`data1 = pd.read_excel("./data/1.xlsx")
`
The inferred type of data1 is Any.
**Why?**   (I guess the reason maybe that there are no .pyi stubs for pandas in the project typeshed.)

Then I try to let pytype infer this with the source code of pandas.
I cut the source code of pandas from the library to my project, and modified the config file:
![1](https://user-images.githubusercontent.com/45310536/103094972-ee4c7380-4639-11eb-9f02-ac2a3c957d01.png)
![2](https://user-images.githubusercontent.com/45310536/103094979-f4425480-4639-11eb-9b7c-b4f5e95c2bfe.png)
![3](https://user-images.githubusercontent.com/45310536/103094981-f4daeb00-4639-11eb-8607-b48686f70d27.png)
And then run pytype:
![4](https://user-images.githubusercontent.com/45310536/103095109-65820780-463a-11eb-9157-54eb918fc3f4.png)
In this way, the inferred type of data1 is still Any.
**Why?**  (I guess this may be caused by the C part of pandas for pytype can't handle this part?)

platform: unbuntu 18.04
pytype version: 2020.12.2

**Comment by rchen152** [comment]
Yeah, pytype can't infer types for a C extension, only pure Python code. I did a quick Google search and didn't find any type stubs for pandas, so I don't think type information is available for pandas yet (or I may have missed it).

**Comment by Yuanhong-Lan** [comment]
Thank you so much !
