### ISSUE TITLE
MappingProxyType.keys() inferred as list

### ISSUE THREAD

**Issue by bentheiii** [google/pytype#775]
The following snippet:
```python
from types import MappingProxyType

d = MappingProxyType(dict(a=1, b=2))
k = d.keys() | (1, 2, 3)
print(k)
```
Runs fine but fails pytype because it thinks MappingProxyType.keys() is a list, when in truth it implements AbstractSet.
```
line 4, in <module>: unsupported operand type(s) for |: 'List[nothing]' and 'Tuple[int, int, int]' [unsupported-operands]
  No attribute '__or__' on List[nothing] or '__ror__' on Tuple[int, int, int]
```

Tested on pytype 2020.12.16 on WSL

**Comment by rchen152** [comment]
This bug appears to be caused by these lines:
https://github.com/google/pytype/blob/2f1d1a357bada38e8969782a2f9bc59c20a79bc8/pytype/stubs/builtins/3/typing.pytd#L280-L283
The internal bug that the TODO links to says:
> items, keys and values on Mapping should return AbstractSets, not lists. However, this causes some unexpected behavior when the dict is mutated, which may be due to how generic pytd classes are matched.
