### ISSUE TITLE
Couldn't import pyi for 'importlib.metadata' [pyi-error]

### ISSUE THREAD

**Issue by kujaomega** [google/pytype#779]
I followed the https://google.github.io/pytype/errors.html#pyi-error and reported the error.

Seems that an error is triggering with the following command:
**/python3 -m pytype.single --disable import-error,not-supported-yet --imports_info **/att.__init__.imports --module-name **.__init__ -V 3.8 -o **/__init__.pyi --analyze-annotated --check-attribute-types --check-container-types --check-parameter-types --check-variable-types --nofail --quick **/__init__.py

File "/**/__init__.py", line 1, in <module>: Couldn't import pyi for 'importlib.metadata' [pyi-error]
  Couldn't find Context in importlib.metadata

**Comment by rchen152** [comment]
Sorry for the slow response! (Just got back from the holidays.) Seems to be a parse error caused by Context not being referred to by its fully qualified name, which we didn't catch because typeshed's pytype test is running only in 3.6. The fix should be fairly simple.

**Comment by rchen152** [comment]
Ok, this has been patched in typeshed. pytype will pick up the change once its typeshed pin is updated past https://github.com/python/typeshed/commit/94b7eac67585ae8c1e2a057cc2e19fea9f4ae4eb.
