### ISSUE TITLE
setup.py install Assertion Error with Python 3.6.5

### ISSUE THREAD

**Issue by BlackFrog1** [google/pytype#78]
Trying to install on Windows 10 and Python 3.6.5 produce the following error:

> C:\GitHub\pytype>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 65, in <module>
    package_data={'pytype': get_builtin_files()},
  File "setup.py", line 34, in get_builtin_files
    check=['stdlib', '2', '*.pyi'])
  File "setup.py", line 24, in scan_package_data
    assert os.path.join(path, *check) in result
AssertionError

https://github.com/google/pytype/blob/ca771c8645734f610f4b30034feaea09f7974c5b/setup.py#L24

https://github.com/google/pytype/blob/ca771c8645734f610f4b30034feaea09f7974c5b/setup.py#L33-L34

https://github.com/google/pytype/blob/ca771c8645734f610f4b30034feaea09f7974c5b/setup.py#L65

**Comment by martindemello** [comment]
sounds like it's having problems with the typeshed submodule. could you try running `git submodule init; git submodule update`, see if that gives any errors, and if not try running `setup.py` again?

**Comment by LaughingLove** [comment]
I am having the same problem on python 3.6.5 on windows 10.

```
F:\pytype (master)
λ git submodule init

F:\pytype (master)
λ git submodule update

F:\pytype (master)
λ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 69, in <module>
    package_data={'pytype': get_builtin_files()},
  File "setup.py", line 34, in get_builtin_files
    check=['stdlib', '2', '*.pyi'])
  File "setup.py", line 24, in scan_package_data
    assert os.path.join(path, *check) in result
AssertionError
```

**Comment by martindemello** [comment]
thanks, i had forgotten we were relying on a symlink and that those didn't work on windows! i'll push out a fix for it.
