### ISSUE TITLE
Incorrect raising of Function type comments cannot be used with annotations [redundant-function-type-comment]

### ISSUE THREAD

**Issue by mattseymour** [google/pytype#783]
Python version: 3.8.6
Pytype version: 2020.12.23
Tested in python:3.8.6-buster, OSX virtual env

I have provided a minimal script which helps explain the issue. I am getting an error where by commenting or uncommenting a line of code is causing `redundant-function-type-comment` errors to be thrown. Which appears to be a little inconsistent (and incorrect).

❌ The following code, run with the command will result in the error:
```
root@a93364f24f3b:/opt/app# pytype test.py
Computing dependencies
Analyzing 1 sources with 0 local dependencies
ninja: Entering directory `/opt/app/.pytype'
[1/1] check test
FAILED: /opt/app/.pytype/pyi/test.pyi 
/venv/bin/python -m pytype.single --disable pyi-error --imports_info /opt/app/.pytype/imports/test.imports --module-name test -V 3.8 -o /opt/app/.pytype/pyi/test.pyi --analyze-annotated --nofail --quick /opt/app/test.py
File "/opt/app/test.py", line 7: Function type comments cannot be used with annotations [redundant-function-type-comment]

```
Code - test.py
```
from typing import Dict


def a() -> Dict[str, str]:
    # some_variable = ''
    # Array is going to be encoded as a string, we do this because of legacy
    cast_type: Dict[str, str] = {
        'boolean': 'string',
        'Float': 'float',
        'Array': 'string',
    }

    return cast_type


print(a())
```

✅ Now if i were to modify the code in the following way (uncomment the `some_variable`). Pytpye passes the check as valid.

Command:
```
root@a93364f24f3b:/opt/app# pytype test.py
Computing dependencies
Analyzing 1 sources with 0 local dependencies
ninja: Entering directory `/opt/app/.pytype'
[1/1] check test
Leaving directory '/opt/app/.pytype'
Success: no errors found
```

Code - test.py
```
from typing import Dict


def a() -> Dict[str, str]:
    some_variable = ''
    # Array is going to be encoded as a string, we do this because of legacy
    cast_type: Dict[str, str] = {
        'boolean': 'string',
        'Float': 'float',
        'Array': 'string',
    }

    return cast_type


print(a())
```

Making the following single changes to the original code:
✅  Removing the type attached to `cast_type: Dict[str, str] = {` results in a pass.
✅ Adding a type to `some_variable -> some_variable: str` results in a passes.
❌ Reming `some_variable` and removing code comment results in a fail.

**Comment by rchen152** [comment]
Sorry for the slow response. This seems to be caused by the following line:
https://github.com/google/pytype/blob/1b13a04b9f982bc4d4fb538b96902c8a0a4dbeea/pytype/blocks.py#L343
It's meant to get the line number of the first line of code in the function body. What it actually does is get the line number of the first opcode, which, as it turns out, can be on a later line. What we actually want is `min(op.line for op in fn_code.co_code)` (but we should probably store that somewhere so we don't have to calculate it more than once).

**Comment by rchen152** [comment]
On second thought, I believe the visitor visits every function exactly once, so there's no need to store the line number unless we want to reuse it. Given that, I'm going to tag this as a good first issue, since it's localized and has a clear path forward.

**Comment by parampatidar** [comment]
I'd like to fix this issue.
