### ISSUE TITLE
Support PEP 604: Allow writing union types as X | Y

### ISSUE THREAD

**Issue by rchen152** [google/pytype#785]
PEP: https://www.python.org/dev/peps/pep-0604/

Introduces new syntax that we should support as soon as possible so typeshed can start using it (https://github.com/python/typeshed/issues/4819).

**Comment by commentator8** [comment]
Hi - i see the code seems to be checking if the context is 3.10 `if ctx.python_version >= (3, 10) and name == "__or__":` - we are using `from future import __annotations__` in python 3.9. Am i correct that it still wont work for 3.9 then?

**Comment by martindemello** [comment]
Hi @commentator8 , that's right, the feature made it into python in 3.10 so we don't support it in earlier versions, even with `from future import __annotations__` or explicit string annotations.

**Comment by commentator8** [comment]
Good to know. Thanks. I've recently disabled pytype for our company's pipelines and was hoping to bring it back.
