### ISSUE TITLE
No extension definition for new C++ extension version of pytype.typegraph.cfg

### ISSUE THREAD

**Issue by mjpieters** [google/pytype#79]
dcabf54dce8006e7223866c7f20faa29a1dfd10c replaced the pure-python `pytype.typegraph.cfg` module with a C++ version, but there is no `Extension` definition for these in `setup.py`.

This leaves the project in a broken state, all `from pytype.typegraph import cfg` imports now fail.

**Comment by mjpieters** [comment]
I see there's a lot more wrong:

* `string` should be `std::string`
* `#include "third_party/py/pytype/typegraph/typegraph.h"` > `#include "typegraph.h"`
* `#include "third_party/absl/memory/memory.h"` > `#include "absl/memory/memory.h"`
* document that abseil is now required

and I'm not entirely sure how the tests are to be run.

**Comment by rchen152** [comment]
Thanks for flagging this!  We've decided to add back cfg.py for now while we figure out the issues with the C++ extension, so the cfg imports should be working again.

**Comment by rchen152** [comment]
We're successfully using the C++ extension now.
