### ISSUE TITLE
Support PEP 593: Flexible Function and Variable Annotations

### ISSUE THREAD

**Issue by rchen152** [google/pytype#791]
PEP: https://www.python.org/dev/peps/pep-0593/
This looks like it entails adding an Annotated type that returns its first parameter and throws away the second.

This would be a good first issue for someone interested in learning how to support new typing features in pytype, since it requires going through all the steps described [here](https://google.github.io/pytype/developers/features.html) for adding a new feature, but none of the steps in this case should be particularly tricky.

**Comment by mlevesquedion** [comment]
I would be interested in implementing this feature.

**Comment by rchen152** [comment]
Great! I think implementing this will require:
* Adding a definition for `Annotated` to the typing stubs in `pytype/stubs/builtins/`
* Adding an implementation of `Annotated` to `pytype/overlays/typing_overlay.py`. You'll probably want to inherit from `abstract.AnnotationClass` and override `_build_value` (similar to what the implementation of `Union` does: https://github.com/google/pytype/blob/644f04dc7cdd3ccb836e5758f175b12028fbb888/pytype/overlays/typing_overlay.py#L46).
* Adding an alias for `Annotated` in `pytype/overlays/typing_extensions_overlay.py`, so it can be used in versions prior to 3.9.

Full instructions are here: https://google.github.io/pytype/developers/features.html. (Not all of the listed steps apply in this case.) This documentation is new, so please ask if anything doesn't make sense!

**Comment by mlevesquedion** [comment]
Sounds good. Thanks a lot for the directions!

**Comment by rchen152** [comment]
@mlevesquedion Thanks again for implementing this! It'll be in the next pytype release (tomorrow or Friday, if nothing unexpected comes up).

**Comment by mlevesquedion** [comment]
Thank you for your help! :slightly_smiling_face: I look forward to contributing again if I get the chance.
