### ISSUE TITLE
No module named 'pytype.ast'

### ISSUE THREAD

**Issue by maldil** [google/pytype#801]
I am using [annotate_ast.annotate_source](https://github.com/google/pytype/blob/18d28bab9e61ee38b30f8b04df599a77e1d68154/pytype/tools/annotate_ast/annotate_ast.py#L8) to obtain inferred types. I was using pytype version _2020.10.8_ and thought to upgrade to the latest version. The code throws an exception **No module named 'pytype.ast'** from this [line](https://github.com/google/pytype/blob/18d28bab9e61ee38b30f8b04df599a77e1d68154/pytype/tools/traces/traces.py#L11). The module `pytype.ast` is available in GitHub repo. But it is not available in the PIP version that was downloaded to the python virtual environment (through `pip install pytype`). May I know whether you have stopped shipping the module `pytype.ast` to the production (PIP repository)?

On a different note, Is there a mailing list to ask questions on this project?

**Comment by rchen152** [comment]
Oops, we definitely didn't intentionally remove pytype/ast/! Maybe we need to add it to MANIFEST.in? (https://github.com/google/pytype/blob/master/MANIFEST.in)

The mailing list is pytype@googlegroups.com.

**Comment by rchen152** [comment]
Actually, the problem seems to be that `ast/` is missing an `__init__.py` file.

**Comment by maldil** [comment]
Oh yes, `__init__.py` was there in 2020.10.8. Will you be able to make a release with this file soon? Or when is the next release date? Thank you!

**Comment by rchen152** [comment]
If the nightly tests look good, I can cut a release tomorrow. Otherwise, the next release will probably be mid-next week.

**Comment by maldil** [comment]
Thanks. I will wait for the release. 
Looking forward to it :)
