### ISSUE TITLE
AssertionError: Don't know how to match <'NamedType'> against <'Literal'>

### ISSUE THREAD

**Issue by maldil** [google/pytype#802]
An Assertion fired at the [line](https://github.com/google/pytype/blob/18d28bab9e61ee38b30f8b04df599a77e1d68154/pytype/pytd/type_match.py#L354) 
Assertion =
``` 
File "..../PyType/lib/python3.7/site-packages/pytype/pytd/type_match.py", line 357, in _match_type_against_type
    type(t1), type(t2)))
pytype.tools.annotate_ast.annotate_ast.PytypeError: Pytype error: AssertionError: Don't know how to match <class 'pytype.pytd.pytd.NamedType'> against <class 'pytype.pytd.pytd.Literal'>
```
Steps to reproduce.
1. Save following code to a file. Use 'FILE_PATH' = path to the file, 'FOLDER_PATH' = project path, "FILE_NAME'=filename .
 ```
def main():
    f = open("./file.txt", "r")
    for x in f:
        print(x)
    f.close()



if __name__ == "__main__":
    main()
```
2. Run `pytype --pythonpath='FOLDER_PATH' --no-report-errors --keep-going --protocols --output='OUTPUT'  FILE_PATH`
3. Run the method [annotate_ast.annotate_source(source, ast_factory, pytype_options)](https://github.com/google/pytype/blob/18d28bab9e61ee38b30f8b04df599a77e1d68154/pytype/tools/annotate_ast/annotate_ast.py#L8) 
as below 
```
  with open(FILE_PATH, 'r') as f:
    src = f.read()
 source = textwrap.dedent(src.lstrip('\n'))
 pytype_options = config.Options.create(python_version=(3,7),nofail=True,protocols=True,
                                         imports_map= OUTPUT +'/imports/'+ FILE_NAME)
 module = annotate_ast.annotate_source(source, ast_factory, pytype_options)

```

**Comment by rchen152** [comment]
@maldil Your fix was merged in https://github.com/google/pytype/pull/807. Thanks!
