### ISSUE TITLE
merge-pyi ignores variable annotations

### ISSUE THREAD

**Issue by unclebob7** [google/pytype#808]
![image](https://user-images.githubusercontent.com/29818505/104794106-845e5e80-57e0-11eb-8706-8da3d98e4f85.png)
`merge-pyi` does nothing when I try to annotate the original .py files.

**Comment by rchen152** [comment]
What are the contents of `test.py` and `test.pyi`? merge-pyi won't overwrite the original file unless you pass in `-i` (`--in-place`), but it should be printing out a diff to stdout.

**Comment by unclebob7** [comment]
![image](https://user-images.githubusercontent.com/29818505/104794349-03a06200-57e2-11eb-9206-48001b49339d.png)
I have only declared three variables as above in test.py, I have tried -i but it won't work. Thanks
![image](https://user-images.githubusercontent.com/29818505/104794382-419d8600-57e2-11eb-9474-5256a83c8994.png)

**Comment by unclebob7** [comment]
FYI this is the content of test.pyi
![image](https://user-images.githubusercontent.com/29818505/104794658-f4baaf00-57e3-11eb-9747-8c25ccb2f1eb.png)

**Comment by rchen152** [comment]
Thanks for the additional information! The problem seems to be that merge-pyi is ignoring variable annotations.
