### ISSUE TITLE
false alarm after finally block

### ISSUE THREAD

**Issue by kcwu** [google/pytype#809]
```
def error():
  raise Exception

def func():
  try:
    output = error()
  finally:
    pass
  return output
```
The `error` function raises an exception, so the control flow exits `func` immediately after the `finally` block. It won't reach the case of `output` undefined.

```
$ pytype --version
2021.01.14
$ /usr/bin/python3 -m pytype.single f.py
File "f.py", line 9, in func: Name 'output' is not defined [name-error]
```

**Comment by rchen152** [comment]
Interesting. I believe we intentionally analyze code after a try block to avoid missing errors, but we shouldn't both exit the block early (without storing `output`) and go on to report an error when `output` is used.

**Comment by rchen152** [comment]
This appears to have been fixed! Likely by the improvements to try/except handling in pytype-2021.07.19.
