### ISSUE TITLE
Clarification for the example of checking __init__.py in README

### ISSUE THREAD

**Issue by HeliWang** [google/pytype#82]
I can see the parameter -M is explained as:
````
  -M MODULE_NAME, --module-name=MODULE_NAME
                        Name of the module we're analyzing. For __init__.py
                        files the package should be suffixed with '.__init__'.
                        E.g. 'foo.bar.mymodule' and 'foo.bar.__init__'
````

Can anyone provide an example of using -M parameter? Is the parameter used only when checking a python package? Thanks.

**Comment by HeliWang** [comment]
Also a follow-up question:
I'd love to be able to let pytype handle a whole package, or a program where it's not totally obvious what the entry point is (or if there is a single entry point), and have it type-check the whole thing. Is there a way to let pytype  accepts a list of folders/files? Thanks.

**Comment by martindemello** [comment]
-M is useful when the full module name of a python file does not match the path you use to pass it to pytype. Here's a small example

````
$ tree foo
foo
├── bar.py
├── baz.py
└── baz.pyi

$ cat foo/bar.py
from . import baz
a = baz.f()

$ cd foo
$ pytype bar.py -o - --pythonpath=..
from typing import Any

a = ...  # type: Any
baz = ...  # type: Any
File "bar.py", line 1, in <module>: Can't find module '.baz'. [import-error]
````

Since we have passed in `bar.py` as an argument rather than `foo/bar.py`, pytype does not infer the module name to be `foo.bar` and therefore does not resolve `from . import baz` as importing `foo.baz`. Passing in the module name fixes that:

````
$ pytype bar.py -o - --pythonpath=.. -M foo.bar
a = ...  # type: int
baz = ...  # type: module
````

**Comment by martindemello** [comment]
For your second question, we are in the process of releasing a [pytype-all](https://github.com/google/pytype/tree/master/pytype/tools/analyze_project) tool for exactly that use case. Give it a try and let us know if you have any problems with it.
