### ISSUE TITLE
TypedDict in 3.8 gives unexpected error?

### ISSUE THREAD

**Issue by IanVermes** [google/pytype#832]
@rchen152 Forgive me for the naive question, but am I correct that TypedDict support from the `typing` module is not supported by PyType (as of version `2021.02.09` while running against Python 3.8)? Issue #680 corroborates this but the error message I get is unclear.

I get an import-error rather than a not supported error, which is confusing me. Equally I may be doing something utterly wrong!

I get the following 
```
$ pytype -V 3.8
...
Can't find module 'typing.TypedDict'. [import-error]
```
```python
# some_file.py
from typing import TypedDict

Keywords = TypedDict(
    "Keywords",
    {
        "foo": str,
        "bar": str,
        "bat": bool,
    },
)
```

**Comment by rchen152** [comment]
Yeah, we should be reporting `[not-supported-yet]`, not `[import-error]`. To fix this, we'd need to add a definition for TypedDict to https://github.com/google/pytype/blob/master/pytype/stubs/builtins/2and3/typing.pytd and a `not_supported_yet` entry in https://github.com/google/pytype/blob/962a1ac118a4daa660170a54cad5ce3ad86a1c1f/pytype/overlays/typing_overlay.py#L748.
