### ISSUE TITLE
container-type-mismatch ignores type narrowing (false positive)

### ISSUE THREAD

**Issue by Cebtenzzre** [google/pytype#835]
When an if statement or assertion is used to narrow a type which was previously a `Union` or `Optional`, pytype with `--check-container-types` reports a container-type-mismatch error that appears to disagree with the actual revealed type.

#### Example Code
```python
from typing import List, Optional

def check(name: str) -> Optional[str]:
    return None if name.endswith('2') else name

names: List[str] = []

for name in ('name1', 'name2'):
    n = check(name)
    if n is not None:
        reveal_type(n)
        names.append(n)
```
#### Expected Behavior
pytype does not report an error on the `names.append` call because the type of `n` has been narrowed to `str`.

#### Actual Behavior
```
$ pytype-single repr.py --check-container-types
File "repr.py", line 11, in <module>: str [reveal-type]
File "repr.py", line 12, in <module>: New container type for names does not match type annotation [container-type-mismatch]
  Container: List[_T]
  Allowed contained types (from annotation List[str]):
    _T: str
  New contained types:
    _T: None
  

For more details, see https://google.github.io/pytype/errors.html.
```

The container type check seems to ignore type narrowing, even though `reveal_type` shows that pytype knows that the type of `n` must be `str`, not `Optional[str]`.

Replacing the if statement with `assert n is not None` yields the same error. Replacing `None` with `0` and `n is not None` with `isinstance(n, str)` (and updating the annotations accordingly) check gives the same error but with `_T: int` instead of `_T: None`.

#### Software Versions
pytype (2021.02.09) - latest release as of this writing, also tested on 2020.12.02
Python 3.8

**Comment by rchen152** [comment]
Oh wow, thanks for catching this. We don't prefilter possible types because that's too slow, but we should do the same thing for container_type_mismatch that we do for attribute_error: once we're at the point of actually logging an error, we should do an extra check to see if the type is actually visible.
