### ISSUE TITLE
pytype complains about Python 3.9 generic type annotation

### ISSUE THREAD

**Issue by dclong** [google/pytype#839]
I'm using Python 3.7 and have the following import. 
```
from __future__ import annotations
```
Then I used `tuple[int, int]` but pytype complains about it. 
![image](https://user-images.githubusercontent.com/824507/108638541-af257d80-7444-11eb-832e-93bf7f280c4c.png)

**Comment by rchen152** [comment]
The problem seems to be that typing.Tuple has an entry in the typing overlay, which is skipped for builtins.tuple.
