### ISSUE TITLE
Protocol variable matching fails

### ISSUE THREAD

**Issue by MatthiasThul** [google/pytype#845]
Consider the following example:

```python
from dataclasses import dataclass
from typing_extensions import Protocol

class SomeProtocol(Protocol):
    foo: int

@dataclass
class SomeClass:
    foo: int

def bar(x: SomeProtocol) -> int:
    return x.foo

bar(SomeClass(1))
```

PytType `2021.02.23` fails with

```bash
File "test.py", line 14, in <module>: Function bar was called with the wrong arguments [wrong-arg-types]
         Expected: (x: SomeProtocol)
  Actually passed: (x: SomeClass)
```
  
MyPy `0.812` passes. The last PyType version that passes is `2020.11.12` and the first that fails is `2020.11.23`. The above syntax should be valid according to the [specs](https://www.python.org/dev/peps/pep-0544/#id25). 

Changing to the alternative (see [here](https://www.python.org/dev/peps/pep-0544/#id25)) doesn't help either:

```python
class SomeProtocol(Protocol):
    @property
    def foo(self) -> int:
        raise NotImplementedError
```

**Comment by MatthiasThul** [comment]
This seems related to https://github.com/google/pytype/issues/524.

**Comment by rchen152** [comment]
This looks like a combination of #524 and #523. Since pytype is ignoring non-method attributes, it thinks SomeProtocol is empty, and it doesn't recognize empty protocols as protocols.

Closing in favor of the existing issues for those bugs.
