### ISSUE TITLE
import-error when importing from email

### ISSUE THREAD

**Issue by pepoluan** [google/pytype#846]
I have been having problems with this file: [handlers.py of aiosmtpd](https://github.com/pepoluan/aiosmtpd/blob/a8ae8d835a3fe3d62d694891f1e968354f019053/aiosmtpd/handlers.py#L21)

Relevant snippet:

```python
# Copyright 2014-2021 The aiosmtpd Developers
# SPDX-License-Identifier: Apache-2.0

"""Handlers which provide custom processing at various events.

At certain times in the SMTP protocol, various events can be processed.  These
events include the SMTP commands, and at the completion of the data receipt.
Pass in an instance of one of these classes, or derive your own, to provide
your own handling of messages.  Implement only the methods you care about.
"""

import asyncio
import io
import logging
import mailbox
import os
import re
import smtplib
import sys
from argparse import ArgumentParser
from email import message_from_bytes, message_from_string  ### <== Here
from email.message import Message
from typing import AnyStr, Dict, List, Tuple, Type, TypeVar
```

The error I get when running `pytype aiosmtpd/handlers.py` from the project root:

```python
% pytype aiosmtpd/handlers.py
Computing dependencies
Analyzing 1 sources with 3 local dependencies
ninja: Entering directory `/home/pepoluan/projects/aiosmtpd/.pytype'
[1/1] check aiosmtpd.handlers
FAILED: /home/pepoluan/projects/aiosmtpd/.pytype/pyi/aiosmtpd/handlers.pyi
/home/pepoluan/.pyenv/versions/3.8.8/bin/python3.8 -m pytype.single --disable not-supported-yet --imports_info /home/pepoluan/projects/aiosmtpd/.pytype/imports/aiosmtpd.handlers.imports --module-name aiosmtpd.handlers -V 3.8 -o /home/pepoluan/projects/aiosmtpd/.pytype/pyi/aiosmtpd/handlers.pyi --analyze-annotated --nofail --quick /home/pepoluan/projects/aiosmtpd/aiosmtpd/handlers.py
File "/home/pepoluan/projects/aiosmtpd/aiosmtpd/handlers.py", line 21, in <module>: Can't find module 'email.message_from_bytes'. [import-error]
File "/home/pepoluan/projects/aiosmtpd/aiosmtpd/handlers.py", line 21, in <module>: Can't find module 'email.message_from_string'. [import-error]
```

Of course this is very strange because those functions are exported:

```python
% python
Python 3.8.8 (default, Feb 20 2021, 21:22:10)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import email
>>> dir(email)
['__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'message_from_binary_file', 'message_from_bytes', 'message_from_file', 'message_from_string']
>>> email.message_from_bytes
<function message_from_bytes at 0x7fe0c7934ee0>
>>> email.message_from_string
<function message_from_string at 0x7fe0c7934e50>
>>>
```

Can someone help point me where I went wrong?

**Comment by pepoluan** [comment]
I worked around this by adding the pragma `# pytype: disable=import-error` for that line, but that makes me uneasy as it's implied that pytype no longer "sees" those functions and thus _might_ miss other errors.

So I still want to dig down into the root cause and fix it, if possible.

**Comment by pepoluan** [comment]
Update: Out of curiosity, I tried removing the line:
```python
from argparse import ArgumentParser
```
I also had to remove many `: ArgumentParser` annotations ...

... but now it works!

I wonder why importing `ArgumentParser` causes trouble with pytype...

**Comment by pepoluan** [comment]
The only thing that worked (that is, without using the pragma), is to inline the `message_from_bytes` and `message_from_string` functions.

So rather than doing:
```python
from email import message_from_bytes, message_from_string
```

Now I do:
```python
from email.parser import BytesParser, Parser

def message_from_bytes(s, *args, **kws):
    return BytesParser(*args, **kws).parsebytes(s)

def message_from_string(s, *args, **kws):
    return Parser(*args, **kws).parsestr(s)
```

**Comment by rchen152** [comment]
Sorry for the slow response! Could you provide more information about the contents of handler.py? I tried running pytype on the first code snippet you provided, and also tried cloning https://github.com/pepoluan/aiosmtpd and running pytype on aiosmtpd/handlers.py, and neither of those generated the error you're seeing. I see that your snippet contains a `from argparse import ArgumentParser` line that isn't in https://github.com/pepoluan/aiosmtpd/blob/master/aiosmtpd/handlers.py; are you working on some in-progress change that pytype is erroring on?

**Comment by pepoluan** [comment]
> Sorry for the slow response! Could you provide more information about the contents of handler.py? I tried running pytype on the first code snippet you provided, and also tried cloning https://github.com/pepoluan/aiosmtpd and running pytype on aiosmtpd/handlers.py, and neither of those generated the error you're seeing. I see that your snippet contains a `from argparse import ArgumentParser` line that isn't in https://github.com/pepoluan/aiosmtpd/blob/master/aiosmtpd/handlers.py; are you working on some in-progress change that pytype is erroring on?

If you've cloned my repo, try checking out `a8ae8d8`

**Comment by rchen152** [comment]
Thanks, that did the trick! Turns out what's tripping pytype up is the import of `email._header_value_parser` in aiosmtpd.smtp - pytype creates an empty `email/__init__` stub when it sees `email/_header_value_parser` in the imports map for handlers.py. A smaller example of the bug:
```
# foo.py
import email._header_value_parser
```
```
# bar.py
from email import message_from_bytes
import foo
```
Running `pytype bar.py` leads to:
```
File "bar.py", line 1, in <module>: Can't find module 'email.message_from_bytes'. [import-error]
```

**Comment by pepoluan** [comment]
Awesome! Glad to help you figure that out.

That said, the lines `import email._header_value_parser` in aiosmtpd.smtp _and_ `from email import message_from_bytes` had already been there for quite some time, e.g. in the current master's [smtp.py](https://github.com/aio-libs/aiosmtpd/blob/986127ff274d36a9059d5f8676b45ed7e6c00c90/aiosmtpd/smtp.py#L17) and [handlers.py](https://github.com/aio-libs/aiosmtpd/blob/986127ff274d36a9059d5f8676b45ed7e6c00c90/aiosmtpd/handlers.py#L18), yet [pytype did not complain](https://github.com/aio-libs/aiosmtpd/runs/1977004291?check_suite_focus=true) (open the "Static code checking" step).

So there seems to be another thing that triggered this change of behavior.
