### ISSUE TITLE
Use of AnyStr can create duplicate TypeVar definitions

### ISSUE THREAD

**Issue by Cebtenzzre** [google/pytype#847]
When `typing.AnyStr` (or `typing._T_IO`) is referenced in by two functions in separate modules, and one function is imported into the other module, pytype generates a `.pyi` file with multiple identical definitions of `AnyStr`, and fails with a ParseError if that `.pyi` file is read.
Related to #159

#### Example Code
a.py:
```python
from typing import AnyStr

def foo(x: AnyStr) -> AnyStr:
    return x
```
b.py:
```python
from typing import AnyStr
from a import foo

def bar(x: AnyStr) -> AnyStr:
    return x
```
c.py:
```python
import b
```
#### Expected Behavior
pytype generates `b.pyi` with _one_ definition of AnyStr and successfully parses it.

#### Actual Behavior
```
$ pytype c.py
ninja: Entering directory `/tmp/repr/.pytype'
[1/3] infer a
[2/3] infer b
[3/3] check c
FAILED: /tmp/repr/.pytype/pyi/c.pyi 
/usr/bin/python3.8 -m pytype.single --imports_info /tmp/repr/.pytype/imports/c.imports --module-name c -V 3.8 -o /tmp/repr/.pytype/pyi/c.pyi --analyze-annotated --nofail --quick /tmp/repr/c.py
File "/tmp/repr/c.py", line 1, in <module>: Couldn't import pyi for 'b' [pyi-error]
    File: "/tmp/repr/.pytype/pyi/b.pyi", line None
  ParseError: Duplicate top-level identifier(s): AnyStr

For more details, see https://google.github.io/pytype/errors.html#pyi-error.
ninja: build stopped: subcommand failed.
Computing dependencies
Analyzing 1 sources with 2 local dependencies
Leaving directory '/tmp/repr/.pytype'
$ cat .pytype/pyi/b.pyi
# (generated with --quick)

from typing import TypeVar

AnyStr = TypeVar('AnyStr', str, bytes)
AnyStr = TypeVar('AnyStr', str, bytes)

def bar(x: AnyStr) -> AnyStr: ...
def foo(x: AnyStr) -> AnyStr: ...
```

If AnyStr is imported from a definition in a local module, there is no error. It seems to be specific to TypeVars defined in `.pytd` stubs which have constraints or an upper bound: `typing.AnyStr` (constraints) and `typing._T_IO` (upper bound) exhibit this issue but `typing._T` (no constraints or bound) and `statistics._NumberT` (not in any `.pytd`) do not.

#### Software Versions
pytype (2021.02.23) - latest release as of this writing
Python 3.8

**Comment by rchen152** [comment]
The problem is that we're not deduplicating the two instances of AnyStr properly because their representations are not completely identical. Should be able to fix this by deduplicating on name instead.
