### ISSUE TITLE
[QUESTION] How to programmatically query return type and parameter type of functions?

### ISSUE THREAD

**Issue by Risira** [google/pytype#854]
I want to programmatically query return type and parameter type of functions
For example

```
def foo(x,c):
   x = x+1
   c = c+2
   return x+c

class Database():
    def __init__(self, ):


    def commit_to_db(self,para1,para2):
         para3 = para1+para2
         return para3
```
How can I query return type of `foo(x,c)` and type of parameters `x, c`?
How can I query return type of `commit_to_db(self,para1,para2) `and type of parameters `para1,para2`?

If this is possible, Is there a particular API in pytype to do this?

Thanks you in advance!

**Comment by rchen152** [comment]
I don't know if this is exactly what you're looking for, but:
* When pytype runs, it produces type stubs (by default, located in a `.pytype/pyi/` directory in the directory in which pytype was run) with types for all top-level module elements. pytype doesn't infer function parameter types, but you can turn on an experimental option to do so with the `--protocols` flag.
* The [traces](https://github.com/google/pytype/tree/master/pytype/tools/traces) library can be used to access pytype's local type information, although it is incomplete.

However, looking at your example, I suspect pytype can't infer satisfactory types for your use case. For:
```
def foo(x,c):
   x = x+1
   c = c+2
   return x+c
```
the best it could do would be something like:
```
from typing import Any, Protocol
class Addable(Protocol):
  def __add__(self, other): ...
def foo(x: Addable, c: Addable) -> Any: ...
```
and pytype isn't even smart enough to generate its own protocols yet.
