### ISSUE TITLE
More specific stub files

### ISSUE THREAD

**Issue by xiaoxiae** [google/pytype#861]
Currently, running `pytype -V 3.8 test.py` on the file

```py
def function():
    x = 1

    return 123
```

Yields the following:
```py
# (generated with --quick)

def function() -> int: ...
```

However, I would expect that the following is produced:
```py
# (generated with --quick)

def function() -> int: ...
    x: int
```

**Comment by rchen152** [comment]
Local variables in function bodies don't belong in type stubs, as they're not part of the function's public interface. For more information on type stubs, typeshed's [CONTRIBUTING.md](https://github.com/python/typeshed/blob/master/CONTRIBUTING.md) and the draft [Type Stubs PEP](https://github.com/srittau/type-stub-pep/blob/type-stub-pep/pep-9999.rst) are good references.
