### ISSUE TITLE
Less directory info in output /home/USERNAME/ 

### ISSUE THREAD

**Issue by igouy** [google/pytype#863]
Would prefer not to have `/home/USERNAME/ in log files

```
~/.local/bin/pytype .
ninja: Entering directory `/home/USERNAME/aaa/bbb/ccc/ddd/.pytype'
[1/1] check pidigits.python3-3
Computing dependencies
Analyzing 1 sources with 0 local dependencies
Leaving directory '/home/USERNAME/aaa/bbb/ccc/ddd/.pytype'
Success: no errors found
```

**Comment by rchen152** [comment]
The `Entering directory` message appears to use the exact path passed to ninja, so changing https://github.com/google/pytype/blob/a7e558c17456d109478bbd02fef1e50a410c60ca/pytype/tools/analyze_project/pytype_runner.py#L351 to be the relative path removes the extra directory info. I'll send out a fix.
