### ISSUE TITLE
[QUESTION]Can we use PyType as a library in Python scripts 

### ISSUE THREAD

**Issue by MLEdits** [google/pytype#865]
I am trying to use `pytype` as a library in my python script. Since I could not figure out this,  I use python subprocess as an alternative. But this alternative is not efficient and it is ugly. 

Below is how I use the `subprocess`.
```subprocess.run(['pytype','--pythonpath='+project_path,'--python-version='+py_version_s,'--no-report-errors','--keep-going','--protocols','--output='+storage,python_file_path], shell=False,env=env,cwd=os.path.dirname(os.path.realpath(__file__)))```

Is there a way to write all the configurations into a `config.Options` object and invoke the relevant function to analyze a particular python file.

The command line argument that I am trying to execute is as below (I want to move this to a python script).   
```pytype --pythonpath=./project_path/xxx --python-version=3.7 --no-report-errors --keep-going --protocols --output=./storage python_file_path.py```

I saw a couple of examples that use `config.Options` in the test cases. But I am not sure about the correct method that I should invoke. 

Thank you!

**Comment by rchen152** [comment]
Unfortunately, there isn't an easy way to do this. Tests use the single-file pytype tool (`pytype-single`), which can indeed be used as a library and configured using a config.Options object, but the whole-project analysis tool writes output to a local directory and uses the ninja build system (via its own subprocess calls) to run `pytype-single`. We could wrap the whole thing in a method, sure, but it would be a binary masquerading as a library.

If you just want to be able to call pytype more easily from Python code, you could put your options in a [configuration file](https://github.com/google/pytype/blob/7e32f843ebcb63f6c534b0794885d917f383029c/pytype/tools/analyze_project/main.py#L22) and invoke [`analyze_project.main()`](https://github.com/google/pytype/blob/7e32f843ebcb63f6c534b0794885d917f383029c/pytype/tools/analyze_project/main.py#L22).
