### ISSUE TITLE
No attribute 'wraps' on module 'contextlib' [module-attr]

### ISSUE THREAD

**Issue by jonathf** [google/pytype#867]
I have a project I want to add annotation to and pytype looks like a great project for helping out adding it quickly.
I start running pytype on the project and it fails here and there. Mostly because of code that needs to be cleaned up.
But I hit a roadblock when the error I recieved was from functools.wraps.

To reproduce, I create the file `example.py`:
```python
import contextlib

def foo(func):
    @contextlib.wraps(func)
    def _func():
        return func()
    return _func
```
And I run the following code:
```sh
python3.8 -m venv venv
. venv/bin/activate
pip install pytype
pytype example.py
```

From which I get the following output:
```
[pip install stuff]
Installing collected packages: six, pyyaml, decorator, networkx, importlab, ninja, typed-ast, attrs, toml, pytype
Successfully installed attrs-20.3.0 decorator-4.4.2 importlab-0.6.1 networkx-2.5 ninja-1.10.0.post2 pytype-2021.3.10 pyyaml-5.4.1 six-1.15.0 toml-0.10.2 typed-ast-1.4.2
WARNING: You are using pip version 20.2.1; however, version 21.0.1 is available.
You should consider upgrading via the '/home/jonathf/work/venv/bin/python3.8 -m pip install --upgrade pip' command.
Computing dependencies
Analyzing 1 sources with 0 local dependencies
ninja: Entering directory `/home/jonathf/work/.pytype'
[1/1] check example
FAILED: /home/jonathf/work/.pytype/pyi/example.pyi
/home/jonathf/work/venv/bin/python3.8 -m pytype.single --imports_info /home/jonathf/work/.pytype/imports/example.imports --module-name example -V 3.8 -o /home/jonathf/work/.pytype/pyi/example.pyi --analyze-annotated --nofail --quick /home/jonathf/work/example.py
File "/home/jonathf/work/example.py", line 4, in foo: No attribute 'wraps' on module 'contextlib' [module-attr]

For more details, see https://google.github.io/pytype/errors.html#module-attr
ninja: build stopped: subcommand failed.
Leaving directory '/home/jonathf/work/.pytype'
```

Not sure if related, but I do have `python2.7` available in path, and it has the `contextlib2` package installed, backporting `contextlib.wraps` to 2.7. Obviously the same package is not installed in the pytype environment.

**Comment by rchen152** [comment]
Thanks for the report! While `wraps` is indeed accessible from `contextlib` at runtime, it doesn't look like it's meant to be a public member of that module: `contextlib` [imports `functools.wraps`](https://github.com/python/cpython/blob/2d1cbe4193499914ccc9d217ea63eb17ff927c91/Lib/contextlib.py#L6) for its own use. I'd suggest changing
```
import contextlib

def foo(func):
    @contextlib.wraps(func)
    def _func():
        return func()
    return _func
```
to
```
import functools

def foo(func):
    @functools.wraps(func)
    def _func():
        return func()
    return _func
```
Would that work for your use case?

**Comment by jonathf** [comment]
Ah, how silly of me. That solved the problem. Thank you for helping me out.
