### ISSUE TITLE
TypedDict not found in typing, with Python 3.8

### ISSUE THREAD

**Issue by stefano-maggiolo** [google/pytype#873]
I'm trying to run pytype on my project (https://github.com/cms-dev/cms) and run into an unexpected error, which might also be a problem with my config.

```
File "/home/s/github/cms/cms/util.py", line 33, in <module>: Couldn't import pyi for 'chardet' [pyi-error]
  No TypedDict in module typing, referenced from 'chardet'
```

Apparently, TypedDict has been introduced in Python 3.8, and I'm using 3.8.7 (in a virtualenv):

```
$ python --version
Python 3.8.7
```

Looking at the [code throwing the error](https://github.com/python/typeshed/blob/master/stubs/chardet/chardet/__init__.pyi#L8) it is indeed executing the 3.8 branch.

The full log of pytype is here: [cms_pytype.txt](https://github.com/google/pytype/files/6217580/cms_pytype.txt)

**Comment by rchen152** [comment]
Thanks for the report! This looks like https://github.com/google/pytype/issues/832, so I'm going to close this issue in favor of that one.
