### ISSUE TITLE
Add support for protocol buffers

### ISSUE THREAD

**Issue by martindemello** [google/pytype#89]
There should be a way to generate pyi files from protobuf definitions, either as part of pytype or as a standalone tool.

**Comment by sivachandra** [comment]
IMO, this bug belongs here: https://github.com/google/protobuf

**Comment by gvanrossum** [comment]
See also https://github.com/dropbox/mypy-protobuf

**Comment by rchen152** [comment]
I believe this issue is obsolete now, given that we're moving in the direction of deprecating/deleting our internal tool, not opensourcing it.
