### ISSUE TITLE
PATH issues when running in windows

### ISSUE THREAD

**Issue by martindemello** [google/pytype#90]
Working:
- pip install pytype

Not working:
````
> pytype
# (doesn't launch python)

> python c:\...\Python36\Scripts\pytype t.py
cannot run pytype

> python c:\...\Python36\Scripts\pytype-single t.py
cannot find a valid python2.7 interpreter in path
````

In general, the way pytype calls subprocesses does not work in windows. A further issue is that pip install doesn't automatically put the scripts/ directory in PATH, even when running in a virtualenv.

**Comment by rchen152** [comment]
A `build.ninja` issue:

OS: Windows 10
Python version: 3.7
```
D:\New>pytype foo.py
Computing dependencies
Analyzing 1 sources with 0 local dependencies
ninja: error: build.ninja:5: expected build command name
build D:\New\pytype_output\pyi\foo.pyi: check D:\New\foo.py
        ^ near here
ninja: Entering directory `D:\New\pytype_output'
```

**Comment by hiyashichuka** [comment]
Hello 
I'm in the middle of investigating this issue.
I would like to share 2 problems.

1 change python_exe to "python"  

pytype/util.py def get_python_exe_version(python_exe):
` try:
    python_exe_version = subprocess.check_output(
         python_exe  + " -V", shell=True, stderr=subprocess.STDOUT).decode()`   ← change python_exe to "python" 

2.wrong src
Although it is unknown whether this "src" was the direct cause or not, "src" information is wrong.
Src has become 
pytype/pytd/builtins/2/typing.pytd 
or pytype/pytd/builtins/2and3/typing.pytd
or pytype/pytd/builtins/3/typing.pytd

`def parse_string(src, name=None, filename=None, python_version=None,←wrong src
                 platform=None):
  return _Parser(version=python_version, platform=platform).parse(
      src, name, filename)`


However, I cannot solve this issue even though I resolve 2 problem.
I will continue to survey this issue.

**Comment by rchen152** [comment]
I spent some time this weekend trying to install and run pytype on Windows. Didn't get it completely working and gave up after a while, but posting what I did in case it's useful to other people:

**For running pytype**
1. Downloaded Python for Windows from https://www.python.org/downloads/windows/.
1. Downloaded cmake from https://cmake.org/download/.
1. Downloaded git from https://git-scm.com/download/win.
1. Downloaded Microsoft C++ Build Tools from https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2019.

I made sure to check all the options to add tools to the system path, so things would work as expected from the command prompt. At this point, I was able to `pip install pytype`. (CMake and git may or may not be necessary; I didn't go back and check.)

**For developing pytype**
1. After setting up everything in the previous section, additionally downloaded winflexbison from https://sourceforge.net/projects/winflexbison/ and manually edited the *system* PATH variable to include the directory containing win_bison.exe and win_flex.exe. (If you're not doing this on a disposable VM, you'll probably want to find a way to modify PATH without editing system-wide environment variables.)
1. Launched the Visual Studio command prompt. Downloading the build tools should have given you several applications with names that are variations on "Developer Command Prompt for VS 2019", for x64, x86, and cross-compilation between the two.

At this point, using the VS command prompt, I could clone the pytype source code and do `pip install .`.

**Comment by rchen152** [comment]
Deduplicating this against the more general https://github.com/google/pytype/issues/1154.
