### ISSUE TITLE
TypeError: evolve() argument after ** must be a mapping, not NamedType

### ISSUE THREAD

**Issue by Akuli** [google/pytype#909]
Somehow I managed to trigger this bug in two typeshed pull requests: https://github.com/python/typeshed/pull/5349 and https://github.com/python/typeshed/pull/5350

The error messages are visible in typeshed CI, but if needed, I can try to make a minimal reproducing example.

**Comment by Akuli** [comment]
Actually, this seems to happen on every pull request, even https://github.com/python/typeshed/pull/5351 which does not touch any stubs.

**Comment by dpp23** [comment]
I've had the same issue - the problem is a new version of one of the requirements of pytype - `attrs`. Pinning to `20.3.0` worked. The issue is with `21`

**Comment by rchen152** [comment]
Oof. Thanks @dpp23 for finding the problem - the attrs developers seem aware of the issue (https://github.com/python-attrs/attrs/issues/804), so I think I'll pin attrs to 20.3.0 and wait for a fix.

**Comment by hynek** [comment]
Hi, sorry about this. 21.2 with a fixed `evolve()` is on PyPI.

**Comment by rchen152** [comment]
Sweet, thanks for the quick fix!
