### ISSUE TITLE
Support PEP 647: TypeGuard

### ISSUE THREAD

**Issue by JelleZijlstra** [google/pytype#916]
I'd like to start using https://www.python.org/dev/peps/pep-0647/ in typeshed. Do you have any plans in that direction already?

I can look into adding basic support to unblock typeshed, which would mean simply interpreting `TypeGuard[...]` as an alias for `bool`.

**Comment by rchen152** [comment]
No plans yet, but as you said, it shouldn't be too difficult for us to just interpret `TypeGuard` as `bool` for now.

**Comment by rchen152** [comment]
I should have some time to do this tomorrow afternoon.

**Comment by JelleZijlstra** [comment]
Thanks!

**Comment by rchen152** [comment]
I've implemented rewriting TypeGuard[X] to bool in stubs; I'll try to do a release tomorrow.

**Comment by rchen152** [comment]
Ok, pytype 2021.05.14 is out. Please let me know if you run into any issues using TypeGuard in stubs.

**Comment by JelleZijlstra** [comment]
Thanks again!

**Comment by rchen152** [comment]
We've got a basic implementation of TypeGuard done. It'll be in the next release, hopefully tomorrow.
