### ISSUE TITLE
Bad link in README.md to https://github.com/google/importlab/blob/master/.travis.yml

### ISSUE THREAD

**Issue by MrCull** [google/pytype#930]
This file does not exist any more in the importlab repo.

In the README.md of this repo it says: _"see this example of a GitHub project that runs pytype on Travis."_
With the link under the word "example".
Perhaps that other report does not use PTYE any more, or needs referencing in a different way?

This issue was found using a tool that I created which finds deadlinks in GitHub repos and can be used to re-check this repo once the PR to resolve this issue is committed: https://githubreadmechecker.com/Home/Search?SingleRepoUri=https%3A%2F%2Fgithub.com%2Fgoogle%2Fpytype&User=&NumberOfReposToSearchFor=&MinStar=&UpdatedAfter=&SearchSort=2&SortAscDsc=1

**Comment by rchen152** [comment]
Fixed by https://github.com/google/pytype/pull/935
