### ISSUE TITLE
Importing pyi files with multi-level absolute imports causes a SyntaxError

### ISSUE THREAD

**Issue by pefoley2** [google/pytype#94]
e.g.
Analyzing 1 sources with 289 dependencies
File "/home/peter/cslbot/cslbot/hooks/reddit.py", line 21, in <module>: Couldn't import pyi for 'requests' [pyi-error]
    File: "/usr/local/virtualenvs/cslbot/lib/python3.6/site-packages/pytype/typeshed/third_party/2and3/requests/packages/urllib3/util/timeout.pyi", line 2
      b'from .. import exceptions'
              ^
  ParseError: syntax error, unexpected IMPORT, expecting NAME or '.'

For more details, see https://github.com/google/pytype/blob/master/docs/errors.md#pyi-error.

**Comment by rchen152** [comment]
Hmm, the problem seems to be that the third_party/ typeshed stubs aren't tested against pytype (since we don't use them inside Google), so they contain constructs that pytype doesn't support.
