### ISSUE TITLE
pytype does not seem to work with `Number`

### ISSUE THREAD

**Issue by rentruewang** [google/pytype#974]
pytype fails when assigning `int` to `Number`, which shouldn't happen because `int` is a subclass of `Number`.

```python
>>> from numbers import Number
>>> issubclass(int, Number)
True
```

However, for the following code, there shouldn't be a problem:

```python
def print_number(num: Number) -> None:
    print(num)

x: Number = 3

print_number(x)
```

pytype says:

```log
Type annotation for x does not match type of assignment [annotation-type-mismatch]
  Annotation: numbers.Number
  Assignment: int
```

For the following code: 

```python

def print_number(num: Number) -> None:
    print(num)

x: int = 4

print_number(x)
```

pytype says:

```log
Function print_number was called with the wrong arguments [wrong-arg-types]
         Expected: (num: numbers.Number)
  Actually passed: (num: int)
```

I'm not sure what's the cause here, as `Number` is defined:

```python
class Number(metaclass=ABCMeta):
    """All numbers inherit from this class.

    If you just want to check if an argument x is a number, without
    caring what kind, use isinstance(x, Number).
    """
    __slots__ = ()

    # Concrete numeric types must provide their own hash implementation
    __hash__ = None
```

And pytype doesn't have any issues with my other customly defined `ABC`s.

**Comment by JelleZijlstra** [comment]
See python/mypy#3186 for reference. The issue is in the mypy repo, but many of the reasons for why this is hard also apply to pyright. In particular, typeshed doesn't provide a way to know that `int` is a `Number`, and because `Number` defines no methods, it's not clear how useful it would be for typing anyway.

**Comment by rentruewang** [comment]
I see. Should I close the issue or leave it open?

**Comment by JelleZijlstra** [comment]
I'm not a pytype maintainer, so I'll leave that to the people who actually work on pytype. (Sorry this morning I wasn't fully awake and I thought I was in the pyright repo.)

**Comment by rentruewang** [comment]
You've got a point that `Number` isn't that useful. I've changed my code to using `Union[int, float]`. Closing this for now.
