### ISSUE TITLE
pyi error for struct_pb2

### ISSUE THREAD

**Issue by dpcollins-google** [google/pytype#977]
FAILED: /Users/dpcollins/Documents/python-pubsublite/.pytype/pyi/google/cloud/pubsublite/internal/wire/pubsub_context.pyi 
/usr/local/Caskroom/miniconda/base/bin/python -m pytype.single --imports_info /Users/dpcollins/Documents/python-pubsublite/.pytype/imports/google.cloud.pubsublite.internal.wire.pubsub_context.imports --module-name google.cloud.pubsublite.internal.wire.pubsub_context -V 3.8 -o /Users/dpcollins/Documents/python-pubsublite/.pytype/pyi/google/cloud/pubsublite/internal/wire/pubsub_context.pyi --analyze-annotated --nofail --quick /Users/dpcollins/Documents/python-pubsublite/google/cloud/pubsublite/internal/wire/pubsub_context.py
File "/Users/dpcollins/Documents/python-pubsublite/google/cloud/pubsublite/internal/wire/pubsub_context.py", line 20, in <module>: Couldn't import pyi for 'google.protobuf.struct_pb2' [pyi-error]
  Couldn't find _Type in google.protobuf.descriptor_pb2

when running `pytype google.cloud.pubsublite` from the root of https://github.com/googleapis/python-pubsublite

**Comment by rchen152** [comment]
That's one of the type stubs on https://github.com/python/typeshed/blob/master/tests/pytype_exclude_list.txt that pytype can't handle =/ Maybe we should ignore pyi errors in stubs on pytype_exclude_list.

One thing you can do as a workaround is add `--disable=pyi-error` either to your pytype command-line invocation or in your [config file](https://github.com/google/pytype#config-file).

**Comment by rchen152** [comment]
Just realized that this issue is the same as https://github.com/google/pytype/issues/764, so I'm going to close this in favor of the latter.
